// Generated by @happyvertical/smrt-mobile-contract (framework contract).
// Do not edit by hand — regenerate with `pnpm --filter @happyvertical/smrt-mobile-contract generate:framework`.

package com.happyvertical.smrt.mobile.contract

const val SMRT_MOBILE_CONTRACT_SCHEMA_VERSION: Int = 1
const val SMRT_MOBILE_CONTRACT_VERSION: String = "2026-07-01.v1"
