// Generated by @happyvertical/smrt-mobile-contract (framework contract).
// Do not edit by hand — regenerate with `pnpm --filter @happyvertical/smrt-mobile-contract generate:framework`.

package com.happyvertical.smrt.mobile.contract

import kotlinx.serialization.Serializable

/**
 * Decimal values cross the wire as strings so no precision is lost between
 * the server's DECIMAL columns and platform floating-point types.
 */
typealias DecimalString = String

@Serializable
data class Measurement(
    val value: DecimalString,
    val unit: String,
    val source: String? = null,
)
