/**
 * The application's SMRT runtime and collection access.
 *
 * `runtime` composes the configured profile (local SQLite or deployed
 * PostgreSQL), storage custody, the owner bootstrap, tenant selection, and the
 * signed session; `src/hooks.server.ts` mounts its `handle` and `init`.
 * Generated API routes import `getCollection` from this file.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  acquireWriterLease,
  createProviderReadinessProbe,
  prepareApplicationStateRoot,
} from '@happyvertical/smrt-app-runtime';
import { createSmrtSvelteKitRuntime } from '@happyvertical/smrt-app-runtime/sveltekit';
import {
  ObjectRegistry,
  type SmrtClassOptions,
  type SmrtObject,
} from '@happyvertical/smrt-core';
import { loadManifestFromPathSync } from '@happyvertical/smrt-core/manifest';

// Import all SMRT objects to register them.
import '../objects/index.js';

/**
 * Whether `error` reports that the generated register module itself is
 * absent. Only the missing module named by the error counts (Node's `url`,
 * or `Cannot find module '<path>'` from Node and Vite's module runner); a
 * package or file that an existing generated module imports is a different
 * missing module and is never matched.
 */
function isMissingRegisterModule(error: unknown): boolean {
  const { code, url, message } = (error ?? {}) as {
    code?: unknown;
    url?: unknown;
    message?: unknown;
  };
  if (code !== 'ERR_MODULE_NOT_FOUND') return false;
  const missing =
    typeof url === 'string'
      ? url
      : typeof message === 'string'
        ? /^Cannot find module '([^']+)'/.exec(message)?.[1]
        : undefined;
  if (!missing) return false;
  const path = missing.replace(/^file:\/\//, '').replace(/[?#].*$/, '');
  return /\/lib\/server\/smrt-register\.(?:js|ts)$/.test(path);
}

// Upgrade those registrations to package-qualified identities
// (`<package>:<Class>`) — required to link each class to its scanned field
// metadata below. The `smrt()` Vite plugin generates this module on every
// dev/build run (it is gitignored, like the generated API routes); guard the
// import so a fresh checkout that has not run the plugin yet still boots.
try {
  // @ts-ignore generated by the smrt() Vite plugin before a build starts
  await import('./smrt-register.js');
} catch (error) {
  // Not generated yet — the first `pnpm dev` / `pnpm build` creates it. Any
  // other failure, including a missing dependency of an existing generated
  // module (an uninstalled extension package), must fail startup.
  if (!isMissingRegisterModule(error)) throw error;
}

// Hydrate field metadata for this app's own objects from the local manifest
// (`.smrt/manifest.json`). Without it the runtime only knows the framework
// base fields and server-side writes would silently drop your domain columns.
const localManifestPath = join(process.cwd(), '.smrt', 'manifest.json');
if (existsSync(localManifestPath)) {
  loadManifestFromPathSync(localManifestPath);
}

export const runtime = createSmrtSvelteKitRuntime({
  // Every local web writer (`pnpm dev`, `pnpm app:start`) holds the same
  // single-writer lease as `smrt app` operations, so imports and backups
  // fail closed while the app is running.
  acquireWriterLease: (context) =>
    acquireWriterLease(prepareApplicationStateRoot(context), {
      operationInstance: process.env.SMRT_OPERATION_INSTANCE,
    }),
  // Deployed profiles prove authentication, asset, and secret readiness
  // through the installed modules named by SMRT_*_READINESS_MODULE.
  providerReadiness: createProviderReadinessProbe,
  // Per-object overrides, for example:
  //   AuditLog: { db: { type: 'postgres', url: process.env.AUDIT_DB_URL! } }
  classOverrides: {},
});

/**
 * Collection options for a class. Call per request and never keep the result:
 * under `database-rls` isolation it carries the request's transaction.
 */
export function getSmrtConfig(className: string): SmrtClassOptions {
  return runtime.classOptions(className);
}

/**
 * Get a collection for a SMRT class, scoped to the current request.
 *
 *   const items = await getCollection<Item>('Item');
 */
export async function getCollection<T extends SmrtObject>(className: string) {
  return await ObjectRegistry.getCollection<T>(
    className,
    runtime.classOptions(className),
  );
}
