// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Get single factualcontent
export const GET: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:FactualContent',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(404, '@happyvertical/smrt-content:FactualContent not found');

  return json(item);
};

// Update factualcontent
export const PUT: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:FactualContent',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(404, '@happyvertical/smrt-content:FactualContent not found');

  const data = await request.json();
  Object.assign(item, data);
  await item.save();

  return json(item);
};

// Delete factualcontent
export const DELETE: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:FactualContent',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(404, '@happyvertical/smrt-content:FactualContent not found');

  await item.delete();
  return json({ success: true });
};
