/**
 * Per-package browser capability (#3709), derived from the browser gate.
 *
 * The browser gate (#3621) already says, for every model package, whether its
 * root entry builds for a browser: a package is `server-only` exactly when it
 * is listed in `EXPECTED_BROWSER_FAILURES` (the ratchet fails on any other
 * outcome, in both directions). This module turns that list into the table a
 * manifest build reads, so the planner's catalog can label features honestly.
 *
 * Two refinements over the raw list:
 *
 *  - **Inheritance.** The ratchet attributes a defect to the package that owns
 *    the fix, so a dependent of a failing package passes the ratchet while
 *    still dragging the failure into any browser bundle. A package is
 *    therefore `server-only` too when a workspace package it depends on
 *    (transitively, through `dependencies`) is, and records them in `via`.
 *  - **Platform baseline.** `smrt-core` is the one package every other package
 *    builds on; its tracked defects (#2838, #3635) are the platform's, not each
 *    dependent's, so it does not propagate.
 *
 * The table is generated into `smrt-core` (which reads it while building every
 * manifest) and checked by `browser-capability.spec.ts`; see AGENTS.md.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import type { ExpectedFailure, ModelPackage } from './boundary.js';

/** Mirrors `PackageBrowserCapability` in `@happyvertical/smrt-types`. */
export interface PackageBrowserCapability {
  status: 'browser-safe' | 'server-only';
  issues?: string[];
  reason?: string;
  via?: string[];
}

/** Packages whose own failures describe the platform and never propagate. */
export const PLATFORM_BASELINE_PACKAGES: readonly string[] = [
  '@happyvertical/smrt-core',
];

/** A gated package and the workspace packages it depends on. */
export interface CapabilityInput {
  name: string;
  dependencies: readonly string[];
}

/** Where the generated table lives, relative to the workspace root. */
export const CAPABILITY_TABLE_PATH =
  'packages/core/src/manifest/browser-capability.generated.ts';

/** `'#3624, #3626'` to `['#3624', '#3626']`. */
function splitIssues(issue: string): string[] {
  return issue
    .split(/[\s,]+/)
    .map((part) => part.trim())
    .filter(Boolean);
}

export function deriveBrowserCapabilities(
  packages: readonly CapabilityInput[],
  expected: Readonly<Record<string, ExpectedFailure>>,
): Record<string, PackageBrowserCapability> {
  const byName = new Map(packages.map((pkg) => [pkg.name, pkg]));
  const propagates = (name: string): boolean =>
    name in expected && !PLATFORM_BASELINE_PACKAGES.includes(name);

  /** Failing packages `name` reaches through `dependencies`. */
  const inheritedFrom = (name: string): string[] => {
    const seen = new Set<string>([name]);
    const found = new Set<string>();
    const queue = [name];
    for (let i = 0; i < queue.length; i++) {
      for (const dep of byName.get(queue[i] as string)?.dependencies ?? []) {
        if (seen.has(dep) || !byName.has(dep)) continue;
        seen.add(dep);
        if (propagates(dep)) found.add(dep);
        queue.push(dep);
      }
    }
    return [...found].sort();
  };

  const out: Record<string, PackageBrowserCapability> = {};
  for (const pkg of [...packages].sort((a, b) =>
    a.name.localeCompare(b.name),
  )) {
    const own = expected[pkg.name];
    const via = inheritedFrom(pkg.name);
    if (!own && via.length === 0) {
      out[pkg.name] = { status: 'browser-safe' };
      continue;
    }
    const issues = [
      ...new Set([
        ...(own ? splitIssues(own.issue) : []),
        ...via.flatMap((dep) => splitIssues(expected[dep]?.issue ?? '')),
      ]),
    ].sort();
    out[pkg.name] = {
      status: 'server-only',
      ...(issues.length > 0 ? { issues } : {}),
      ...(own ? { reason: own.reason } : {}),
      ...(via.length > 0 ? { via } : {}),
    };
  }
  return out;
}

/** Reads the workspace dependencies of each gated package from `package.json`. */
export function readCapabilityInputs(
  packages: readonly ModelPackage[],
): CapabilityInput[] {
  return packages.map((pkg) => {
    const manifest = JSON.parse(
      readFileSync(path.join(pkg.dir, 'package.json'), 'utf8'),
    ) as {
      dependencies?: Record<string, string>;
      optionalDependencies?: Record<string, string>;
    };
    return {
      name: pkg.name,
      dependencies: Object.keys({
        ...manifest.dependencies,
        ...manifest.optionalDependencies,
      }),
    };
  });
}

/** The exact source of the generated table in `smrt-core`. */
export function renderCapabilityModule(
  table: Readonly<Record<string, PackageBrowserCapability>>,
): string {
  return `/**
 * GENERATED by packages/bundle-gate (browser-capability.spec.ts); do not edit.
 * Regenerate with \`UPDATE_BROWSER_CAPABILITY=1 pnpm --filter
 * @happyvertical/smrt-bundle-gate test\` after the browser gate's
 * expected-failures list or a package's dependencies change (#3709).
 *
 * Per-package browser capability derived from the browser gate (#3621): a
 * package is \`server-only\` when it, or a workspace package it depends on,
 * is listed as an expected failure. The manifest build emits the entry for the
 * package being built as \`browser\`, and uses it to classify its recipes.
 */
import type { PackageBrowserCapability } from '@happyvertical/smrt-types';

// biome-ignore format: generated file, keep the generator's layout
export const PACKAGE_BROWSER_CAPABILITY: Readonly<Record<string, PackageBrowserCapability>> = {
${Object.entries(table)
  .map(
    ([name, entry]) => `  ${JSON.stringify(name)}: ${JSON.stringify(entry)},`,
  )
  .join('\n')}
};
`;
}
