// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom collection method: resolveForContent
export const POST: RequestHandler = async ({ request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:ContentGovernanceAssignment',
  );
  const typedCollection = collection as any;
  if (!collection)
    throw error(
      500,
      '@happyvertical/smrt-content:ContentGovernanceAssignment collection is not registered',
    );

  const options = await request.json();
  const result = await typedCollection.resolveForContent(options);

  return json({ action: 'resolveForContent', result });
};
