packages:
  - 'packages/*'
  - 'packages/smrt-playground/host'

catalog:
  '@happyvertical/ai': ^0.71.18
  '@happyvertical/cache': ^0.71.18
  '@happyvertical/documents': ^0.71.18
  '@happyvertical/email': ^0.71.18
  '@happyvertical/encryption': ^0.71.18
  '@happyvertical/files': ^0.71.18
  '@happyvertical/geo': ^0.71.18
  '@happyvertical/images': ^0.71.18
  '@happyvertical/jobs': ^0.71.18
  '@happyvertical/json': ^0.71.18
  '@happyvertical/logger': ^0.71.18
  '@happyvertical/messages': ^0.71.18
  '@happyvertical/ocr': ^0.60.29
  '@happyvertical/pdf': ^0.62.20
  '@happyvertical/projects': ^0.71.18
  '@happyvertical/repos': ^0.71.18
  '@happyvertical/secrets': ^0.71.18
  '@happyvertical/spider': ^0.60.9
  '@happyvertical/sql': ^0.71.18
  '@happyvertical/utils': ^0.71.18
