// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom action: toJSON
export const POST: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:FactualContent',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(404, '@happyvertical/smrt-content:FactualContent not found');

  const result = await item.toJSON();

  return json({ action: 'toJSON', result });
};
