// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';
// Note: @happyvertical/smrt-content:ContentReview is auto-registered by the Vite plugin scanner

// List all @happyvertical/smrt-content:contentreviews
export const GET: RequestHandler = async ({ url }) => {
  const limit = Number(url.searchParams.get('limit')) || 50;
  const offset = Number(url.searchParams.get('offset')) || 0;

  const collection = await getCollection('@happyvertical/smrt-content:ContentReview');
  const items = await collection.list({ limit, offset });
  const count = await collection.count();

  return json({ items, count, limit, offset });
};

// Create new @happyvertical/smrt-content:contentreview
export const POST: RequestHandler = async ({ request }) => {
  const data = await request.json();

  const collection = await getCollection('@happyvertical/smrt-content:ContentReview');
  const item = await collection.create(data);
  await item.save();

  return json(item, { status: 201 });
};
