/**
 * Service exports for smrt-users
 * @packageDocumentation
 */

export {
  ACCESS_REQUEST_CAPABILITIES,
  type AccessRequestAuthorizationContext,
  type AccessRequestAuthorizer,
  type AccessRequestCapability,
  AccessRequestError,
  type AccessRequestErrorCode,
  type AccessRequestEvent,
  type AccessRequestEventHandler,
  type AccessRequestEventType,
  AccessRequestService,
  type AccessRequestServiceOptions,
  type ApproveAccessRequestOptions,
  type CancelAccessRequestOptions,
  type CreateAccessRequestInput,
  type DeclineAccessRequestOptions,
  type GraduateAccessRequestOptions,
  type GraduateAccessRequestResult,
  type GraduateExistingTenantOption,
  type GraduateNewTenantOption,
  type GraduateTenantOption,
  type ListAccessRequestsFilter,
} from './AccessRequestService.js';
export {
  ANCESTOR_READ_ACTION,
  type AncestorReadPackageConfig,
  type AncestorReadPolicy,
  DEFAULT_ANCESTOR_READ_MAX_DEPTH,
  getConfiguredAncestorReadPolicy,
  isAncestorReadableSlug,
  type NormalizedAncestorReadPolicy,
  normalizeAncestorReadPolicy,
} from './AncestorReadPolicy.js';
export {
  type ClearPinInput,
  DEFAULT_DEVICE_PERSON_IDLE_SECONDS,
  DEFAULT_PIN_MANAGE_PERMISSION,
  DeviceCredentialError,
  DeviceCredentialForbiddenError,
  DeviceCredentialPolicyError,
  DeviceCredentialService,
  type DeviceCredentialServiceOptions,
  type DeviceCredentialVerification,
  type DeviceCredentialVerifier,
  type DeviceSignInContext,
  type DeviceSignInInput,
  type DeviceSignInResult,
  ensurePinPermissionsRegistered,
  PIN_LOGIN_KIND,
  PIN_PERMISSION_DEFINITIONS,
  type PinPolicyOptions,
  type PinSignInInput,
  PinVerifier,
  type ResetPinInput,
  type SetPinInput,
} from './DeviceCredentialService.js';
export {
  DEFAULT_LOGIN_ATTEMPT_WINDOW_SECONDS,
  DEFAULT_LOGIN_LOCKOUT_BASE_SECONDS,
  DEFAULT_LOGIN_LOCKOUT_FACTOR,
  DEFAULT_LOGIN_LOCKOUT_MAX_SECONDS,
  DEFAULT_LOGIN_MAX_ATTEMPTS,
  DurableLoginAuditSink,
  InvalidCredentialsError,
  type LoginAttemptDecision,
  type LoginAttemptDenied,
  type LoginAttemptLease,
  LoginAttemptLimiter,
  type LoginAttemptLimiterOptions,
  type LoginAuditEntry,
  type LoginAuditSink,
  type LoginFailureOutcome,
  type LoginLockoutOptions,
  LoginRateLimitError,
  type ReserveLoginAttemptOptions,
} from './LoginAttemptLimiter.js';
export {
  MagicLinkError,
  type MagicLinkResult,
  MagicLinkService,
  type MagicLinkServiceOptions,
  type MagicLinkVerifyResult,
} from './MagicLinkService.js';
export {
  MobileAuthError,
  type MobileAuthErrorCode,
  MobileAuthService,
  type MobileAuthServiceOptions,
  type MobileBootstrapContext,
  type MobileLoginContext,
  type MobileLogoutResult,
  type MobileRequestMeta,
  type MobileResolvedUser,
  type MobileTenantContext,
  readMobileBearerToken,
  validateMobileRedirectUri,
} from './MobileAuthService.js';
export {
  SmrtOAuthAuthorizationService,
  type SmrtOAuthAuthorizationServiceOptions,
  type SmrtOAuthGrantSummary,
} from './OAuthAuthorizationService.js';
export {
  SMRT_OAUTH_GRANT_CLAIM,
  SmrtOAuthAuthorizationStorage,
  type SmrtOAuthAuthorizationStorageOptions,
} from './OAuthAuthorizationStorage.js';
export {
  type CreateAuthorizationUrlOptions,
  decodeOidcTransaction,
  encodeOidcTransaction,
  getUsersOidcConfig,
  type OidcCallbackResult,
  OidcLoginError,
  type OidcLoginResult,
  OidcLoginService,
  type OidcLoginServiceOptions,
  type OidcProviderConfig,
  type OidcProviderKind,
  type OidcProviderMetadata,
  type OidcProviderResolution,
  type OidcProviderResolutionOptions,
  type OidcTokenEndpointAuthMethod,
  type OidcTokenSet,
  type OidcTransaction,
  type ResolvedOidcProviderConfig,
  resolveOidcProviderConfig,
  type UsersOidcConfig,
} from './OidcLoginService.js';
export {
  assertOperationPermission,
  checkOperationPermission,
  hasOperationPermission,
  type OperationPermissionAllowReason,
  type OperationPermissionDecision,
  type OperationPermissionDenyReason,
  OperationPermissionError,
  type OperationPermissionOptions,
} from './OperationPermissionService.js';
export {
  type ChangePasswordInput,
  type ClearPasswordInput,
  DEFAULT_PASSWORD_DENYLIST,
  DEFAULT_PASSWORD_MANAGE_PERMISSION,
  DEFAULT_PASSWORD_MAX_LENGTH,
  DEFAULT_PASSWORD_MIN_LENGTH,
  ensurePasswordPermissionsRegistered,
  PASSWORD_LOGIN_KIND,
  PASSWORD_MAX_LENGTH_CEILING,
  PASSWORD_PERMISSION_DEFINITIONS,
  PasswordCredentialError,
  PasswordCredentialForbiddenError,
  PasswordCredentialService,
  type PasswordCredentialServiceOptions,
  type PasswordPolicyContext,
  PasswordPolicyError,
  type PasswordPolicyOptions,
  type PasswordSignInInput,
  type PasswordSignInResult,
  type ResetPasswordInput,
  type SetPasswordInput,
} from './PasswordCredentialService.js';
export {
  deriveOperationPermissionCollectionName,
  deriveOperationPermissionSlug,
  normalizeOperationPermissionAction,
  type OperationPermissionCollectionInput,
  type PermissionCatalog,
  PermissionCatalogService,
  type PermissionCatalogSource,
  type PermissionCatalogSyncResult,
  type PermissionDefinition,
  type PostgresPermissionAction,
  type PostgresPermissionBinding,
  registerPermissionDefinitions,
  syncPermissionCatalog,
  type UsersConfig,
} from './PermissionCatalogService.js';
export {
  type PermissionResolutionOptions,
  type PermissionResolutionResult,
  PermissionResolver,
  type PermissionResolverOptions,
  type TenantPermissionInheritanceResult,
} from './PermissionResolver.js';
export {
  applyPostgresPermissionPolicies,
  type GeneratePostgresPermissionSqlResult,
  generatePostgresPermissionSql,
  type PostgresPermissionPolicyReportItem,
  type PostgresPermissionPolicyTarget,
} from './PostgresPermissionPolicies.js';
export {
  type CreateResourceGrantOptions,
  checkResourceOperationPermission,
  MAX_RESOURCE_GRANT_DELEGATION_DEPTH,
  type ResourceGrantDecision,
  ResourceGrantService,
  type ResourceIdentity,
  type ResourceIdentityVerifier,
  type ResourceOperationPermissionOptions,
  type RevokeResourceGrantOptions,
} from './ResourceGrantService.js';
export {
  getCurrentSessionPermissionContext,
  getRequestScopedDatabase,
  type PrincipalPermissionRuntimeOptions,
  type SessionPermissionRuntimeContext,
  type SessionPermissionRuntimeOptions,
  withPrincipalPermissionContext,
  withSessionPermissionContext,
} from './SessionPermissionContext.js';
export {
  type SessionContext,
  type SessionParentContext,
  SessionService,
  type SessionServiceOptions,
  type SwitchTenantResult,
} from './SessionService.js';
export {
  type EnsureTenantResult,
  TenantService,
  type TenantWithOwnershipResult,
} from './TenantService.js';
export {
  type ApproveCliAuthRequestInput,
  type CliAuthStartResult,
  type CliAuthTokenResult,
  DEFAULT_CLI_AUTH_APPROVE_ATTEMPT_WINDOW_SECONDS,
  DEFAULT_CLI_AUTH_MAX_APPROVE_ATTEMPTS,
  DEFAULT_CLI_AUTH_POLL_INTERVAL_SECONDS,
  DEFAULT_CLI_AUTH_REQUEST_TTL_SECONDS,
  DEFAULT_CLI_SESSION_TTL_SECONDS,
  TERMINAL_APPROVE_LOGIN_KIND,
  TerminalAuthError,
  TerminalAuthRateLimitError,
  TerminalAuthService,
  type TerminalAuthServiceOptions,
} from './TerminalAuthService.js';
