/**
 * Vitest globalSetup hook.
 *
 * The template's `template/tsconfig.json` extends `./.svelte-kit/tsconfig.json`
 * — a file that SvelteKit generates by running `svelte-kit sync` inside a
 * consumer project. We never run `svelte-kit sync` here in the monorepo,
 * but Vite's `tsconfck` walks up from imported template source files to
 * find that tsconfig and tries to resolve its `extends` chain. The
 * resolution fails because `.svelte-kit/tsconfig.json` doesn't exist yet,
 * which crashes the test runner before any spec executes.
 *
 * This setup writes a minimal stub at test-startup time and cleans it up
 * at teardown. The stub is not committed (`.svelte-kit/` is gitignored)
 * and isn't shipped to consumers (`copyTemplate()` filters the directory
 * out, but a fresh test run regenerates it for tsconfck either way).
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const STUB_DIR = join(__dirname, '..', '..', 'template', '.svelte-kit');
const STUB_FILE = join(STUB_DIR, 'tsconfig.json');

const STUB_CONTENT = JSON.stringify(
  {
    '//':
      'Test-only stub generated by __tests__/setup/svelte-kit-stub.ts. ' +
      'Real consumers get this regenerated by `svelte-kit sync`.',
    compilerOptions: {
      paths: {
        $lib: ['../src/lib'],
        '$lib/*': ['../src/lib/*'],
      },
      verbatimModuleSyntax: true,
      isolatedModules: true,
      lib: ['esnext', 'DOM', 'DOM.Iterable'],
      moduleResolution: 'bundler',
      module: 'esnext',
      noEmit: true,
      target: 'esnext',
    },
    include: ['../src/**/*.ts', '../src/**/*.js'],
    exclude: ['../node_modules/**'],
  },
  null,
  2,
);

export async function setup(): Promise<void> {
  mkdirSync(STUB_DIR, { recursive: true });
  writeFileSync(STUB_FILE, STUB_CONTENT);
}

export async function teardown(): Promise<void> {
  rmSync(STUB_DIR, { recursive: true, force: true });
}
