name: 'Setup Environment'
description: 'Setup Node.js, pnpm, system dependencies, and install project dependencies'
author: 'Happy Vertical'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

  install-deps:
    description: 'Whether to install project dependencies'
    required: false
    default: 'true'

  registry-url:
    description: 'npm registry URL (for publishing)'
    required: false
    default: ''

outputs:
  pnpm-cache-hit:
    description: 'Whether pnpm cache was hit'
    value: ${{ steps.pnpm-cache.outputs.cache-hit }}

  playwright-cache-hit:
    description: 'Whether Playwright browser cache was hit'
    value: ${{ steps.playwright-cache.outputs.cache-hit }}

  store-path:
    description: 'pnpm store path'
    value: ${{ steps.pnpm-store.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url || 'https://registry.npmjs.org' }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: |
        echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      id: pnpm-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Get Playwright version
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(npm list playwright --depth=0 --json 2>/dev/null | grep -oP '"playwright":\s*{\s*"version":\s*"\K[^"]+' || echo "1.54.2")
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install system dependencies for ONNX Runtime
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
          libstdc++6 \
          libc6-dev \
          build-essential \
          gcc \
          g++ \
          cmake \
          libgomp1 \
          libprotobuf-dev

    - name: Install project dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        # In CI, activate overrides to use local SDK workspace packages
        if [ -f .pnpmrc-ci ]; then
          echo "Activating CI-specific .pnpmrc for local SDK overrides"
          cp .pnpmrc-ci .pnpmrc
          # Use --no-frozen-lockfile when SDK workspace is present
          # because overrides convert npm packages to workspace packages
          # which changes lockfile structure
          echo "Installing with SDK workspace packages (--no-frozen-lockfile)"
          pnpm install --no-frozen-lockfile
        else
          echo "Installing with frozen lockfile"
          pnpm install --frozen-lockfile
        fi
      env:
        # Force ONNX Runtime to skip CUDA installation
        ONNXRUNTIME_NODE_INSTALL_CUDA: 'skip'

    - name: Install Playwright browsers
      if: inputs.install-deps == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        # Check if playwright is installed as a dependency
        if npx playwright --version >/dev/null 2>&1; then
          echo "Installing Playwright browsers..."
          npx playwright install --with-deps chromium
        else
          echo "Playwright not installed, skipping browser installation"
        fi
