<script lang="ts">
/**
 * Auto-generated form component from SMRT object schema
 * Demonstrates "Define Once, Consume Everywhere" - form is generated from Product class definition
 */

import type { ProductData } from '../../types';
import FieldRenderer from './FieldRenderer.svelte';

interface Props {
  data?: ProductData;
  title?: string;
  submitLabel?: string;
  readonly?: boolean;
  onSubmit?: (data: ProductData) => void;
  onChange?: (data: ProductData) => void;
}

const {
  data = {},
  title = 'Product Information',
  submitLabel = 'Save',
  readonly = false,
  onSubmit,
  onChange,
}: Props = $props();

// Auto-generated field schema from Product class
// In a full implementation, this would be generated by the SMRT plugin
const fieldSchema = [
  {
    name: 'name',
    type: 'string',
    label: 'Product Name',
    required: true,
    placeholder: 'Enter product name',
  },
  {
    name: 'description',
    type: 'string',
    label: 'Description',
    placeholder: 'Product description',
  },
  {
    name: 'category',
    type: 'string',
    label: 'Category',
    placeholder: 'Product category',
  },
  {
    name: 'manufacturer',
    type: 'string',
    label: 'Manufacturer',
    placeholder: 'Manufacturer name',
  },
  {
    name: 'model',
    type: 'string',
    label: 'Model',
    placeholder: 'Product model',
  },
  {
    name: 'specifications',
    type: 'object',
    label: 'Specifications',
    placeholder: 'Technical specifications',
  },
  { name: 'tags', type: 'array', label: 'Tags', placeholder: 'Product tags' },
] as const;

// Reactive form data
let formData = $state({ ...data });

// Update form data when props change
$effect(() => {
  formData = { ...data };
});

function _updateField(fieldName: string, value: any) {
  formData[fieldName as keyof ProductData] = value;

  // Trigger change callback
  if (onChange) {
    onChange({ ...formData });
  }
}

function _handleSubmit(event: Event) {
  event.preventDefault();
  if (onSubmit && !readonly) {
    onSubmit({ ...formData });
  }
}

function _getFieldType(
  name: string,
): 'string' | 'number' | 'boolean' | 'array' | 'object' {
  const field = fieldSchema.find((f) => f.name === name);
  return field?.type || 'string';
}
</script>

<div class="auto-form">
  <header class="form-header">
    <h2 class="form-title">{title}</h2>
    <div class="form-subtitle">
      Auto-generated from SMRT Product model
    </div>
  </header>

  <form class="form-content" onsubmit={handleSubmit}>
    {#each fieldSchema as field}
      <FieldRenderer
        fieldName={field.name}
        fieldType={field.type}
        value={formData[field.name]}
        label={field.label}
        placeholder={field.placeholder}
        required={field.required || false}
        {readonly}
        onUpdate={(value) => updateField(field.name, value)}
      />
    {/each}

    {#if !readonly}
      <div class="form-actions">
        <button type="submit" class="submit-btn">
          {submitLabel}
        </button>
        <button type="button" class="reset-btn" onclick={() => formData = {}}>
          Reset
        </button>
      </div>
    {/if}
  </form>

  <!-- Demo: Show current form state -->
  <details class="form-debug">
    <summary>Form Data (Debug)</summary>
    <pre>{JSON.stringify(formData, null, 2)}</pre>
  </details>
</div>

<style>
  .auto-form {
    max-width: 600px;
    margin: 0 auto;
    padding: 1.5rem;
    background: white;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  }

  .form-header {
    margin-bottom: 2rem;
    text-align: center;
  }

  .form-title {
    font-size: 1.5rem;
    font-weight: 600;
    color: #1f2937;
    margin: 0 0 0.5rem 0;
  }

  .form-subtitle {
    font-size: 0.875rem;
    color: #6b7280;
    font-style: italic;
  }

  .form-content {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .form-actions {
    display: flex;
    gap: 0.75rem;
    margin-top: 1.5rem;
    padding-top: 1.5rem;
    border-top: 1px solid #e5e7eb;
  }

  .submit-btn {
    background: #3b82f6;
    color: white;
    border: none;
    padding: 0.75rem 1.5rem;
    border-radius: 0.375rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.2s;
  }

  .submit-btn:hover {
    background: #2563eb;
  }

  .reset-btn {
    background: #f3f4f6;
    color: #374151;
    border: 1px solid #d1d5db;
    padding: 0.75rem 1.5rem;
    border-radius: 0.375rem;
    font-weight: 500;
    cursor: pointer;
    transition: background-color 0.2s;
  }

  .reset-btn:hover {
    background: #e5e7eb;
  }

  .form-debug {
    margin-top: 2rem;
    padding: 1rem;
    background: #f9fafb;
    border-radius: 0.375rem;
    border: 1px solid #e5e7eb;
  }

  .form-debug summary {
    cursor: pointer;
    font-weight: 500;
    color: #374151;
  }

  .form-debug pre {
    margin-top: 0.5rem;
    font-size: 0.75rem;
    color: #6b7280;
    white-space: pre-wrap;
    word-break: break-word;
  }
</style>