// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';

// Custom collection method: getContributionTypesAction
export const GET: RequestHandler = async () => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:ContentContribution') as any;
  if (!collection) throw error(500, '@happyvertical/smrt-content:ContentContribution collection is not registered');

  const result = await collection.getContributionTypesAction()

  return json({ action: 'getContributionTypesAction', result });
};
