import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

// @ts-expect-error — index.js has no type declarations
import { copyTemplate, getTemplatePath } from '../index.js';

describe('copyTemplate', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'smrt-template-test-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('copies the canonical template files to the destination', () => {
    copyTemplate(tempDir, { name: 'my-app', overwrite: true });

    expect(existsSync(join(tempDir, 'package.json'))).toBe(true);
    expect(existsSync(join(tempDir, 'src', 'hooks.server.ts'))).toBe(true);
    expect(existsSync(join(tempDir, 'src', 'lib', 'server', 'tenancy.ts'))).toBe(
      true,
    );
    expect(existsSync(join(tempDir, 'src', 'app.d.ts'))).toBe(true);
  });

  it('does NOT copy the `.svelte-kit/` directory if it exists in the template', () => {
    // `.svelte-kit/` is regenerated by `svelte-kit sync` per project. If a
    // stale copy is laying around in our template directory (e.g. from
    // test fixtures), `copyTemplate()` must filter it out so consumers
    // don't get an out-of-date stub.
    const sveltekitDir = join(getTemplatePath(), '.svelte-kit');
    const createdHere = !existsSync(sveltekitDir);
    if (createdHere) {
      mkdirSync(sveltekitDir, { recursive: true });
      writeFileSync(join(sveltekitDir, 'tsconfig.json'), '{}');
    }
    try {
      copyTemplate(tempDir, { name: 'my-app', overwrite: true });
      expect(existsSync(join(tempDir, '.svelte-kit'))).toBe(false);
    } finally {
      if (createdHere) {
        rmSync(sveltekitDir, { recursive: true, force: true });
      }
    }
  });

  it('substitutes the project name into package.json', () => {
    copyTemplate(tempDir, { name: 'my-app', overwrite: true });

    const pkg = JSON.parse(
      readFileSync(join(tempDir, 'package.json'), 'utf-8'),
    );
    expect(pkg.name).toBe('my-app');
  });
});
