import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

// @ts-expect-error — index.js has no type declarations
import { copyTemplate, getTemplatePath } from '../index.js';

describe('copyTemplate', () => {
  let tempDir: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'smrt-template-test-'));
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('copies the canonical template files to the destination', () => {
    copyTemplate(tempDir, { name: 'my-app', overwrite: true });

    expect(existsSync(join(tempDir, 'package.json'))).toBe(true);
    expect(existsSync(join(tempDir, 'src', 'hooks.server.ts'))).toBe(true);
    expect(existsSync(join(tempDir, 'src', 'lib', 'server', 'tenancy.ts'))).toBe(
      true,
    );
    expect(existsSync(join(tempDir, 'src', 'app.d.ts'))).toBe(true);
    expect(
      existsSync(join(tempDir, 'src', 'routes', '+page.server.ts')),
    ).toBe(true);
    expect(existsSync(join(tempDir, 'src', 'routes', '+page.svelte'))).toBe(
      true,
    );
    expect(existsSync(join(tempDir, 'AGENTS.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'INSTALL_PROMPT.md'))).toBe(true);
    expect(existsSync(join(tempDir, 'scripts', 'smrt-app.mjs'))).toBe(true);
    expect(
      existsSync(join(tempDir, 'scripts', 'smrt-operation-lock.mjs')),
    ).toBe(true);
    expect(
      existsSync(join(tempDir, 'scripts', 'smrt-prepare-migration.mjs')),
    ).toBe(true);
    expect(
      existsSync(join(tempDir, 'scripts', 'smrt-runtime-identity.mjs')),
    ).toBe(true);
    expect(existsSync(join(tempDir, 'scripts', 'smrt-worker.mjs'))).toBe(true);
    expect(existsSync(join(tempDir, 'Dockerfile'))).toBe(true);
    expect(existsSync(join(tempDir, '.dockerignore'))).toBe(true);
    expect(existsSync(join(tempDir, 'compose.yaml'))).toBe(true);
    expect(readFileSync(join(tempDir, 'CLAUDE.md'), 'utf-8').trim()).toBe(
      '@AGENTS.md',
    );
  });

  it('ships one canonical profile and the complete operational surface', () => {
    copyTemplate(tempDir, { name: 'my-app', overwrite: true });

    const config = readFileSync(join(tempDir, 'smrt.config.ts'), 'utf8');
    const pkg = JSON.parse(readFileSync(join(tempDir, 'package.json'), 'utf8'));
    expect(config).toContain('runtime:');
    expect(config).toContain("process.env.SMRT_RUNTIME_PROFILE || 'local'");
    for (const operation of [
      'install',
      'setup',
      'recover',
      'start',
      'doctor',
      'open',
      'stop',
      'backup',
      'export',
      'import',
    ]) {
      expect(pkg.scripts).toHaveProperty(`app:${operation}`);
    }
  });

  it('does NOT copy the `.svelte-kit/` directory if it exists in the template', () => {
    // `.svelte-kit/` is regenerated by `svelte-kit sync` per project. If a
    // stale copy is laying around in our template directory (e.g. from
    // test fixtures), `copyTemplate()` must filter it out so consumers
    // don't get an out-of-date stub.
    const sveltekitDir = join(getTemplatePath(), '.svelte-kit');
    const createdHere = !existsSync(sveltekitDir);
    if (createdHere) {
      mkdirSync(sveltekitDir, { recursive: true });
      writeFileSync(join(sveltekitDir, 'tsconfig.json'), '{}');
    }
    try {
      copyTemplate(tempDir, { name: 'my-app', overwrite: true });
      expect(existsSync(join(tempDir, '.svelte-kit'))).toBe(false);
    } finally {
      if (createdHere) {
        rmSync(sveltekitDir, { recursive: true, force: true });
      }
    }
  });

  it('does not copy internal test fixtures if they appear under the template', () => {
    const fixturesDir = join(getTemplatePath(), '__tests__');
    const createdHere = !existsSync(fixturesDir);
    if (createdHere) {
      mkdirSync(fixturesDir, { recursive: true });
      writeFileSync(join(fixturesDir, 'fixture.test.ts'), 'throw new Error()');
    }
    try {
      copyTemplate(tempDir, { name: 'my-app', overwrite: true });
      expect(existsSync(join(tempDir, '__tests__'))).toBe(false);
    } finally {
      if (createdHere) {
        rmSync(fixturesDir, { recursive: true, force: true });
      }
    }
  });

  it('substitutes the project name into package.json', () => {
    copyTemplate(tempDir, { name: 'my-app', overwrite: true });

    const pkg = JSON.parse(
      readFileSync(join(tempDir, 'package.json'), 'utf-8'),
    );
    expect(pkg.name).toBe('@smrt-app/my-app');
    expect(pkg.packageManager).toBe('pnpm@10.34.4');
    expect(pkg.engines).toEqual({ node: '>=24.18.0', pnpm: '10.34.4' });
  });

  it('preserves an explicitly scoped package identity', () => {
    copyTemplate(tempDir, { name: '@example/my-app', overwrite: true });

    const pkg = JSON.parse(
      readFileSync(join(tempDir, 'package.json'), 'utf-8'),
    );
    expect(pkg.name).toBe('@example/my-app');
  });
});
