// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom collection method: getByKey
export const POST: RequestHandler = async ({ request }) => {
  const collection = (await getCollection<any>(
    '@happyvertical/smrt-content:ContentGovernanceProfile',
  )) as any;
  if (!collection)
    throw error(
      500,
      '@happyvertical/smrt-content:ContentGovernanceProfile collection is not registered',
    );

  const options = await request.json();
  const result = await collection.getByKey(options);

  return json({ action: 'getByKey', result });
};
