/**
 * Auto-generated static manifest
 * Generated at build time from SMRT object scanning
 * DO NOT EDIT - This file is automatically generated
 */

import type { SmartObjectManifest } from '../scanner/types';

export const staticManifest: SmartObjectManifest = {
  "version": "1.0.0",
  "timestamp": 1760658455446,
  "objects": {
    "pleb": {
      "name": "pleb",
      "className": "Pleb",
      "collection": "plebs",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/pleb.ts",
      "fields": {},
      "methods": {
        "create": {
          "name": "create",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "PlebOptions",
              "optional": false
            }
          ],
          "returnType": "void",
          "isStatic": true,
          "isPublic": true
        },
        "initialize": {
          "name": "initialize",
          "async": true,
          "parameters": [],
          "returnType": "Promise<this>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {}
    }
  }
} as const;

export default staticManifest;
