/**
 * Test manifest stub
 * This file is replaced by generate-test-manifest.js during pretest
 * If tests run without pretest, this empty manifest is used
 *
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import type { SmartObjectManifest } from '../scanner/types';

export const testManifest: SmartObjectManifest = {
  version: '1.0.0',
  timestamp: 1761781747871,
  objects: {
    testobject: {
      name: 'testobject',
      className: 'TestObject',
      collection: 'testobjects',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/object.spec.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        description: {
          type: 'text',
          required: false,
          default: '',
        },
        active: {
          type: 'boolean',
          required: true,
          default: false,
        },
        count: {
          type: 'decimal',
          required: true,
          default: 0,
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    perftestuser: {
      name: 'perftestuser',
      className: 'PerfTestUser',
      collection: 'perftestusers',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/performance.spec.ts',
      fields: {
        username: {
          type: 'text',
          required: true,
          default: '',
        },
        email: {
          type: 'text',
          required: true,
          default: '',
        },
        age: {
          type: 'decimal',
          required: true,
          default: 0,
        },
        active: {
          type: 'boolean',
          required: true,
          default: false,
        },
        createdAt: {
          type: 'datetime',
          required: true,
        },
        lastLogin: {
          type: 'datetime',
          required: true,
        },
        profileData: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {
        create: {
          name: 'create',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
            },
          ],
          returnType: 'Promise<PerfTestUser>',
          isStatic: true,
          isPublic: true,
        },
      },
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    perftestusers: {
      name: 'perftestusers',
      className: 'PerfTestUsers',
      collection: 'perftestuserses',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/performance.spec.ts',
      fields: {},
      methods: {
        create: {
          name: 'create',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
            },
          ],
          returnType: 'Promise<PerfTestUsers>',
          isStatic: true,
          isPublic: true,
        },
      },
      decoratorConfig: {},
    },
    testcategory: {
      name: 'testcategory',
      className: 'TestCategory',
      collection: 'testcategories',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        description: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testcustomer: {
      name: 'testcustomer',
      className: 'TestCustomer',
      collection: 'testcustomers',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        email: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testproduct: {
      name: 'testproduct',
      className: 'TestProduct',
      collection: 'testproducts',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-integration.spec.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
        },
        price: {
          type: 'decimal',
          required: true,
        },
        stock: {
          type: 'integer',
          required: true,
        },
      },
      methods: {
        analyze: {
          name: 'analyze',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'void',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        api: {
          include: ['list', 'get', 'create', 'update'],
        },
        mcp: {
          include: ['list', 'get', 'analyze'],
        },
        cli: true,
      },
    },
    testorder: {
      name: 'testorder',
      className: 'TestOrder',
      collection: 'testorders',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts',
      fields: {
        customerId: {
          type: 'text',
          required: true,
          default: '',
        },
        productId: {
          type: 'text',
          required: true,
          default: '',
        },
        total: {
          type: 'decimal',
          required: true,
          default: 0,
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testclass: {
      name: 'testclass',
      className: 'TestClass',
      collection: 'testclasses',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/utils.spec.ts',
      fields: {
        test_string: {
          type: 'text',
          required: true,
        },
        test_number: {
          type: 'integer',
          required: true,
        },
        test_date: {
          type: 'datetime',
          required: true,
        },
      },
      methods: {
        methodField: {
          name: 'methodField',
          async: false,
          parameters: [],
          returnType: 'void',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testevent: {
      name: 'testevent',
      className: 'TestEvent',
      collection: 'testevents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts',
      fields: {
        title: {
          type: 'text',
          required: true,
          default: '',
        },
        description: {
          type: 'text',
          required: true,
          default: '',
        },
        startDate: {
          type: 'datetime',
          required: true,
        },
        endDate: {
          type: 'datetime',
          required: true,
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testprofile: {
      name: 'testprofile',
      className: 'TestProfile',
      collection: 'testprofiles',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts',
      fields: {
        firstName: {
          type: 'text',
          required: true,
          default: '',
        },
        lastName: {
          type: 'text',
          required: true,
          default: '',
        },
        email: {
          type: 'text',
          required: true,
          default: '',
        },
        bio: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testeventcollection: {
      name: 'testeventcollection',
      className: 'TestEventCollection',
      collection: 'testeventcollections',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts',
      fields: {},
      methods: {},
      decoratorConfig: {},
    },
    testprofilecollection: {
      name: 'testprofilecollection',
      className: 'TestProfileCollection',
      collection: 'testprofilecollections',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts',
      fields: {},
      methods: {},
      decoratorConfig: {},
    },
    place: {
      name: 'place',
      className: 'Place',
      collection: 'places',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-65-nullable-fields.test.ts',
      fields: {
        latitude: {
          type: 'decimal',
          required: true,
          default: null,
        },
        longitude: {
          type: 'decimal',
          required: true,
          default: null,
        },
        name: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        api: true,
        mcp: true,
        cli: true,
      },
    },
    issue75product: {
      name: 'issue75product',
      className: 'Issue75Product',
      collection: 'issue75products',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        productName: {
          type: 'text',
          required: true,
          default: 'Test Product',
        },
        price: {
          type: 'decimal',
          required: true,
          default: 99.99,
        },
        inStock: {
          type: 'boolean',
          required: true,
          default: true,
        },
      },
      methods: {},
      decoratorConfig: {},
    },
    issue75article: {
      name: 'issue75article',
      className: 'Issue75Article',
      collection: 'issue75articles',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        title: {
          type: 'text',
          required: true,
          default: 'Test Article',
        },
        body: {
          type: 'text',
          required: true,
          default: 'Article content',
        },
        published: {
          type: 'boolean',
          required: true,
          default: false,
        },
      },
      methods: {},
      decoratorConfig: {},
    },
    issue75book: {
      name: 'issue75book',
      className: 'Issue75Book',
      collection: 'issue75books',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        bookTitle: {
          type: 'text',
          required: true,
          default: 'The Book',
        },
        author: {
          type: 'text',
          required: true,
          default: 'Author Name',
        },
        pages: {
          type: 'decimal',
          required: true,
          default: 300,
        },
      },
      methods: {},
      decoratorConfig: {},
    },
    schemagentestevent: {
      name: 'schemagentestevent',
      className: 'SchemaGenTestEvent',
      collection: 'schemagentestevents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/schema-generation.test.ts',
      fields: {
        title: {
          type: 'text',
          required: true,
        },
        description: {
          type: 'text',
          required: true,
        },
        startDate: {
          type: 'text',
          required: true,
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    schemagenarticle: {
      name: 'schemagenarticle',
      className: 'SchemaGenArticle',
      collection: 'schemagenarticles',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/schema-generation.test.ts',
      fields: {
        title: {
          type: 'text',
          required: true,
        },
        body: {
          type: 'text',
          required: true,
        },
      },
      methods: {},
      decoratorConfig: {
        api: {},
        mcp: {},
        cli: false,
      },
    },
    testproductcollection: {
      name: 'testproductcollection',
      className: 'TestProductCollection',
      collection: 'testproductcollections',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-integration.spec.ts',
      fields: {},
      methods: {},
      decoratorConfig: {},
    },
    protocoltestobject: {
      name: 'protocoltestobject',
      className: 'ProtocolTestObject',
      collection: 'protocoltestobjects',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-protocol.spec.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
        },
        count: {
          type: 'integer',
          required: true,
        },
      },
      methods: {
        testAction: {
          name: 'testAction',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'void',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        mcp: {
          include: ['list', 'get', 'testAction'],
        },
      },
    },
    protocoltestobjectcollection: {
      name: 'protocoltestobjectcollection',
      className: 'ProtocolTestObjectCollection',
      collection: 'protocoltestobjectcollections',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-protocol.spec.ts',
      fields: {},
      methods: {},
      decoratorConfig: {},
    },
    testagent: {
      name: 'testagent',
      className: 'TestAgent',
      collection: 'testagents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
        source: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {
        research: {
          name: 'research',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
        report: {
          name: 'report',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
        analyze: {
          name: 'analyze',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        mcp: {
          include: ['list', 'get', 'research', 'report', 'analyze'],
        },
      },
    },
    invalidactionagent: {
      name: 'invalidactionagent',
      className: 'InvalidActionAgent',
      collection: 'invalidactionagents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        mcp: {
          include: ['list', 'get', 'nonexistent'],
        },
      },
    },
    excludedactionagent: {
      name: 'excludedactionagent',
      className: 'ExcludedActionAgent',
      collection: 'excludedactionagents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts',
      fields: {
        name: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {
        research: {
          name: 'research',
          async: true,
          parameters: [],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
        report: {
          name: 'report',
          async: true,
          parameters: [],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        mcp: {
          include: ['list', 'get', 'research', 'report'],
          exclude: ['report'],
        },
      },
    },
    document: {
      name: 'document',
      className: 'Document',
      collection: 'documents',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts',
      fields: {
        title: {
          type: 'text',
          required: true,
          default: '',
        },
        content: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {
        analyze: {
          name: 'analyze',
          async: true,
          parameters: [
            {
              name: 'options',
              type: 'any',
              optional: false,
              default: {},
            },
          ],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        cli: true,
      },
    },
    secret: {
      name: 'secret',
      className: 'Secret',
      collection: 'secrets',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts',
      fields: {
        value: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {},
      decoratorConfig: {
        cli: false,
      },
    },
    article: {
      name: 'article',
      className: 'Article',
      collection: 'articles',
      filePath:
        '/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts',
      fields: {
        title: {
          type: 'text',
          required: true,
          default: '',
        },
        author: {
          type: 'text',
          required: true,
          default: '',
        },
      },
      methods: {
        analyze: {
          name: 'analyze',
          async: true,
          parameters: [],
          returnType: 'Promise<any>',
          isStatic: false,
          isPublic: true,
        },
      },
      decoratorConfig: {
        cli: {
          include: ['list', 'get', 'analyze'],
          exclude: ['delete'],
        },
      },
    },
  },
} as const;

export default testManifest;
