/**
 * Test manifest stub
 * This file is replaced by generate-test-manifest.js during pretest
 * If tests run without pretest, this empty manifest is used
 *
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import type { SmartObjectManifest } from '../scanner/types';

export const testManifest: SmartObjectManifest = {
  "version": "1.0.0",
  "timestamp": 1762774091950,
  "objects": {
    "testobject": {
      "name": "testobject",
      "className": "TestObject",
      "collection": "testobjects",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/object.spec.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "description": {
          "type": "text",
          "required": false
        },
        "active": {
          "type": "boolean",
          "required": true
        },
        "count": {
          "type": "integer",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestObject",
      "collectionExportName": "TestObjectCollection"
    },
    "testcouncil": {
      "name": "testcouncil",
      "className": "TestCouncil",
      "collection": "testcouncils",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/object.spec.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "description": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "custom_councils"
      },
      "extends": "SmrtObject",
      "exportName": "TestCouncil",
      "collectionExportName": "TestCouncilCollection"
    },
    "perftestuser": {
      "name": "perftestuser",
      "className": "PerfTestUser",
      "collection": "perftestusers",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/performance.spec.ts",
      "fields": {
        "username": {
          "type": "text",
          "required": true
        },
        "email": {
          "type": "text",
          "required": true
        },
        "age": {
          "type": "integer",
          "required": true
        },
        "active": {
          "type": "boolean",
          "required": true
        },
        "createdAt": {
          "type": "datetime",
          "required": true
        },
        "lastLogin": {
          "type": "datetime",
          "required": true
        },
        "profileData": {
          "type": "text",
          "required": true
        }
      },
      "methods": {
        "create": {
          "name": "create",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<PerfTestUser>",
          "isStatic": true,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "PerfTestUser",
      "collectionExportName": "PerfTestUserCollection"
    },
    "perftestusers": {
      "name": "perftestusers",
      "className": "PerfTestUsers",
      "collection": "perftestuserses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/performance.spec.ts",
      "fields": {},
      "methods": {
        "create": {
          "name": "create",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<PerfTestUsers>",
          "isStatic": true,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "PerfTestUsers",
      "collectionExportName": "PerfTestUsersCollection"
    },
    "testcategory": {
      "name": "testcategory",
      "className": "TestCategory",
      "collection": "testcategories",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "description": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestCategory",
      "collectionExportName": "TestCategoryCollection"
    },
    "testcustomer": {
      "name": "testcustomer",
      "className": "TestCustomer",
      "collection": "testcustomers",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "email": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestCustomer",
      "collectionExportName": "TestCustomerCollection"
    },
    "testproduct": {
      "name": "testproduct",
      "className": "TestProduct",
      "collection": "testproducts",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-integration.spec.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "price": {
          "type": "decimal",
          "required": true,
          "options": {
            "min": 0
          }
        },
        "stock": {
          "type": "integer",
          "required": true,
          "options": {
            "default": 0
          }
        }
      },
      "methods": {
        "analyze": {
          "name": "analyze",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "void",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get",
            "analyze"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "exportName": "TestProduct",
      "collectionExportName": "TestProductCollection"
    },
    "testorder": {
      "name": "testorder",
      "className": "TestOrder",
      "collection": "testorders",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts",
      "fields": {
        "customerId": {
          "type": "text",
          "required": true
        },
        "productId": {
          "type": "text",
          "required": true
        },
        "total": {
          "type": "integer",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestOrder",
      "collectionExportName": "TestOrderCollection"
    },
    "overwritetestobject": {
      "name": "overwritetestobject",
      "className": "OverwriteTestObject",
      "collection": "overwritetestobjects",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/registry.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true,
            "maxLength": 100
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "OverwriteTestObject",
      "collectionExportName": "OverwriteTestObjectCollection"
    },
    "testclass": {
      "name": "testclass",
      "className": "TestClass",
      "collection": "testclasses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/utils.spec.ts",
      "fields": {
        "test_string": {
          "type": "text",
          "required": true
        },
        "test_number": {
          "type": "integer",
          "required": true
        },
        "test_date": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {
        "methodField": {
          "name": "methodField",
          "async": false,
          "parameters": [],
          "returnType": "void",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestClass",
      "collectionExportName": "TestClassCollection"
    },
    "testprofile": {
      "name": "testprofile",
      "className": "TestProfile",
      "collection": "testprofiles",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts",
      "fields": {
        "firstName": {
          "type": "text",
          "required": true
        },
        "lastName": {
          "type": "text",
          "required": true
        },
        "email": {
          "type": "text",
          "required": true
        },
        "bio": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestProfile",
      "collectionExportName": "TestProfileCollection"
    },
    "testmetadata": {
      "name": "testmetadata",
      "className": "TestMetadata",
      "collection": "testmetadatas",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/circular-dependency.test.ts",
      "fields": {
        "profileId": {
          "type": "foreignKey",
          "required": true
        },
        "key": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "value": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "TestMetadata",
      "collectionExportName": "TestMetadataCollection"
    },
    "basecontent": {
      "name": "basecontent",
      "className": "BaseContent",
      "collection": "basecontents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance-simple.test.ts",
      "fields": {
        "baseField": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "baseNumber": {
          "type": "integer",
          "required": true,
          "default": 0
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "BaseContent",
      "collectionExportName": "BaseContentCollection"
    },
    "extendedcontent": {
      "name": "extendedcontent",
      "className": "ExtendedContent",
      "collection": "extendedcontents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance-simple.test.ts",
      "fields": {
        "extendedField": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "extendedNumber": {
          "type": "decimal",
          "required": true,
          "default": 0
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "BaseContent",
      "exportName": "ExtendedContent",
      "collectionExportName": "ExtendedContentCollection"
    },
    "content": {
      "name": "content",
      "className": "Content",
      "collection": "contents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "body": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "publishedAt": {
          "type": "datetime",
          "required": true,
          "default": null
        },
        "wordCount": {
          "type": "integer",
          "required": true,
          "default": 0
        }
      },
      "methods": {
        "generateSummary": {
          "name": "generateSummary",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "Content",
      "collectionExportName": "ContentCollection"
    },
    "praecocontent": {
      "name": "praecocontent",
      "className": "PraecoContent",
      "collection": "praecocontents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "praecoCustom1": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "sourceUrl": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "rating": {
          "type": "decimal",
          "required": true,
          "default": 0
        }
      },
      "methods": {
        "analyzeSentiment": {
          "name": "analyzeSentiment",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "Content",
      "exportName": "PraecoContent",
      "collectionExportName": "PraecoContentCollection"
    },
    "bentleycontent": {
      "name": "bentleycontent",
      "className": "BentleyContent",
      "collection": "bentleycontents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "bentleyCustom1": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "localTags": {
          "type": "json",
          "required": true,
          "default": []
        }
      },
      "methods": {
        "analyzeLocal": {
          "name": "analyzeLocal",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "PraecoContent",
      "exportName": "BentleyContent",
      "collectionExportName": "BentleyContentCollection"
    },
    "parentwithconstraints": {
      "name": "parentwithconstraints",
      "className": "ParentWithConstraints",
      "collection": "parentwithconstraintses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "age": {
          "type": "integer",
          "required": true,
          "options": {
            "min": 0,
            "max": 150
          }
        },
        "score": {
          "type": "decimal",
          "required": true,
          "options": {
            "min": 0,
            "max": 100
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "ParentWithConstraints",
      "collectionExportName": "ParentWithConstraintsCollection"
    },
    "childwithconstraints": {
      "name": "childwithconstraints",
      "className": "ChildWithConstraints",
      "collection": "childwithconstraintses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "age": {
          "type": "integer",
          "required": true,
          "options": {
            "min": 18,
            "max": 65
          }
        },
        "score": {
          "type": "decimal",
          "required": true,
          "options": {
            "min": 50,
            "max": 90
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "ParentWithConstraints",
      "exportName": "ChildWithConstraints",
      "collectionExportName": "ChildWithConstraintsCollection"
    },
    "parenttypemismatch": {
      "name": "parenttypemismatch",
      "className": "ParentTypeMismatch",
      "collection": "parenttypemismatches",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "myField": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "ParentTypeMismatch",
      "collectionExportName": "ParentTypeMismatchCollection"
    },
    "childtypemismatch": {
      "name": "childtypemismatch",
      "className": "ChildTypeMismatch",
      "collection": "childtypemismatches",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "myField": {
          "type": "integer",
          "required": true,
          "default": 0
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "ParentTypeMismatch",
      "exportName": "ChildTypeMismatch",
      "collectionExportName": "ChildTypeMismatchCollection"
    },
    "parentwithmethod": {
      "name": "parentwithmethod",
      "className": "ParentWithMethod",
      "collection": "parentwithmethods",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {},
      "methods": {
        "doSomething": {
          "name": "doSomething",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "ParentWithMethod",
      "collectionExportName": "ParentWithMethodCollection"
    },
    "childwithmethod": {
      "name": "childwithmethod",
      "className": "ChildWithMethod",
      "collection": "childwithmethods",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {},
      "methods": {
        "doSomething": {
          "name": "doSomething",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "ParentWithMethod",
      "exportName": "ChildWithMethod",
      "collectionExportName": "ChildWithMethodCollection"
    },
    "orphanclass": {
      "name": "orphanclass",
      "className": "OrphanClass",
      "collection": "orphanclasses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/inheritance.test.ts",
      "fields": {
        "orphanField": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "OrphanClass",
      "collectionExportName": "OrphanClassCollection"
    },
    "product": {
      "name": "product",
      "className": "Product",
      "collection": "products",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-115-sql-injection-prevention.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "price": {
          "type": "decimal",
          "required": true
        },
        "category": {
          "type": "text",
          "required": true
        },
        "active": {
          "type": "boolean",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "Product",
      "collectionExportName": "ProductCollection"
    },
    "productcollection": {
      "name": "productcollection",
      "className": "ProductCollection",
      "collection": "productcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-115-sql-injection-prevention.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "ProductCollection",
      "collectionExportName": "ProductCollectionCollection"
    },
    "cachetestobject": {
      "name": "cachetestobject",
      "className": "CacheTestObject",
      "collection": "cachetestobjects",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-117-memory-leak-prevention.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "value": {
          "type": "integer",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": true,
        "mcp": true,
        "cli": true
      },
      "extends": "SmrtObject",
      "exportName": "CacheTestObject",
      "collectionExportName": "CacheTestObjectCollection"
    },
    "cachetestcollection": {
      "name": "cachetestcollection",
      "className": "CacheTestCollection",
      "collection": "cachetestcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-117-memory-leak-prevention.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CacheTestCollection",
      "collectionExportName": "CacheTestCollectionCollection"
    },
    "testevent": {
      "name": "testevent",
      "className": "TestEvent",
      "collection": "testevents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true
        },
        "description": {
          "type": "text",
          "required": true
        },
        "startDate": {
          "type": "datetime",
          "required": true
        },
        "endDate": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestEvent",
      "collectionExportName": "TestEventCollection"
    },
    "testeventcollection": {
      "name": "testeventcollection",
      "className": "TestEventCollection",
      "collection": "testeventcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "TestEventCollection",
      "collectionExportName": "TestEventCollectionCollection"
    },
    "testprofilecollection": {
      "name": "testprofilecollection",
      "className": "TestProfileCollection",
      "collection": "testprofilecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-144-integration.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "TestProfileCollection",
      "collectionExportName": "TestProfileCollectionCollection"
    },
    "testcontent": {
      "name": "testcontent",
      "className": "TestContent",
      "collection": "testcontents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-198-duckdb-datetime-compatibility.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "publishDate": {
          "type": "datetime",
          "required": true
        },
        "lastSyncedAt": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestContent",
      "collectionExportName": "TestContentCollection"
    },
    "eventwithdates": {
      "name": "eventwithdates",
      "className": "EventWithDates",
      "collection": "eventwithdateses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-198-integration-date-serialization.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "eventDate": {
          "type": "datetime",
          "required": true
        },
        "registrationDeadline": {
          "type": "datetime",
          "required": true
        },
        "lastModified": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "EventWithDates",
      "collectionExportName": "EventWithDatesCollection"
    },
    "eventcollection": {
      "name": "eventcollection",
      "className": "EventCollection",
      "collection": "eventcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-198-integration-date-serialization.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "EventCollection",
      "collectionExportName": "EventCollectionCollection"
    },
    "contentmock": {
      "name": "contentmock",
      "className": "ContentMock",
      "collection": "contentmocks",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-201-content-references-excluded.test.ts",
      "fields": {
        "type": {
          "type": "text",
          "required": true,
          "default": null
        },
        "title": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "body": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "ContentMock",
      "collectionExportName": "ContentMockCollection"
    },
    "testwithprotected": {
      "name": "testwithprotected",
      "className": "TestWithProtected",
      "collection": "testwithprotecteds",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-201-protected-properties-in-schema.test.ts",
      "fields": {
        "publicName": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "publicDescription": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "TestWithProtected",
      "collectionExportName": "TestWithProtectedCollection"
    },
    "councilwithtsoptional": {
      "name": "councilwithtsoptional",
      "className": "CouncilWithTSOptional",
      "collection": "councilwithtsoptionals",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "url": {
          "type": "text",
          "required": false
        },
        "location": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "councils_ts_optional"
      },
      "extends": "SmrtObject",
      "exportName": "CouncilWithTSOptional",
      "collectionExportName": "CouncilWithTSOptionalCollection"
    },
    "counciltsoptionalcollection": {
      "name": "counciltsoptionalcollection",
      "className": "CouncilTSOptionalCollection",
      "collection": "counciltsoptionalcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CouncilTSOptionalCollection",
      "collectionExportName": "CouncilTSOptionalCollectionCollection"
    },
    "councilwithnullable": {
      "name": "councilwithnullable",
      "className": "CouncilWithNullable",
      "collection": "councilwithnullables",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "url": {
          "type": "text",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "location": {
          "type": "text",
          "required": true,
          "options": {
            "nullable": true
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "councils_nullable"
      },
      "extends": "SmrtObject",
      "exportName": "CouncilWithNullable",
      "collectionExportName": "CouncilWithNullableCollection"
    },
    "councilnullablecollection": {
      "name": "councilnullablecollection",
      "className": "CouncilNullableCollection",
      "collection": "councilnullablecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CouncilNullableCollection",
      "collectionExportName": "CouncilNullableCollectionCollection"
    },
    "councilwithworkaround": {
      "name": "councilwithworkaround",
      "className": "CouncilWithWorkaround",
      "collection": "councilwithworkarounds",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "url": {
          "type": "text",
          "required": false
        },
        "location": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "councils_workaround"
      },
      "extends": "SmrtObject",
      "exportName": "CouncilWithWorkaround",
      "collectionExportName": "CouncilWithWorkaroundCollection"
    },
    "councilworkaroundcollection": {
      "name": "councilworkaroundcollection",
      "className": "CouncilWorkaroundCollection",
      "collection": "councilworkaroundcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CouncilWorkaroundCollection",
      "collectionExportName": "CouncilWorkaroundCollectionCollection"
    },
    "councilforupdate": {
      "name": "councilforupdate",
      "className": "CouncilForUpdate",
      "collection": "councilforupdates",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "url": {
          "type": "text",
          "required": false
        },
        "location": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "councils_update"
      },
      "extends": "SmrtObject",
      "exportName": "CouncilForUpdate",
      "collectionExportName": "CouncilForUpdateCollection"
    },
    "councilupdatecollection": {
      "name": "councilupdatecollection",
      "className": "CouncilUpdateCollection",
      "collection": "councilupdatecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-205-optional-field-undefined.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CouncilUpdateCollection",
      "collectionExportName": "CouncilUpdateCollectionCollection"
    },
    "councilissue208": {
      "name": "councilissue208",
      "className": "CouncilIssue208",
      "collection": "councilissue208s",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-208-optional-field-helper-undefined.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "description": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "tableName": "councils_issue_208"
      },
      "extends": "SmrtObject",
      "exportName": "CouncilIssue208",
      "collectionExportName": "CouncilIssue208Collection"
    },
    "councilissue208collection": {
      "name": "councilissue208collection",
      "className": "CouncilIssue208Collection",
      "collection": "councilissue208collections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-208-optional-field-helper-undefined.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "CouncilIssue208Collection",
      "collectionExportName": "CouncilIssue208CollectionCollection"
    },
    "issue35testobject1": {
      "name": "issue35testobject1",
      "className": "Issue35TestObject1",
      "collection": "issue35testobject1s",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value1": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObject1",
      "collectionExportName": "Issue35TestObject1Collection"
    },
    "issue35testobject2": {
      "name": "issue35testobject2",
      "className": "Issue35TestObject2",
      "collection": "issue35testobject2s",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value2": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObject2",
      "collectionExportName": "Issue35TestObject2Collection"
    },
    "issue35testobjectdiffdb": {
      "name": "issue35testobjectdiffdb",
      "className": "Issue35TestObjectDiffDb",
      "collection": "issue35testobjectdiffdbs",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObjectDiffDb",
      "collectionExportName": "Issue35TestObjectDiffDbCollection"
    },
    "issue35testdocument": {
      "name": "issue35testdocument",
      "className": "Issue35TestDocument",
      "collection": "issue35testdocuments",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "content": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestDocument",
      "collectionExportName": "Issue35TestDocumentCollection"
    },
    "issue35testobjectstringconfig": {
      "name": "issue35testobjectstringconfig",
      "className": "Issue35TestObjectStringConfig",
      "collection": "issue35testobjectstringconfigs",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObjectStringConfig",
      "collectionExportName": "Issue35TestObjectStringConfigCollection"
    },
    "issue35testobjectconfigobj": {
      "name": "issue35testobjectconfigobj",
      "className": "Issue35TestObjectConfigObj",
      "collection": "issue35testobjectconfigobjs",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObjectConfigObj",
      "collectionExportName": "Issue35TestObjectConfigObjCollection"
    },
    "issue35testobjectconcurrent": {
      "name": "issue35testobjectconcurrent",
      "className": "Issue35TestObjectConcurrent",
      "collection": "issue35testobjectconcurrents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObjectConcurrent",
      "collectionExportName": "Issue35TestObjectConcurrentCollection"
    },
    "issue35testobjectweakset": {
      "name": "issue35testobjectweakset",
      "className": "Issue35TestObjectWeakSet",
      "collection": "issue35testobjectweaksets",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-35-system-tables-initialization.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue35TestObjectWeakSet",
      "collectionExportName": "Issue35TestObjectWeakSetCollection"
    },
    "place": {
      "name": "place",
      "className": "Place",
      "collection": "places",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-65-nullable-fields.test.ts",
      "fields": {
        "latitude": {
          "type": "decimal",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "longitude": {
          "type": "decimal",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "name": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": true,
        "mcp": true,
        "cli": true
      },
      "extends": "SmrtObject",
      "exportName": "Place",
      "collectionExportName": "PlaceCollection"
    },
    "issue75product": {
      "name": "issue75product",
      "className": "Issue75Product",
      "collection": "issue75products",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "default": ""
          }
        },
        "productName": {
          "type": "text",
          "required": true,
          "options": {
            "default": "Test Product"
          }
        },
        "price": {
          "type": "decimal",
          "required": true,
          "options": {
            "default": 99.99
          }
        },
        "inStock": {
          "type": "boolean",
          "required": true,
          "options": {
            "default": true
          }
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue75Product",
      "collectionExportName": "Issue75ProductCollection"
    },
    "issue75article": {
      "name": "issue75article",
      "className": "Issue75Article",
      "collection": "issue75articles",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "default": ""
          }
        },
        "title": {
          "type": "text",
          "required": true,
          "options": {
            "default": "Test Article"
          }
        },
        "body": {
          "type": "text",
          "required": true,
          "options": {
            "default": "Article content"
          }
        },
        "published": {
          "type": "boolean",
          "required": true,
          "options": {
            "default": false
          }
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue75Article",
      "collectionExportName": "Issue75ArticleCollection"
    },
    "issue75book": {
      "name": "issue75book",
      "className": "Issue75Book",
      "collection": "issue75books",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-75-circular-serialization.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "default": ""
          }
        },
        "bookTitle": {
          "type": "text",
          "required": true,
          "options": {
            "default": "The Book"
          }
        },
        "author": {
          "type": "text",
          "required": true,
          "options": {
            "default": "Author Name"
          }
        },
        "pages": {
          "type": "integer",
          "required": true,
          "options": {
            "default": 300
          }
        }
      },
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtObject",
      "exportName": "Issue75Book",
      "collectionExportName": "Issue75BookCollection"
    },
    "issue87parentevent": {
      "name": "issue87parentevent",
      "className": "Issue87ParentEvent",
      "collection": "issue87parentevents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {
        "startDate": {
          "type": "datetime",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "endDate": {
          "type": "datetime",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "issuedAt": {
          "type": "datetime",
          "required": true,
          "options": {
            "nullable": true
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "Issue87ParentEvent",
      "collectionExportName": "Issue87ParentEventCollection"
    },
    "issue87childevent": {
      "name": "issue87childevent",
      "className": "Issue87ChildEvent",
      "collection": "issue87childevents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {
        "temperature": {
          "type": "integer",
          "required": true
        },
        "description": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "Issue87ParentEvent",
      "exportName": "Issue87ChildEvent",
      "collectionExportName": "Issue87ChildEventCollection"
    },
    "issue87parenteventcollection": {
      "name": "issue87parenteventcollection",
      "className": "Issue87ParentEventCollection",
      "collection": "issue87parenteventcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "Issue87ParentEventCollection",
      "collectionExportName": "Issue87ParentEventCollectionCollection"
    },
    "issue87childeventcollection": {
      "name": "issue87childeventcollection",
      "className": "Issue87ChildEventCollection",
      "collection": "issue87childeventcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "Issue87ChildEventCollection",
      "collectionExportName": "Issue87ChildEventCollectionCollection"
    },
    "issue87basemodel": {
      "name": "issue87basemodel",
      "className": "Issue87BaseModel",
      "collection": "issue87basemodels",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {
        "textField": {
          "type": "text",
          "required": true
        },
        "numberField": {
          "type": "integer",
          "required": true
        },
        "booleanField": {
          "type": "boolean",
          "required": true
        },
        "issueDate": {
          "type": "datetime",
          "required": true,
          "options": {
            "nullable": true
          }
        },
        "optionalEventDate": {
          "type": "datetime",
          "required": true,
          "options": {
            "nullable": true
          }
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "Issue87BaseModel",
      "collectionExportName": "Issue87BaseModelCollection"
    },
    "issue87derivedmodel": {
      "name": "issue87derivedmodel",
      "className": "Issue87DerivedModel",
      "collection": "issue87derivedmodels",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {
        "derivedField": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "Issue87BaseModel",
      "exportName": "Issue87DerivedModel",
      "collectionExportName": "Issue87DerivedModelCollection"
    },
    "issue87derivedmodelcollection": {
      "name": "issue87derivedmodelcollection",
      "className": "Issue87DerivedModelCollection",
      "collection": "issue87derivedmodelcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-87-inherited-date-fields.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "Issue87DerivedModelCollection",
      "collectionExportName": "Issue87DerivedModelCollectionCollection"
    },
    "testdocumentforduckdb": {
      "name": "testdocumentforduckdb",
      "className": "TestDocumentForDuckDB",
      "collection": "testdocumentforduckdbs",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true
        },
        "content": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "TestDocumentForDuckDB",
      "collectionExportName": "TestDocumentForDuckDBCollection"
    },
    "testdocumentcollection": {
      "name": "testdocumentcollection",
      "className": "TestDocumentCollection",
      "collection": "testdocumentcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "TestDocumentCollection",
      "collectionExportName": "TestDocumentCollectionCollection"
    },
    "indexeddocument": {
      "name": "indexeddocument",
      "className": "IndexedDocument",
      "collection": "indexeddocuments",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true
        },
        "category": {
          "type": "text",
          "required": true
        },
        "priority": {
          "type": "integer",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "IndexedDocument",
      "collectionExportName": "IndexedDocumentCollection"
    },
    "indexeddocumentcollection": {
      "name": "indexeddocumentcollection",
      "className": "IndexedDocumentCollection",
      "collection": "indexeddocumentcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "IndexedDocumentCollection",
      "collectionExportName": "IndexedDocumentCollectionCollection"
    },
    "scopeddocument": {
      "name": "scopeddocument",
      "className": "ScopedDocument",
      "collection": "scopeddocuments",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true
        },
        "content": {
          "type": "text",
          "required": false
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "ScopedDocument",
      "collectionExportName": "ScopedDocumentCollection"
    },
    "scopeddocumentcollection": {
      "name": "scopeddocumentcollection",
      "className": "ScopedDocumentCollection",
      "collection": "scopeddocumentcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/issue-89-duckdb-schema-transformation.test.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "ScopedDocumentCollection",
      "collectionExportName": "ScopedDocumentCollectionCollection"
    },
    "schemagentestevent": {
      "name": "schemagentestevent",
      "className": "SchemaGenTestEvent",
      "collection": "schemagentestevents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/schema-generation.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "description": {
          "type": "text",
          "required": true
        },
        "startDate": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "SchemaGenTestEvent",
      "collectionExportName": "SchemaGenTestEventCollection"
    },
    "schemagenarticle": {
      "name": "schemagenarticle",
      "className": "SchemaGenArticle",
      "collection": "schemagenarticles",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/schema-generation.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "body": {
          "type": "text",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "SchemaGenArticle",
      "collectionExportName": "SchemaGenArticleCollection"
    },
    "customtimestamps": {
      "name": "customtimestamps",
      "className": "CustomTimestamps",
      "collection": "customtimestampses",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/__tests__/schema-generation.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "created_at": {
          "type": "datetime",
          "required": true
        },
        "updated_at": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {},
      "decoratorConfig": {
        "api": {},
        "mcp": {},
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "CustomTimestamps",
      "collectionExportName": "CustomTimestampsCollection"
    },
    "testproductcollection": {
      "name": "testproductcollection",
      "className": "TestProductCollection",
      "collection": "testproductcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-integration.spec.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "TestProductCollection",
      "collectionExportName": "TestProductCollectionCollection"
    },
    "protocoltestobject": {
      "name": "protocoltestobject",
      "className": "ProtocolTestObject",
      "collection": "protocoltestobjects",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-protocol.spec.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true
        },
        "count": {
          "type": "integer",
          "required": true
        }
      },
      "methods": {
        "testAction": {
          "name": "testAction",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "void",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "mcp": {
          "include": [
            "list",
            "get",
            "testAction"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "ProtocolTestObject",
      "collectionExportName": "ProtocolTestObjectCollection"
    },
    "protocoltestobjectcollection": {
      "name": "protocoltestobjectcollection",
      "className": "ProtocolTestObjectCollection",
      "collection": "protocoltestobjectcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp-protocol.spec.ts",
      "fields": {},
      "methods": {},
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "exportName": "ProtocolTestObjectCollection",
      "collectionExportName": "ProtocolTestObjectCollectionCollection"
    },
    "testagent": {
      "name": "testagent",
      "className": "TestAgent",
      "collection": "testagents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "source": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {
        "research": {
          "name": "research",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        },
        "report": {
          "name": "report",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        },
        "analyze": {
          "name": "analyze",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "mcp": {
          "include": [
            "list",
            "get",
            "research",
            "report",
            "analyze"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "TestAgent",
      "collectionExportName": "TestAgentCollection"
    },
    "invalidactionagent": {
      "name": "invalidactionagent",
      "className": "InvalidActionAgent",
      "collection": "invalidactionagents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "mcp": {
          "include": [
            "list",
            "get",
            "nonexistent"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "InvalidActionAgent",
      "collectionExportName": "InvalidActionAgentCollection"
    },
    "excludedactionagent": {
      "name": "excludedactionagent",
      "className": "ExcludedActionAgent",
      "collection": "excludedactionagents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/generators/mcp.test.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {
        "research": {
          "name": "research",
          "async": true,
          "parameters": [],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        },
        "report": {
          "name": "report",
          "async": true,
          "parameters": [],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "mcp": {
          "include": [
            "list",
            "get",
            "research",
            "report"
          ],
          "exclude": [
            "report"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "ExcludedActionAgent",
      "collectionExportName": "ExcludedActionAgentCollection"
    },
    "document": {
      "name": "document",
      "className": "Document",
      "collection": "documents",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "content": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {
        "analyze": {
          "name": "analyze",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "any",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "cli": true
      },
      "extends": "SmrtObject",
      "exportName": "Document",
      "collectionExportName": "DocumentCollection"
    },
    "secret": {
      "name": "secret",
      "className": "Secret",
      "collection": "secrets",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts",
      "fields": {
        "value": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {},
      "decoratorConfig": {
        "cli": false
      },
      "extends": "SmrtObject",
      "exportName": "Secret",
      "collectionExportName": "SecretCollection"
    },
    "article": {
      "name": "article",
      "className": "Article",
      "collection": "articles",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/core/src/vite-plugin/cli-module.test.ts",
      "fields": {
        "title": {
          "type": "text",
          "required": true,
          "default": ""
        },
        "author": {
          "type": "text",
          "required": true,
          "default": ""
        }
      },
      "methods": {
        "analyze": {
          "name": "analyze",
          "async": true,
          "parameters": [],
          "returnType": "Promise<any>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "cli": {
          "include": [
            "list",
            "get",
            "analyze"
          ],
          "exclude": [
            "delete"
          ]
        }
      },
      "extends": "SmrtObject",
      "exportName": "Article",
      "collectionExportName": "ArticleCollection"
    }
  },
  "packageName": "@happyvertical/smrt-core"
} as const;

export default testManifest;
