// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom action: withdrawAction
export const POST: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:ContentContribution',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(
      404,
      '@happyvertical/smrt-content:ContentContribution not found',
    );

  const options = await request.json();
  const result = await item.withdrawAction(options);

  return json({ action: 'withdrawAction', result });
};
