/**
 * Pre-build utilities for generating TypeScript declarations
 * Solves virtual module resolution by creating physical .d.ts files
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import type { SmartObjectManifest } from '../scanner/types';

export interface PrebuildOptions {
  /** Path to manifest file or manifest object */
  manifest: string | SmartObjectManifest;
  /** Output directory for generated types */
  outDir: string;
  /** Include virtual module declarations */
  includeVirtualModules?: boolean;
  /** Include object type definitions */
  includeObjectTypes?: boolean;
  /** Project root path for resolving relative paths */
  projectRoot?: string;
}

/**
 * Generate TypeScript declaration files from SMRT manifest
 */
export async function generateDeclarations(
  options: PrebuildOptions,
): Promise<void> {
  const {
    manifest: manifestInput,
    outDir,
    includeVirtualModules = true,
    includeObjectTypes = true,
    projectRoot = process.cwd(),
  } = options;

  // Load manifest
  const manifest: SmartObjectManifest =
    typeof manifestInput === 'string'
      ? JSON.parse(fs.readFileSync(manifestInput, 'utf-8'))
      : manifestInput;

  // Ensure output directory exists
  const fullOutDir = path.isAbsolute(outDir)
    ? outDir
    : path.join(projectRoot, outDir);
  fs.mkdirSync(fullOutDir, { recursive: true });

  console.log(`[smrt:prebuild] Generating declarations to ${fullOutDir}`);

  if (includeObjectTypes) {
    await generateObjectTypeDeclarations(manifest, fullOutDir);
  }

  if (includeVirtualModules) {
    await generateVirtualModuleDeclarations(manifest, fullOutDir);
  }

  console.log(
    `[smrt:prebuild] Generated declarations for ${Object.keys(manifest.objects).length} SMRT objects`,
  );
}

/**
 * Generate TypeScript interfaces for SMRT objects
 */
async function generateObjectTypeDeclarations(
  manifest: SmartObjectManifest,
  outDir: string,
): Promise<void> {
  const interfaces: string[] = [];

  // Generate interfaces for each discovered SMRT object
  for (const [_objectName, objectMeta] of Object.entries(manifest.objects)) {
    const fields = objectMeta.fields || {};
    const propertyLines: string[] = [];

    // Add standard SmrtObject properties
    propertyLines.push('  id?: string;');
    propertyLines.push('  created_at?: string;');
    propertyLines.push('  updated_at?: string;');

    // Add object-specific properties
    for (const [fieldName, fieldDef] of Object.entries(fields)) {
      const type = mapFieldTypeToTypeScript(fieldDef.type);
      const optional = !fieldDef.required ? '?' : '';
      propertyLines.push(`  ${fieldName}${optional}: ${type};`);
    }

    const interfaceDef = `export interface ${objectMeta.className}Data {
${propertyLines.join('\n')}
}`;
    interfaces.push(interfaceDef);
  }

  // Write object types file
  const objectTypesContent = `/**
 * Auto-generated TypeScript interfaces for SMRT objects
 * Generated at build time from @smrt() decorated classes
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

${interfaces.join('\n\n')}
`;

  fs.writeFileSync(path.join(outDir, 'smrt-objects.d.ts'), objectTypesContent);
}

/**
 * Generate virtual module declarations
 */
async function generateVirtualModuleDeclarations(
  manifest: SmartObjectManifest,
  outDir: string,
): Promise<void> {
  // Generate manifest module declaration
  const manifestDeclaration = `/**
 * Auto-generated manifest module declaration
 */
declare module '@smrt/manifest' {
  export interface SmrtObjectField {
    type: string;
    required?: boolean;
    default?: any;
  }

  export interface SmrtObjectMethod {
    name: string;
    parameters: Array<{
      name: string;
      type: string;
      optional?: boolean;
      default?: any;
    }>;
    returnType: string;
    async: boolean;
    isStatic: boolean;
    isPublic: boolean;
  }

  export interface SmrtObjectDefinition {
    name: string;
    className: string;
    collection: string;
    filePath: string;
    fields: Record<string, SmrtObjectField>;
    methods: Record<string, SmrtObjectMethod>;
    decoratorConfig: any;
    extends?: string;
  }

  export interface SmrtManifest {
    version: string;
    timestamp: number;
    objects: Record<string, SmrtObjectDefinition>;
  }

  export const manifest: SmrtManifest;
  export default manifest;
}`;

  // Generate client module declaration
  const collectionNames = [
    ...new Set(Object.values(manifest.objects).map((obj) => obj.collection)),
  ];

  const apiClientInterface = collectionNames
    .map((collection) => {
      const dataType = Object.entries(manifest.objects).find(
        ([, obj]) => obj.collection === collection,
      )?.[1].className;
      const interfaceName = dataType ? `${dataType}Data` : 'any';
      return `    ${collection}: CrudOperations<${interfaceName}>;`;
    })
    .join('\n');

  const clientDeclaration = `/**
 * Auto-generated API client module declaration
 */
declare module '@smrt/client' {
  export interface ApiResponse<T = any> {
    id?: string;
    data?: T;
    error?: string;
    message?: string;
  }

  export interface CrudOperations<T = any> {
    list(params?: Record<string, any>): Promise<ApiResponse<T[]>>;
    get(id: string): Promise<ApiResponse<T>>;
    create(data: Partial<T>): Promise<ApiResponse<T>>;
    update(id: string, data: Partial<T>): Promise<ApiResponse<T>>;
    delete(id: string): Promise<boolean>;
  }

  export interface ApiClient {
${apiClientInterface}
  }

  export function createClient(basePath?: string): ApiClient;
  export default createClient;
}`;

  // Generate web collection-definition module declaration (spike #1756).
  // Selection mirrors the vite-plugin's generateWebModule: skip collection
  // classes, require `list` on the api surface (omitted api config means the
  // full CRUD surface is exposed, so it qualifies), one entry per REST
  // collection (STI children folding into their base table's definition).
  const isCollectionClassDef = (
    obj: {
      extends?: string;
      extendsQualified?: string;
      extendsTypeArg?: string;
    },
    seen: Set<string> = new Set(),
  ): boolean => {
    if (obj.extends === 'SmrtCollection' || obj.extendsTypeArg !== undefined) {
      return true;
    }
    // Walk the extends chain within the manifest: deeper collection
    // subclasses (e.g. MaterialCollection extends ProductCollection) carry
    // no type arg themselves.
    const parentName = obj.extendsQualified || obj.extends;
    if (!parentName || seen.has(parentName)) return false;
    seen.add(parentName);
    const parent = Object.values(manifest.objects).find(
      (candidate) =>
        candidate.qualifiedName === parentName ||
        candidate.className === parentName,
    );
    return parent ? isCollectionClassDef(parent, seen) : false;
  };

  const exposesList = (obj: { decoratorConfig?: unknown }): boolean => {
    const api = (obj.decoratorConfig as { api?: unknown } | undefined)?.api;
    if (api === false) return false;
    if (api && typeof api === 'object') {
      const include = (api as { include?: unknown }).include;
      if (Array.isArray(include)) return include.includes('list');
      const exclude = (api as { exclude?: unknown }).exclude;
      if (Array.isArray(exclude)) return !exclude.includes('list');
    }
    return true;
  };

  // True when some ancestor model maps to the same REST collection: the STI
  // base model owns the shared table's definition.
  const isStiChildDef = (obj: {
    collection: string;
    extends?: string;
    extendsQualified?: string;
  }): boolean => {
    const seen = new Set<string>();
    let parentName = obj.extendsQualified || obj.extends;
    while (parentName && !seen.has(parentName)) {
      seen.add(parentName);
      const name: string = parentName;
      const parent = Object.values(manifest.objects).find(
        (candidate) =>
          candidate.qualifiedName === name || candidate.className === name,
      );
      if (!parent) return false;
      if (parent.collection === obj.collection) return true;
      parentName = parent.extendsQualified || parent.extends;
    }
    return false;
  };

  const webCollectionChoices = new Map<
    string,
    { className: string; isStiChild: boolean }
  >();
  for (const obj of Object.values(manifest.objects)) {
    if (isCollectionClassDef(obj)) continue;
    if (!exposesList(obj)) continue;
    const isStiChild = isStiChildDef(obj);
    const existing = webCollectionChoices.get(obj.collection);
    if (existing && !(existing.isStiChild && !isStiChild)) continue;
    webCollectionChoices.set(obj.collection, {
      className: obj.className,
      isStiChild,
    });
  }
  const webCollectionEntries = [...webCollectionChoices.entries()].map(
    ([collection, choice]) =>
      `    ${collection}: SmrtWebCollectionDefinition<import('./smrt-objects').${choice.className}Data>;`,
  );

  const webDeclaration = `/**
 * Auto-generated web collection-definition module declaration (spike #1756)
 */
declare module '@smrt/web' {
  export interface SmrtWebFieldDefinition {
    type: string;
    required?: boolean;
    default?: unknown;
  }

  export interface SmrtWebCollectionDefinition<TData = Record<string, unknown>> {
    name: string;
    className: string;
    endpoint: string;
    idField: string;
    actions: string[];
    fields: Record<string, SmrtWebFieldDefinition>;
    /** Phantom row-type carrier for inference — never present at runtime. */
    _row?: TData;
  }

  export interface SmrtWebCollectionDefinitions {
${webCollectionEntries.join('\n')}
  }

  export const collectionDefinitions: SmrtWebCollectionDefinitions;
  export function getCollectionDefinition<
    K extends keyof SmrtWebCollectionDefinitions,
  >(name: K): SmrtWebCollectionDefinitions[K];
  export default collectionDefinitions;
}`;

  // Generate routes module declaration
  const routesDeclaration = `/**
 * Auto-generated routes module declaration
 */
declare module '@smrt/routes' {
  export interface RouteApp {
    get(path: string, handler: (req: any, res: any) => void): void;
    post(path: string, handler: (req: any, res: any) => void): void;
    put(path: string, handler: (req: any, res: any) => void): void;
    delete(path: string, handler: (req: any, res: any) => void): void;
  }

  export function setupRoutes(app: RouteApp): void;
  export default setupRoutes;
}`;

  // Generate MCP module declaration
  const mcpDeclaration = `/**
 * Auto-generated MCP module declaration
 */
declare module '@smrt/mcp' {
  export interface McpTool {
    name: string;
    description: string;
    inputSchema: {
      type: string;
      properties: Record<string, any>;
      required?: string[];
    };
  }

  export const tools: McpTool[];
  export function createMCPServer(): {
    name: string;
    version: string;
    tools: McpTool[]
  };
  export default createMCPServer;
}`;

  // Generate types module declaration with object imports
  const objectImports = Object.values(manifest.objects)
    .map(
      (obj) =>
        `  export type ${obj.className}Data = import('./smrt-objects').${obj.className}Data;`,
    )
    .join('\n');

  const typesDeclaration = `/**
 * Auto-generated types module declaration
 */
declare module '@smrt/types' {
${objectImports}

  export interface Request {
    params: Record<string, string>;
    query: Record<string, any>;
    json(): Promise<any>;
  }

  export interface Response {
    json(data: any, init?: { status?: number }): Response;
    status(code: number): Response;
  }
}`;

  // Write all virtual module declarations
  fs.writeFileSync(
    path.join(outDir, 'smrt-manifest.d.ts'),
    manifestDeclaration,
  );
  fs.writeFileSync(path.join(outDir, 'smrt-client.d.ts'), clientDeclaration);
  fs.writeFileSync(path.join(outDir, 'smrt-routes.d.ts'), routesDeclaration);
  fs.writeFileSync(path.join(outDir, 'smrt-mcp.d.ts'), mcpDeclaration);
  fs.writeFileSync(path.join(outDir, 'smrt-types.d.ts'), typesDeclaration);
  fs.writeFileSync(path.join(outDir, 'smrt-web.d.ts'), webDeclaration);
}

/**
 * Map SMRT field types to TypeScript types
 */
function mapFieldTypeToTypeScript(smrtType: string): string {
  switch (smrtType) {
    case 'text':
      return 'string';
    case 'decimal':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'datetime':
      return 'string | Date';
    case 'json':
      return 'any';
    case 'foreignKey':
      return 'string';
    default:
      return 'any';
  }
}

/**
 * CLI command for generating declarations
 */
export async function generateDeclarationsFromCLI(
  args: string[],
): Promise<void> {
  const manifestPath = args[0];
  const outDir = args[1] || 'src/types/generated';

  if (!manifestPath) {
    console.error('Usage: generate-declarations <manifest-path> [output-dir]');
    process.exit(1);
  }

  if (!fs.existsSync(manifestPath)) {
    console.error(`Manifest file not found: ${manifestPath}`);
    process.exit(1);
  }

  await generateDeclarations({
    manifest: manifestPath,
    outDir,
  });
}
