/**
 * Centralized SMRT configuration with per-object overrides
 * Generated by @smrt/core vite plugin
 *
 * Most objects will use the default configuration.
 * Add entries to `objectOverrides` for objects that need different backends.
 */

// Import SMRT objects to register them via @smrt() decorators
import './smrt-register.js';

import type {
  DatabaseConfig,
  SmrtClassOptions,
  SmrtObject,
} from '@happyvertical/smrt-core';
import { ObjectRegistry } from '@happyvertical/smrt-core';

/**
 * Shallow-merge two database configs, layering `override` over `base`.
 *
 * Preserves the prior `{ ...base, ...override }` spread semantics exactly while
 * avoiding `any`: `DatabaseConfig` is a union (`string | object |
 * DatabaseInterface`), so we spread each side through its object-record view.
 * In practice both sides are the object form (`{ url, type }`); the cast only
 * satisfies the union, it does not change runtime behavior.
 */
function mergeDbConfig(
  base: DatabaseConfig | undefined,
  override: DatabaseConfig | undefined,
): DatabaseConfig {
  if (!override) {
    return base as DatabaseConfig;
  }
  return {
    ...(base as Record<string, unknown>),
    ...(override as Record<string, unknown>),
  } as DatabaseConfig;
}

/**
 * Per-object configuration overrides
 * Define specific backends for objects that differ from project defaults
 *
 * @example
 * const objectOverrides: Record<string, Partial<SmrtClassOptions>> = {
 *   // Analytics uses a separate PostgreSQL database
 *   Analytics: {
 *     db: {
 *       url: process.env.ANALYTICS_DATABASE_URL!,
 *       type: 'postgres'
 *     }
 *   },
 *
 *   // AuditLog uses dedicated database with no AI
 *   AuditLog: {
 *     db: {
 *       url: process.env.AUDIT_DATABASE_URL!,
 *       type: 'postgres'
 *     },
 *     ai: undefined
 *   },
 *
 *   // Cache uses REST adapter (e.g., Redis)
 *   Cache: {
 *     persistence: {
 *       type: 'rest',
 *       baseUrl: process.env.REDIS_URL!
 *     }
 *   }
 * };
 */
const objectOverrides: Record<string, Partial<SmrtClassOptions>> = {
  // Add your per-object configuration overrides here
};

/**
 * Default configuration for most SMRT objects
 * Customize this to change project-wide defaults
 */
function getDefaultConfig(): SmrtClassOptions {
  return {
    db: {
      url: process.env.DATABASE_URL || '.smrt/local.db',
      type: (process.env.DATABASE_TYPE as 'sqlite' | 'postgres') || 'sqlite',
    },
    ai: process.env.OPENAI_API_KEY
      ? {
          type: 'openai',
          apiKey: process.env.OPENAI_API_KEY,
        }
      : process.env.ANTHROPIC_API_KEY
        ? {
            type: 'anthropic',
            apiKey: process.env.ANTHROPIC_API_KEY,
          }
        : undefined,
  };
}

/**
 * Get configuration for a specific SMRT object
 * Merges project defaults with per-object overrides if defined
 */
export function getSmrtConfig(className: string): SmrtClassOptions {
  const defaults = getDefaultConfig();
  const override = objectOverrides[className];

  if (override) {
    return {
      ...defaults,
      ...override,
      // Ensure nested objects are merged properly
      db: mergeDbConfig(defaults.db, override.db),
      ai: override.ai !== undefined ? override.ai : defaults.ai,
    };
  }

  return defaults;
}

/**
 * Helper to get a collection with centralized configuration
 * Automatically applies project defaults or object-specific overrides
 */
export async function getCollection<T extends SmrtObject>(
  className: string,
  overrides: Partial<SmrtClassOptions> = {},
) {
  const config = getSmrtConfig(className);

  return await ObjectRegistry.getCollection<T>(className, {
    ...config,
    ...overrides,
    db: mergeDbConfig(config.db, overrides.db),
    ai: overrides.ai !== undefined ? overrides.ai : config.ai,
  });
}
