import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import {
  frameworkKotlinFiles,
  frameworkSwiftFiles,
} from '../emit-framework.js';
import { verifyFileSet, writeFileSet } from '../file-set.js';

const SMRT_MOBILE_CONTRACT_DIR = resolve(
  import.meta.dirname,
  '../../../smrt-mobile/src/commonMain/kotlin/com/happyvertical/smrt/mobile/contract',
);

describe('frameworkKotlinFiles', () => {
  const files = frameworkKotlinFiles();

  it('emits the five framework contract files with generated headers', () => {
    expect([...files.keys()].sort()).toEqual([
      'MobileAuthContract.kt',
      'MobileContractInfo.kt',
      'MobileDeviceContract.kt',
      'PackLocalization.kt',
      'SupportTypes.kt',
    ]);
    for (const content of files.values()) {
      expect(content).toContain(
        'Generated by @happyvertical/smrt-mobile-contract',
      );
      expect(content).toContain(
        'package com.happyvertical.smrt.mobile.contract',
      );
    }
  });

  it('matches the files checked into @happyvertical/smrt-mobile', () => {
    // The build script also verifies this; the test keeps drift red in the
    // test lane even when the build task replays from cache.
    expect(verifyFileSet(SMRT_MOBILE_CONTRACT_DIR, files)).toEqual([]);
  });
});

describe('frameworkSwiftFiles', () => {
  it('mirrors the auth/session/device contract for SwiftUI apps', () => {
    const swift = frameworkSwiftFiles().get('MobileContract.swift') ?? '';

    expect(swift).toContain('struct MobileAuthStartRequest {');
    expect(swift).toContain('struct MobileAuthSession {');
    expect(swift).toContain('struct MobileDeviceCapabilities {');
    expect(swift).toContain('let SmrtMobileContractVersion = "2026-07-01.v1"');
  });

  it('stays field-for-field in sync with the Kotlin framework contract', () => {
    // Both templates are generated text with fixed shapes, so parsing them
    // is reliable: every Swift struct must have a Kotlin data class twin
    // with the identical ordered field-name list. Catches the hand-edited
    // Kotlin / stale Swift drift (and vice versa) that byte-freshness alone
    // cannot see.
    const kotlin = [...frameworkKotlinFiles().values()].join('\n');
    const swift = frameworkSwiftFiles().get('MobileContract.swift') ?? '';

    const kotlinTypes = new Map<string, string[]>();
    for (const match of kotlin.matchAll(
      /data class (\w+)\(\n([\s\S]*?)\n\)/g,
    )) {
      kotlinTypes.set(
        match[1],
        [...match[2].matchAll(/^ {4}val (\w+):/gm)].map((field) => field[1]),
      );
    }

    const swiftStructs = [
      ...swift.matchAll(/struct (\w+) \{\n([\s\S]*?)\n\}/g),
    ];
    expect(swiftStructs.length).toBeGreaterThanOrEqual(12);

    for (const [, name, body] of swiftStructs) {
      const swiftFields = [...body.matchAll(/^ {2}let `?(\w+)`?:/gm)].map(
        (field) => field[1],
      );
      expect(kotlinTypes.get(name), `Kotlin twin for struct ${name}`).toEqual(
        swiftFields,
      );
    }
  });
});

describe('writeFileSet / verifyFileSet', () => {
  const tempDir = mkdtempSync(join(tmpdir(), 'smrt-mobile-contract-'));

  afterAll(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('round-trips a file set and reports staleness', () => {
    const files = new Map([
      ['a/one.kt', 'alpha\n'],
      ['two.kt', 'beta\n'],
    ]);

    writeFileSet(tempDir, files);
    expect(verifyFileSet(tempDir, files)).toEqual([]);

    const drifted = new Map(files);
    drifted.set('two.kt', 'gamma\n');
    expect(verifyFileSet(tempDir, drifted)).toEqual(['two.kt']);

    drifted.set('missing/three.kt', 'delta\n');
    expect(verifyFileSet(tempDir, drifted)).toContain('missing/three.kt');
  });
});
