// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';

// Custom action: listVersions
export const GET: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:Content');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const result = await item.listVersions();

  return json({ action: 'listVersions', result });
};

// Custom action: mutateVersionAction
export const POST: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:Content');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const options = await request.json();
  const result = await item.mutateVersionAction(options);

  return json({ action: 'mutateVersionAction', result });
};
