/**
 * ProfileType model - Lookup table defining profile types
 *
 * Represents the nature of a profile (e.g., 'human', 'org', 'robot').
 * Uses UUID primary key with unique slug for human-readable lookups.
 */

import {
  field,
  SmrtObject,
  type SmrtObjectOptions,
  smrt,
} from '@happyvertical/smrt-core';
import { TenantScoped, tenantId } from '@happyvertical/smrt-tenancy';

export interface ProfileTypeOptions extends SmrtObjectOptions {
  slug?: string;
  name?: string;
  description?: string;
  tenantId?: string | null;
}

@TenantScoped({ mode: 'optional' })
@smrt({
  tableStrategy: 'sti',
  api: { include: ['list', 'get', 'create', 'update'] },
  mcp: { include: ['list', 'get'] },
  cli: true,
})
export class ProfileType extends SmrtObject {
  @tenantId({ nullable: true })
  tenantId: string | null = null;

  // id: UUID (auto-generated by SmrtObject)
  // slug is inherited from SmrtObject (auto-generated from name)
  @field({ required: true })
  name: string = '';

  description?: string;

  constructor(options: ProfileTypeOptions = {}) {
    super(options);
    if (options.name) this.name = options.name;
    if (options.description !== undefined)
      this.description = options.description;
  }

  /**
   * Convenience method for slug-based lookup
   *
   * @param slug - The slug to search for
   * @returns ProfileType instance or null if not found
   */
  static async getBySlug(_slug: string): Promise<ProfileType | null> {
    // Will be auto-implemented by SMRT
    return null;
  }
}
