/**
 * Profile model - Core entity representing any profile type
 *
 * Central table holding all primary entities with type, email, name, and description.
 * Uses UUID primary key with relationships to ProfileType for classification.
 */

import type { Asset } from '@happyvertical/smrt-assets';

import {
  field,
  foreignKey,
  oneToMany,
  SmrtObject,
  type SmrtObjectOptions,
  smrt,
} from '@happyvertical/smrt-core';
import { TenantScoped, tenantId } from '@happyvertical/smrt-tenancy';
import type { ProfileRelationship } from './ProfileRelationship';
import { ProfileType } from './ProfileType';

export interface ProfileOptions extends SmrtObjectOptions {
  typeId?: string;
  email?: string;
  name?: string;
  description?: string;
  tenantId?: string | null;
}

const ASSET_RELATIONSHIP_PATTERN = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

function assertValidAssetRelationship(relationship: string): void {
  if (!ASSET_RELATIONSHIP_PATTERN.test(relationship)) {
    throw new Error(
      `Invalid relationship type "${relationship}"; must start with a letter or underscore and contain only letters, digits, and underscores`,
    );
  }
}

function assertValidAssetSortOrder(sortOrder: number): void {
  if (!Number.isInteger(sortOrder) || sortOrder < 0 || sortOrder > 2147483647) {
    throw new Error(
      `Invalid sortOrder "${sortOrder}"; must be a non-negative integer`,
    );
  }
}

@TenantScoped({ mode: 'optional' })
@smrt({
  tableStrategy: 'sti',
  api: { include: ['list', 'get', 'create', 'update', 'delete'] },
  mcp: { include: ['list', 'get', 'create', 'update'] },
  cli: true,
})
export class Profile extends SmrtObject {
  @tenantId({ nullable: true })
  tenantId: string | null = null;

  // id: UUID (auto-generated by SmrtObject)
  @foreignKey('ProfileType', { required: true })
  typeId?: string; // References ProfileType.id

  @field({ unique: true })
  email?: string; // Optional email address

  @field({ required: true })
  name: string = ''; // Display name

  description?: string; // Short bio or description

  // Relationships (not stored as columns)
  @oneToMany('ProfileMetadata')
  metadata: any[] = [];

  @oneToMany('ProfileRelationship')
  relationshipsFrom: any[] = [];

  @oneToMany('ProfileRelationship')
  relationshipsTo: any[] = [];

  constructor(options: ProfileOptions = {}) {
    super(options);
    if (options.typeId !== undefined) this.typeId = options.typeId;
    if (options.email !== undefined) this.email = options.email;
    if (options.name) this.name = options.name;
    if (options.description !== undefined)
      this.description = options.description;
  }

  /**
   * Get the profile type slug for this profile
   *
   * @returns The slug of the profile type
   */
  async getTypeSlug(): Promise<string> {
    const type = await this.loadRelated('typeId');
    return type?.slug || '';
  }

  /**
   * Set the profile type by slug
   *
   * @param slug - The slug of the profile type
   * @throws Error if profile type not found
   */
  async setTypeBySlug(slug: string): Promise<void> {
    const type = await ProfileType.getBySlug(slug);
    if (!type) throw new Error(`Profile type '${slug}' not found`);
    this.typeId = type.id as string;
  }

  /**
   * Add metadata to this profile
   *
   * @param metafieldSlug - The slug of the metafield
   * @param value - The value to set
   */
  async addMetadata(metafieldSlug: string, value: any): Promise<void> {
    const { ProfileMetafieldCollection } = await import(
      '../collections/ProfileMetafieldCollection'
    );
    const { ProfileMetadataCollection } = await import(
      '../collections/ProfileMetadataCollection'
    );

    // Get or create metafield collection
    const metafieldCollection = await (
      ProfileMetafieldCollection as any
    ).create(this.options);

    // Find the metafield by slug
    const metafield = await metafieldCollection.getBySlug(metafieldSlug);
    if (!metafield) {
      throw new Error(`Metafield '${metafieldSlug}' not found`);
    }

    // Validate the value
    await metafield.validateValue(value);

    // Get or create metadata collection
    const metadataCollection = await (ProfileMetadataCollection as any).create(
      this.options,
    );

    // Check if metadata already exists
    const existing = await metadataCollection.list({
      where: { profileId: this.id, metafieldId: metafield.id },
      limit: 1,
    });

    if (existing.length > 0) {
      // Update existing
      const metadata = existing[0];
      metadata.value = String(value);
      await metadata.save();
    } else {
      // Create new
      const metadata = await metadataCollection.create({
        profileId: this.id,
        metafieldId: metafield.id,
        value: String(value),
      });
      await metadata.save();
    }
  }

  /**
   * Get all metadata for this profile as key-value object
   *
   * @returns Object with metafield slugs as keys
   */
  async getMetadata(): Promise<Record<string, any>> {
    const { ProfileMetadataCollection } = await import(
      '../collections/ProfileMetadataCollection'
    );

    const metadataCollection = await (ProfileMetadataCollection as any).create(
      this.options,
    );

    return await metadataCollection.getMetadataObject(this.id);
  }

  /**
   * Update multiple metadata values
   *
   * @param metadata - Object with metafield slugs as keys and values
   */
  async updateMetadata(metadata: Record<string, any>): Promise<void> {
    for (const [metafieldSlug, value] of Object.entries(metadata)) {
      await this.addMetadata(metafieldSlug, value);
    }
  }

  /**
   * Remove metadata by metafield slug
   *
   * @param metafieldSlug - The slug of the metafield to remove
   */
  async removeMetadata(metafieldSlug: string): Promise<void> {
    const { ProfileMetafieldCollection } = await import(
      '../collections/ProfileMetafieldCollection'
    );
    const { ProfileMetadataCollection } = await import(
      '../collections/ProfileMetadataCollection'
    );

    const metafieldCollection = await (
      ProfileMetafieldCollection as any
    ).create(this.options);

    const metafield = await metafieldCollection.getBySlug(metafieldSlug);
    if (!metafield) {
      throw new Error(`Metafield '${metafieldSlug}' not found`);
    }

    const metadataCollection = await (ProfileMetadataCollection as any).create(
      this.options,
    );

    const existing = await metadataCollection.list({
      where: { profileId: this.id, metafieldId: metafield.id },
      limit: 1,
    });

    if (existing.length > 0) {
      await existing[0].delete();
    }
  }

  private async getAssetCollection() {
    const { AssetCollection } = await import('@happyvertical/smrt-assets');
    return AssetCollection.create({ db: this.db });
  }

  private async getProfileAssetCollection() {
    const { ProfileAssetCollection } = await import(
      '../collections/ProfileAssetCollection'
    );
    return ProfileAssetCollection.create({ db: this.db });
  }

  private async resolveAssets(assetIds: string[]): Promise<Asset[]> {
    if (assetIds.length === 0) {
      return [];
    }

    const assets = await this.getAssetCollection();
    const resolved = await assets.listByIds(assetIds);
    const assetsById = new Map(
      resolved
        .filter((asset) => asset.id)
        .map((asset) => [asset.id as string, asset]),
    );

    return assetIds
      .map((assetId) => assetsById.get(assetId))
      .filter(Boolean) as Asset[];
  }

  async getAssets(relationship?: string): Promise<Asset[]> {
    if (!this.id) {
      return [];
    }

    const profileAssets = await this.getProfileAssetCollection();
    const linkedAssets = await profileAssets.getForProfile(
      this.id,
      relationship,
    );

    return this.resolveAssets(linkedAssets.map((link) => link.assetId));
  }

  async addAsset(
    asset: Asset,
    relationship = 'attachment',
    sortOrder = 0,
  ): Promise<void> {
    if (!this.id || !asset.id) {
      throw new Error('Cannot associate unsaved profile or asset');
    }

    assertValidAssetRelationship(relationship);
    assertValidAssetSortOrder(sortOrder);

    const profileAssets = await this.getProfileAssetCollection();
    await profileAssets.attach(
      this.id,
      asset.id,
      relationship,
      sortOrder,
      this.tenantId,
    );
  }

  async removeAsset(assetId: string, relationship?: string): Promise<void> {
    if (!this.id) {
      return;
    }

    const profileAssets = await this.getProfileAssetCollection();
    await profileAssets.detach(this.id, assetId, relationship);
  }

  /**
   * Add a relationship to another profile
   *
   * @param toProfile - The target profile
   * @param relationshipSlug - The type of relationship
   * @param contextProfile - Optional context profile for tertiary relationships
   */
  async addRelationship(
    toProfile: Profile,
    relationshipSlug: string,
    contextProfile?: Profile,
  ): Promise<void> {
    const { ProfileRelationshipTypeCollection } = await import(
      '../collections/ProfileRelationshipTypeCollection'
    );
    const { ProfileRelationshipCollection } = await import(
      '../collections/ProfileRelationshipCollection'
    );
    const { ProfileRelationshipType } = await import(
      './ProfileRelationshipType'
    );

    // Get relationship type
    const relationshipTypeCollection = await (
      ProfileRelationshipTypeCollection as any
    ).create(this.options);

    const relationshipType =
      await relationshipTypeCollection.getBySlug(relationshipSlug);
    if (!relationshipType) {
      throw new Error(`Relationship type '${relationshipSlug}' not found`);
    }

    // Check if relationship already exists
    const relationshipCollection = await (
      ProfileRelationshipCollection as any
    ).create(this.options);

    const exists = await relationshipCollection.exists(
      this.id,
      toProfile.id,
      relationshipType.id,
    );

    if (!exists) {
      // Create the relationship
      const relationship = await relationshipCollection.create({
        fromProfileId: this.id,
        toProfileId: toProfile.id,
        typeId: relationshipType.id,
        contextProfileId: contextProfile?.id,
      });
      await relationship.save();
    }

    // Handle reciprocal relationships
    if (relationshipType.reciprocal) {
      const handler =
        ProfileRelationshipType.getReciprocalHandler(relationshipSlug);
      if (handler) {
        await handler(this, toProfile, contextProfile);
      }
    }
  }

  /**
   * Get all relationships for this profile
   *
   * @param options - Filter options (typeSlug, direction)
   * @returns Array of ProfileRelationship instances
   */
  async getRelationships(options?: {
    typeSlug?: string;
    direction?: 'from' | 'to' | 'all';
  }): Promise<ProfileRelationship[]> {
    const { ProfileRelationshipCollection } = await import(
      '../collections/ProfileRelationshipCollection'
    );
    const { ProfileRelationshipTypeCollection } = await import(
      '../collections/ProfileRelationshipTypeCollection'
    );

    const relationshipCollection = await (
      ProfileRelationshipCollection as any
    ).create(this.options);

    const direction = options?.direction || 'all';

    // Get type ID if typeSlug is provided
    let typeId: string | undefined;
    if (options?.typeSlug) {
      const relationshipTypeCollection = await (
        ProfileRelationshipTypeCollection as any
      ).create(this.options);

      const relationshipType = await relationshipTypeCollection.getBySlug(
        options.typeSlug,
      );
      typeId = relationshipType?.id;
    }

    // Fetch relationships based on direction
    if (direction === 'from') {
      return await relationshipCollection.getFromProfile(this.id, typeId);
    } else if (direction === 'to') {
      return await relationshipCollection.getToProfile(this.id, typeId);
    } else {
      return await relationshipCollection.getForProfile(this.id, typeId);
    }
  }

  /**
   * Get related profiles
   *
   * @param relationshipSlug - Optional filter by relationship type slug
   * @returns Array of related Profile instances
   */
  async getRelatedProfiles(relationshipSlug?: string): Promise<Profile[]> {
    const { ProfileCollection } = await import(
      '../collections/ProfileCollection'
    );

    const relationships = await this.getRelationships({
      typeSlug: relationshipSlug,
      direction: 'all',
    });

    const profileCollection = await (ProfileCollection as any).create(
      this.options,
    );

    const relatedProfiles: Profile[] = [];
    const seenIds = new Set<string>();

    for (const relationship of relationships) {
      // Get the other profile (not this one)
      // Convert Field instances to strings for comparison
      const fromId = String(relationship.fromProfileId);
      const toId = String(relationship.toProfileId);
      const thisId = String(this.id);
      const otherId = fromId === thisId ? toId : fromId;

      if (!seenIds.has(otherId)) {
        seenIds.add(otherId);
        const profile = await profileCollection.get({ id: otherId });
        if (profile) {
          relatedProfiles.push(profile);
        }
      }
    }

    return relatedProfiles;
  }

  /**
   * Remove a relationship to another profile
   *
   * @param toProfile - The target profile
   * @param relationshipSlug - The type of relationship to remove
   */
  async removeRelationship(
    toProfile: Profile,
    relationshipSlug: string,
  ): Promise<void> {
    const { ProfileRelationshipTypeCollection } = await import(
      '../collections/ProfileRelationshipTypeCollection'
    );
    const { ProfileRelationshipCollection } = await import(
      '../collections/ProfileRelationshipCollection'
    );

    // Get relationship type
    const relationshipTypeCollection = await (
      ProfileRelationshipTypeCollection as any
    ).create(this.options);

    const relationshipType =
      await relationshipTypeCollection.getBySlug(relationshipSlug);
    if (!relationshipType) {
      throw new Error(`Relationship type '${relationshipSlug}' not found`);
    }

    // Find and delete the relationship
    const relationshipCollection = await (
      ProfileRelationshipCollection as any
    ).create(this.options);

    const relationships = await relationshipCollection.list({
      where: {
        fromProfileId: this.id,
        toProfileId: toProfile.id,
        typeId: relationshipType.id,
      },
    });

    for (const relationship of relationships) {
      await relationship.delete();
    }

    // Handle reciprocal relationships - delete the inverse
    if (relationshipType.reciprocal) {
      const inverseRelationships = await relationshipCollection.list({
        where: {
          fromProfileId: toProfile.id,
          toProfileId: this.id,
          typeId: relationshipType.id,
        },
      });

      for (const relationship of inverseRelationships) {
        await relationship.delete();
      }
    }
  }

  /**
   * AI-powered: Generate a professional bio for this profile
   *
   * @returns Generated bio text
   */
  async generateBio(): Promise<string> {
    return await this.do('Write a short, professional bio for this person.');
  }

  /**
   * AI-powered: Check if profile matches criteria
   *
   * @param criteria - Criteria to match against
   * @returns True if matches criteria
   */
  async matches(criteria: string): Promise<boolean> {
    return await this.is(criteria);
  }

  /**
   * Find profiles by metadata key-value pair
   *
   * @param metafieldSlug - The metafield slug to search
   * @param value - The value to match
   * @returns Array of matching profiles
   */
  static async findByMetadata(
    _metafieldSlug: string,
    _value: any,
  ): Promise<Profile[]> {
    // Will be auto-implemented by SMRT
    return [];
  }

  /**
   * Find profiles by type slug
   *
   * @param typeSlug - The profile type slug
   * @returns Array of matching profiles
   */
  static async findByType(_typeSlug: string): Promise<Profile[]> {
    // Will be auto-implemented by SMRT
    return [];
  }

  /**
   * Find related profiles for a given profile
   *
   * @param profileId - The profile UUID
   * @param relationshipSlug - Optional filter by relationship type
   * @returns Array of related profiles
   */
  static async findRelated(
    _profileId: string,
    _relationshipSlug?: string,
  ): Promise<Profile[]> {
    // Will be auto-implemented by SMRT
    return [];
  }

  /**
   * Search profiles by email
   *
   * @param email - The email to search for
   * @returns Profile or null if not found
   */
  static async searchByEmail(_email: string): Promise<Profile | null> {
    // Will be auto-implemented by SMRT
    return null;
  }

  // ========================
  // Auth-related methods
  // ========================

  /**
   * Get all API keys for this profile
   *
   * @returns Array of API keys
   */
  async getApiKeys(): Promise<any[]> {
    const { ApiKeyCollection } = await import(
      '../collections/ApiKeyCollection'
    );
    const collection = await (ApiKeyCollection as any).create(this.options);
    return await collection.findByProfile(this.id as string);
  }

  /**
   * Get active (non-revoked, non-expired) API keys for this profile
   *
   * @returns Array of active API keys
   */
  async getActiveApiKeys(): Promise<any[]> {
    const { ApiKeyCollection } = await import(
      '../collections/ApiKeyCollection'
    );
    const collection = await (ApiKeyCollection as any).create(this.options);
    return await collection.findActiveByProfile(this.id as string);
  }

  /**
   * Generate a new API key for this profile
   *
   * @param options - Key options (name, scopes, expiration)
   * @returns The generated key (plaintext) and ApiKey record
   */
  async generateApiKey(options: {
    name: string;
    scopes?: string[];
    expiresAt?: Date | null;
  }): Promise<{ key: string; apiKey: any }> {
    const { ApiKey } = await import('./ApiKey');
    return await ApiKey.generate(this, {
      ...options,
      db: this.options?.db,
    });
  }

  /**
   * Get all OIDC identities linked to this profile
   *
   * @returns Array of OIDC identity records
   */
  async getOidcIdentities(): Promise<any[]> {
    const { OidcIdentityCollection } = await import(
      '../collections/OidcIdentityCollection'
    );
    const collection = await (OidcIdentityCollection as any).create(
      this.options,
    );
    return await collection.findByProfile(this.id as string);
  }

  /**
   * Link a new OIDC identity to this profile
   *
   * @param oidcData - OIDC provider data
   * @returns The linked OIDC identity record
   */
  async linkOidcIdentity(oidcData: {
    provider: string;
    issuer: string;
    subject: string;
    email?: string;
  }): Promise<any> {
    const { OidcIdentityCollection } = await import(
      '../collections/OidcIdentityCollection'
    );
    const collection = await (OidcIdentityCollection as any).create(
      this.options,
    );
    return await collection.linkToProfile(this, oidcData);
  }

  /**
   * Get all Nostr identities linked to this profile
   *
   * @returns Array of Nostr identity records
   */
  async getNostrIdentities(): Promise<any[]> {
    const { NostrIdentityCollection } = await import(
      '../collections/NostrIdentityCollection'
    );
    const collection = await (NostrIdentityCollection as any).create(
      this.options,
    );
    return await collection.findByProfile(this.id as string);
  }

  /**
   * Link a new Nostr identity to this profile
   *
   * @param nostrData - Nostr identity data (encrypted keypair)
   * @returns The linked Nostr identity record
   */
  async linkNostrIdentity(nostrData: {
    pubkey: string;
    encryptedPrivkey: string;
    encryptionIv: string;
    encryptionTag: string;
    email: string;
    nip05Username?: string;
  }): Promise<any> {
    const { NostrIdentityCollection } = await import(
      '../collections/NostrIdentityCollection'
    );
    const collection = await (NostrIdentityCollection as any).create(
      this.options,
    );
    return await collection.linkToProfile(this, nostrData);
  }

  /**
   * Get audit logs for actions performed by this profile
   *
   * @param limit - Maximum number of logs to return
   * @returns Array of audit log entries
   */
  async getAuditLogs(limit: number = 50): Promise<any[]> {
    const { AuditLogCollection } = await import(
      '../collections/AuditLogCollection'
    );
    const collection = await (AuditLogCollection as any).create(this.options);
    return await collection.getRecentActivity(this.id as string, limit);
  }

  /**
   * Record an audit log entry for an action by this profile
   *
   * @param options - Audit log options
   * @returns The created audit log entry
   */
  async recordAction(options: {
    action: string;
    resourceType: string;
    resourceId: string;
    source?: 'web' | 'cli' | 'ci' | 'webhook' | 'mcp';
    metadata?: Record<string, any>;
    onBehalfOf?: Profile | null;
  }): Promise<any> {
    const { AuditLogCollection } = await import(
      '../collections/AuditLogCollection'
    );
    const collection = await (AuditLogCollection as any).create(this.options);
    return await collection.record({
      profile: this,
      ...options,
    });
  }
}
