/**
 * ProfileRelationship model - Connects two profiles with a relationship type
 *
 * Represents directional or reciprocal relationships between profiles.
 * Uses UUID primary key with foreign keys to profiles and relationship type.
 */

import {
  foreignKey,
  oneToMany,
  SmrtObject,
  type SmrtObjectOptions,
  smrt,
} from '@happyvertical/smrt-core';
import { TenantScoped, tenantId } from '@happyvertical/smrt-tenancy';
import type { ProfileRelationshipTerm } from './ProfileRelationshipTerm';

export interface ProfileRelationshipOptions extends SmrtObjectOptions {
  fromProfileId?: string;
  toProfileId?: string;
  typeId?: string;
  contextProfileId?: string;
  tenantId?: string | null;
}

@TenantScoped({ mode: 'optional' })
@smrt({
  tableStrategy: 'sti',
  api: { include: ['list', 'get', 'create', 'delete'] },
  mcp: { include: ['list', 'get'] },
  cli: true,
})
export class ProfileRelationship extends SmrtObject {
  @tenantId({ nullable: true })
  tenantId: string | null = null;

  // id: UUID (auto-generated by SmrtObject)
  @foreignKey('Profile', { required: true })
  fromProfileId?: string; // Origin profile

  @foreignKey('Profile', { required: true })
  toProfileId?: string; // Target profile

  @foreignKey('ProfileRelationshipType', { required: true })
  typeId?: string; // Relationship type

  @foreignKey('Profile')
  contextProfileId?: string; // Optional tertiary context

  // Relationships
  @oneToMany('ProfileRelationshipTerm')
  terms: ProfileRelationshipTerm[] = [];

  constructor(options: ProfileRelationshipOptions = {}) {
    super(options);
    if (options.fromProfileId !== undefined)
      this.fromProfileId = options.fromProfileId;
    if (options.toProfileId !== undefined)
      this.toProfileId = options.toProfileId;
    if (options.typeId !== undefined) this.typeId = options.typeId;
    if (options.contextProfileId !== undefined)
      this.contextProfileId = options.contextProfileId;
  }

  /**
   * Get the relationship type slug
   *
   * @returns The slug of the relationship type
   */
  async getTypeSlug(): Promise<string> {
    const type = await this.loadRelated('typeId');
    return type?.slug || '';
  }

  /**
   * Add a term (time period) to this relationship
   *
   * @param startedAt - Start date of the term
   * @param endedAt - Optional end date of the term
   */
  async addTerm(startedAt: Date, endedAt?: Date): Promise<void> {
    if (!this.id) {
      throw new Error(
        'ProfileRelationship.addTerm requires a persisted relationship (missing id)',
      );
    }
    const relationshipId = this.id;

    const { ProfileRelationshipTermCollection } = await import(
      '../collections/ProfileRelationshipTermCollection'
    );

    const termCollection = await ProfileRelationshipTermCollection.create(
      this.options,
    );

    const term = await termCollection.create({
      relationshipId,
      startedAt,
      endedAt,
    });

    await term.save();
  }

  /**
   * End the current active term
   *
   * @param endedAt - End date for the term
   */
  async endCurrentTerm(endedAt: Date): Promise<void> {
    const activeTerm = await this.getActiveTerm();
    if (activeTerm) {
      await activeTerm.end(endedAt);
    }
  }

  /**
   * Get all terms for this relationship
   *
   * @returns Array of ProfileRelationshipTerm instances
   */
  async getTerms(): Promise<ProfileRelationshipTerm[]> {
    const { ProfileRelationshipTermCollection } = await import(
      '../collections/ProfileRelationshipTermCollection'
    );

    const termCollection = await ProfileRelationshipTermCollection.create(
      this.options,
    );

    return await termCollection.getByRelationship(this.id as string);
  }

  /**
   * Get the active term (no end date)
   *
   * @returns Current term or null if none active
   */
  async getActiveTerm(): Promise<ProfileRelationshipTerm | null> {
    const { ProfileRelationshipTermCollection } = await import(
      '../collections/ProfileRelationshipTermCollection'
    );

    const termCollection = await ProfileRelationshipTermCollection.create(
      this.options,
    );

    return await termCollection.getActiveTerm(this.id as string);
  }
}
