/**
 * ProfileRelationshipType model - Lookup table for relationship types
 *
 * Defines the kinds of relationships that can exist between profiles.
 * Uses UUID primary key with unique slug for human-readable lookups.
 */

import {
  field,
  SmrtObject,
  type SmrtObjectOptions,
  smrt,
} from '@happyvertical/smrt-core';
import type { ReciprocalHandler } from '../types';

export interface ProfileRelationshipTypeOptions extends SmrtObjectOptions {
  slug?: string;
  name?: string;
  reciprocal?: boolean;
}

/**
 * Extend globalThis to include reciprocal handlers registry.
 * Using globalThis ensures all module instances share the same handlers,
 * which is critical in monorepos where the same package can be loaded
 * from different paths (e.g., pnpm store vs workspace symlink).
 *
 * @see https://github.com/happyvertical/smrt/issues/543
 */
declare global {
  // eslint-disable-next-line no-var
  var __smrtProfileRelationshipHandlers:
    | Map<string, ReciprocalHandler>
    | undefined;
  // eslint-disable-next-line no-var
  var __smrtProfileRelationshipHandlersInitialized: boolean | undefined;
}

/**
 * Get the reciprocal handlers Map from globalThis
 */
function getReciprocalHandlers(): Map<string, ReciprocalHandler> {
  if (!globalThis.__smrtProfileRelationshipHandlers) {
    globalThis.__smrtProfileRelationshipHandlers = new Map<
      string,
      ReciprocalHandler
    >();
  }
  return globalThis.__smrtProfileRelationshipHandlers;
}

/**
 * Default handlers for common reciprocal relationship patterns
 */
const DEFAULT_HANDLERS: Record<string, ReciprocalHandler> = {
  // Symmetric relationships (same type in both directions)
  friend: async (from, to, context) => {
    await to.addRelationship(from, 'friend', context);
  },

  spouse: async (from, to) => {
    await to.addRelationship(from, 'spouse');
  },

  partner: async (from, to, context) => {
    await to.addRelationship(from, 'partner', context);
  },

  colleague: async (from, to, context) => {
    await to.addRelationship(from, 'colleague', context);
  },

  sibling: async (from, to) => {
    await to.addRelationship(from, 'sibling');
  },
};

// Register default handlers (only once across all module instances)
if (!globalThis.__smrtProfileRelationshipHandlersInitialized) {
  globalThis.__smrtProfileRelationshipHandlersInitialized = true;
  for (const [slug, handler] of Object.entries(DEFAULT_HANDLERS)) {
    getReciprocalHandlers().set(slug, handler);
  }
}

@smrt({
  tableStrategy: 'sti',
  api: { include: ['list', 'get', 'create', 'update'] },
  mcp: { include: ['list', 'get'] },
  cli: true,
})
export class ProfileRelationshipType extends SmrtObject {
  // id: UUID (auto-generated by SmrtObject)
  // slug is inherited from SmrtObject (auto-generated from name)
  @field({ required: true })
  name: string = '';

  reciprocal: boolean = true; // True for two-way relationships

  constructor(options: ProfileRelationshipTypeOptions = {}) {
    super(options);
    if (options.name) this.name = options.name;
    if (options.reciprocal !== undefined) this.reciprocal = options.reciprocal;
  }

  /**
   * Convenience method for slug-based lookup
   *
   * @param slug - The slug to search for
   * @returns ProfileRelationshipType instance or null if not found
   */
  static async getBySlug(
    _slug: string,
  ): Promise<ProfileRelationshipType | null> {
    // Will be auto-implemented by SMRT
    return null;
  }

  /**
   * Register a custom reciprocal handler for a relationship type
   *
   * @param slug - The relationship type slug
   * @param handler - The handler function to execute when creating reciprocal relationship
   */
  static registerReciprocalHandler(
    slug: string,
    handler: ReciprocalHandler,
  ): void {
    getReciprocalHandlers().set(slug, handler);
  }

  /**
   * Get the reciprocal handler for a relationship type
   *
   * @param slug - The relationship type slug
   * @returns The handler function or undefined
   */
  static getReciprocalHandler(slug: string): ReciprocalHandler | undefined {
    return getReciprocalHandlers().get(slug);
  }

  /**
   * Check if a relationship type is reciprocal
   *
   * @param slug - The relationship type slug
   * @returns True if reciprocal, false otherwise
   */
  static async isReciprocal(slug: string): Promise<boolean> {
    const type = await ProfileRelationshipType.getBySlug(slug);
    return type?.reciprocal || false;
  }
}
