/**
 * SMRT Configuration
 *
 * This file configures the SMRT framework for your project.
 * See: https://github.com/happyvertical/smrt
 */

const profile = (process.env.SMRT_RUNTIME_PROFILE || 'local') as
  | 'local'
  | 'self-hosted'
  | 'cloud';

export default {
  // This is the single infrastructure selector for the application. Domain
  // objects and generated REST/CLI/MCP/WebMCP surfaces do not branch on it.
  runtime: {
    profile,
  },

  // SMRT packages whose object manifests this app consumes. Keeping the list
  // explicit avoids treating tooling/UI packages as domain model providers
  // and makes generated runtime registration deterministic.
  consumer: {
    packages: [
      '@happyvertical/smrt-profiles',
      '@happyvertical/smrt-tenancy',
      '@happyvertical/smrt-users',
    ],
  },

  // Agent/developer knowledge artifacts are generated by the smrt() Vite plugin.
  // HTTP API routes stay off unless explicitly enabled for a dev/admin-only workflow.
  knowledge: {
    enabled: true,
    api: {
      enabled: false,
      basePath: '/__smrt/knowledge',
      requireAdmin: true,
      includeDocs: false,
      includePrompts: false,
    },
  },

  // No `packages.cli.database`: `smrt app setup` / `smrt app migrate` hand
  // `smrt db:migrate` the profile-owned database through DATABASE_URL and
  // DATABASE_TYPE (local: the SQLite file in the user data root; deployed: the
  // operator's URL). See the smrt-cli README for the precedence.
};
