#!/usr/bin/env node
/**
 * CI-safe structural validation for the smrt-mobile KMP module (ADR 0001,
 * CI lane (a)). Checks file layout and load-bearing content patterns WITHOUT
 * requiring a JDK, the Android SDK, or Xcode — the real Gradle compile+test
 * lane is .github/workflows/mobile.yml (lane (b), path-filtered).
 *
 * Ported from amaru's scripts/validate-mobile-shell.mjs and rescoped to the
 * library layout (single-module KMP, no androidApp/iosApp here).
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');

const KOTLIN_ROOT = 'src/commonMain/kotlin/com/happyvertical/smrt/mobile';
const TEST_ROOT = 'src/commonTest/kotlin/com/happyvertical/smrt/mobile';

const REQUIRED_FILES = [
  'package.json',
  'AGENTS.md',
  'CLAUDE.md',
  'README.md',
  'settings.gradle.kts',
  'build.gradle.kts',
  'gradle.properties',
  'gradle/libs.versions.toml',
  'gradlew',
  'gradlew.bat',
  'gradle/wrapper/gradle-wrapper.jar',
  'gradle/wrapper/gradle-wrapper.properties',
  `${KOTLIN_ROOT}/contract/SupportTypes.kt`,
  `${KOTLIN_ROOT}/contract/PackLocalization.kt`,
  `${KOTLIN_ROOT}/contract/MobileAuthContract.kt`,
  `${KOTLIN_ROOT}/contract/MobileDeviceContract.kt`,
  `${KOTLIN_ROOT}/contract/MobileContractInfo.kt`,
  `${KOTLIN_ROOT}/i18n/PackTextResolver.kt`,
  `${KOTLIN_ROOT}/packs/PackIntegrity.kt`,
  `${KOTLIN_ROOT}/evidence/EvidenceCapture.kt`,
  `${KOTLIN_ROOT}/shell/MobileShell.kt`,
  `${KOTLIN_ROOT}/platform/Hashing.kt`,
  `${TEST_ROOT}/i18n/PackTextResolverTest.kt`,
  `${TEST_ROOT}/packs/PackIntegrityCheckTest.kt`,
  `${TEST_ROOT}/shell/MobileShellStateTest.kt`,
  `${TEST_ROOT}/evidence/EvidenceCaptureTest.kt`,
];

// file → substrings that must all be present.
const CONTENT_CHECKS = {
  'settings.gradle.kts': ['rootProject.name = "smrt-mobile"'],
  'build.gradle.kts': [
    'androidTarget()',
    'jvm()',
    'iosArm64()',
    'iosSimulatorArm64()',
    'baseName = "SmrtMobile"',
    'jvmToolchain(21)',
    'namespace = "com.happyvertical.smrt.mobile"',
  ],
  'gradle.properties': ['android.useAndroidX=true'],
  'gradle/libs.versions.toml': ['agp = ', 'kotlin = ', 'kotlinx-serialization'],
  'gradle/wrapper/gradle-wrapper.properties': ['gradle-8.14.4-bin.zip'],
  'package.json': ['"@happyvertical/smrt-mobile"', '"private": true'],
  [`${KOTLIN_ROOT}/contract/SupportTypes.kt`]: [
    'Generated by @happyvertical/smrt-mobile-contract',
    'typealias DecimalString = String',
  ],
  [`${KOTLIN_ROOT}/contract/PackLocalization.kt`]: [
    'data class PackLanguage(',
    'data class PackLanguageBundle(',
    'data class PackTextSourceRef(',
  ],
  [`${KOTLIN_ROOT}/contract/MobileAuthContract.kt`]: [
    'data class MobileAuthStartRequest(',
    'data class MobileAuthCompleteRequest(',
    'data class MobileAuthSession(',
    'data class MobileSessionBootstrap(',
  ],
  [`${KOTLIN_ROOT}/i18n/PackTextResolver.kt`]: [
    'class PackTextResolver(',
    'fun resolve(key: String',
  ],
  [`${KOTLIN_ROOT}/packs/PackIntegrity.kt`]: [
    'class PackIntegrityCheck',
    'fun verifyManifestHash(',
  ],
  [`${KOTLIN_ROOT}/evidence/EvidenceCapture.kt`]: [
    'interface EvidenceCapturePlatformAdapter',
    'data class EvidenceLocationMetadata(',
  ],
  [`${KOTLIN_ROOT}/shell/MobileShell.kt`]: ['data class MobileShellState('],
};

const failures = [];

for (const relPath of REQUIRED_FILES) {
  if (!existsSync(join(PKG, relPath))) {
    failures.push(`missing required file: ${relPath}`);
  }
}

for (const [relPath, patterns] of Object.entries(CONTENT_CHECKS)) {
  const absPath = join(PKG, relPath);
  if (!existsSync(absPath)) continue; // already reported above
  const content = readFileSync(absPath, 'utf8');
  for (const pattern of patterns) {
    if (!content.includes(pattern)) {
      failures.push(`${relPath}: missing expected content ${JSON.stringify(pattern)}`);
    }
  }
}

// Every commonMain source must live in the library namespace.
for (const relPath of REQUIRED_FILES) {
  if (!relPath.startsWith(KOTLIN_ROOT) || !relPath.endsWith('.kt')) continue;
  const absPath = join(PKG, relPath);
  if (!existsSync(absPath)) continue;
  const content = readFileSync(absPath, 'utf8');
  if (!content.includes('package com.happyvertical.smrt.mobile')) {
    failures.push(`${relPath}: not in the com.happyvertical.smrt.mobile namespace`);
  }
}

if (failures.length > 0) {
  console.error(`✗ smrt-mobile shell validation failed (${failures.length} issue(s)):`);
  for (const failure of failures) {
    console.error(`  - ${failure}`);
  }
  process.exit(1);
}

console.log(
  `✓ smrt-mobile shell validation passed (${REQUIRED_FILES.length} files, ` +
    `${Object.keys(CONTENT_CHECKS).length} content checks).`,
);
