#!/usr/bin/env node
/**
 * CI-safe structural validation for the smrt-mobile KMP module (ADR 0001,
 * CI lane (a)). Checks file layout and load-bearing content patterns WITHOUT
 * requiring a JDK, the Android SDK, or Xcode — the real Gradle compile+test
 * lane is .github/workflows/mobile.yml (lane (b), path-filtered).
 *
 * Generated contract files are pinned for provenance (header + namespace)
 * only — their exact bytes are owned and byte-verified by
 * @happyvertical/smrt-mobile-contract's build, so shape substrings are not
 * duplicated here.
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');

const KOTLIN_ROOT = 'src/commonMain/kotlin/com/happyvertical/smrt/mobile';
const IOS_ROOT = 'src/iosMain/kotlin/com/happyvertical/smrt/mobile';
const TEST_ROOT = 'src/commonTest/kotlin/com/happyvertical/smrt/mobile';
const JVM_TEST_ROOT = 'src/jvmTest/kotlin/com/happyvertical/smrt/mobile';
const SQL_ROOT = 'src/commonMain/sqldelight/com/happyvertical/smrt/mobile/db';
const GENERATED_HEADER = 'Generated by @happyvertical/smrt-mobile-contract';
const NAMESPACE = 'package com.happyvertical.smrt.mobile';

const GENERATED_CONTRACT_FILES = [
  'SupportTypes.kt',
  'PackLocalization.kt',
  'MobileAuthContract.kt',
  'MobileDeviceContract.kt',
  'MobileContractInfo.kt',
];

// One entry per required file; `mustContain` lists load-bearing substrings.
// Kotlin sources under KOTLIN_ROOT additionally get the namespace check.
const SPEC = [
  {
    path: 'package.json',
    mustContain: ['"@happyvertical/smrt-mobile"', '"private": true'],
  },
  { path: 'AGENTS.md' },
  { path: 'CLAUDE.md' },
  { path: 'README.md' },
  {
    path: 'settings.gradle.kts',
    mustContain: ['rootProject.name = "smrt-mobile"'],
  },
  {
    path: 'build.gradle.kts',
    mustContain: [
      'alias(libs.plugins.androidKmpLibrary)',
      'android {',
      'jvm()',
      'iosArm64()',
      'iosSimulatorArm64()',
      'baseName = "SmrtMobile"',
      'jvmToolchain(21)',
      'namespace = "com.happyvertical.smrt.mobile"',
      'alias(libs.plugins.sqldelight)',
      'create("SmrtMobileDatabase")',
    ],
  },
  { path: 'gradle.properties', mustContain: ['android.useAndroidX=true'] },
  {
    path: 'gradle/libs.versions.toml',
    mustContain: ['agp = ', 'kotlin = ', 'kotlinx-serialization', 'sqldelight = '],
  },
  { path: 'gradlew' },
  { path: 'gradlew.bat' },
  { path: 'gradle/wrapper/gradle-wrapper.jar' },
  {
    path: 'gradle/wrapper/gradle-wrapper.properties',
    mustContain: ['services.gradle.org/distributions/gradle-'],
  },
  ...GENERATED_CONTRACT_FILES.map((name) => ({
    path: `${KOTLIN_ROOT}/contract/${name}`,
    mustContain: [GENERATED_HEADER],
  })),
  {
    path: `${KOTLIN_ROOT}/auth/AuthSeams.kt`,
    mustContain: [
      'interface AuthStorage',
      'interface AuthTransport',
      'fun interface ExternalAuthLauncher',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/auth/MobileSessionManager.kt`,
    mustContain: [
      'class MobileSessionManager(',
      'suspend fun beginSignIn(',
      'suspend fun handleRedirect(',
      'suspend fun onUnauthorized()',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/network/MobileApiClient.kt`,
    mustContain: [
      'class MobileApiClient(',
      'suspend fun submitMultipart(',
      'Idempotency-Key',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/network/HttpQueueSender.kt`,
    mustContain: ['class HttpQueueSender(', 'SendOutcome.Unauthorized'],
  },
  {
    path: `${KOTLIN_ROOT}/i18n/PackTextResolver.kt`,
    mustContain: ['class PackTextResolver(', 'fun resolve(key: String'],
  },
  {
    path: `${KOTLIN_ROOT}/packs/PackIntegrity.kt`,
    mustContain: ['class PackIntegrityCheck', 'fun verifyManifestHash('],
  },
  {
    path: `${KOTLIN_ROOT}/packs/OfflinePackStore.kt`,
    mustContain: ['interface OfflinePackStore', 'class DurableOfflinePackStore('],
  },
  {
    path: `${KOTLIN_ROOT}/sync/DurableWriteQueue.kt`,
    mustContain: [
      'class DurableWriteQueue(',
      'suspend fun flush(sender: QueueSender)',
      'recoverInterrupted',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/evidence/EvidenceCapture.kt`,
    mustContain: [
      'interface EvidenceCapturePlatformAdapter',
      'data class EvidenceLocationMetadata(',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/shell/MobileShell.kt`,
    mustContain: ['data class MobileShellState('],
  },
  {
    path: `${KOTLIN_ROOT}/platform/Hashing.kt`,
    mustContain: ['fun interface Sha256Hasher'],
  },
  {
    path: `${KOTLIN_ROOT}/platform/BarcodeScanning.kt`,
    mustContain: ['interface BarcodeScanner', 'data class BarcodeScan('],
  },
  {
    path: `${KOTLIN_ROOT}/platform/SpeechTranscription.kt`,
    mustContain: ['interface SpeechTranscriber', 'object SpeechErrorCode'],
  },
  {
    path: `${KOTLIN_ROOT}/platform/OnDeviceLanguageModel.kt`,
    mustContain: [
      'interface OnDeviceLanguageModel',
      'data class LanguageModelAvailability(',
    ],
  },
  {
    path: `${KOTLIN_ROOT}/platform/DeviceCapabilities.kt`,
    mustContain: ['fun interface DeviceCapabilityAdapter'],
  },
  // iOS platform factories the exported framework hands to Swift (Phase 6):
  // the durable store + Ktor client Swift cannot construct itself.
  {
    path: `${IOS_ROOT}/platform/SmrtMobileIos.kt`,
    mustContain: ['object SmrtMobileIos', 'NativeSqliteDriver', 'fun createDatabase('],
  },
  {
    path: `${SQL_ROOT}/QueueEntry.sq`,
    mustContain: ['CREATE TABLE queue_entry', 'recoverInterrupted:'],
  },
  {
    path: `${SQL_ROOT}/PackRecord.sq`,
    mustContain: ['CREATE TABLE pack_record'],
  },
  // Schema snapshot backing verifyMigrations — deleting it disables the
  // schema-evolution guardrail (see AGENTS.md § Schema changes).
  { path: 'src/commonMain/sqldelight/databases/1.db' },
  { path: `${TEST_ROOT}/auth/MobileSessionManagerTest.kt` },
  { path: `${TEST_ROOT}/network/MobileApiClientTest.kt` },
  { path: `${TEST_ROOT}/i18n/PackTextResolverTest.kt` },
  { path: `${TEST_ROOT}/packs/PackIntegrityCheckTest.kt` },
  { path: `${TEST_ROOT}/shell/MobileShellStateTest.kt` },
  { path: `${TEST_ROOT}/evidence/EvidenceCaptureTest.kt` },
  { path: `${TEST_ROOT}/platform/PlatformSeamsTest.kt` },
  { path: `${JVM_TEST_ROOT}/sync/DurableWriteQueueTest.kt` },
  { path: `${JVM_TEST_ROOT}/packs/DurableOfflinePackStoreTest.kt` },
  { path: `${JVM_TEST_ROOT}/network/QueueFlushIntegrationTest.kt` },
];

const failures = [];
let contentChecks = 0;

for (const { path, mustContain = [] } of SPEC) {
  const absPath = join(PKG, path);
  if (!existsSync(absPath)) {
    failures.push(`missing required file: ${path}`);
    continue;
  }

  const isKotlinSource = path.startsWith(KOTLIN_ROOT) && path.endsWith('.kt');
  if (mustContain.length === 0 && !isKotlinSource) continue;

  const content = readFileSync(absPath, 'utf8');
  for (const pattern of mustContain) {
    contentChecks++;
    if (!content.includes(pattern)) {
      failures.push(`${path}: missing expected content ${JSON.stringify(pattern)}`);
    }
  }
  if (isKotlinSource && !content.includes(NAMESPACE)) {
    failures.push(`${path}: not in the ${NAMESPACE} namespace`);
  }
}

if (failures.length > 0) {
  console.error(`✗ smrt-mobile shell validation failed (${failures.length} issue(s)):`);
  for (const failure of failures) {
    console.error(`  - ${failure}`);
  }
  process.exit(1);
}

console.log(
  `✓ smrt-mobile shell validation passed (${SPEC.length} files, ` +
    `${contentChecks} content checks).`,
);
