import type {
  MobileContract,
  MobileContractField,
  MobileContractObject,
} from './types.js';

export const GENERATED_HEADER = [
  '// Generated by @happyvertical/smrt-mobile-contract.',
  '// Do not edit by hand.',
  '',
].join('\n');

const FRAMEWORK_CONTRACT_PACKAGE = 'com.happyvertical.smrt.mobile.contract';

/**
 * Emits one Kotlin DTO file per allowlisted object, plus a
 * `MobileContractManifest.kt` recording the contract identity, all in the
 * consumer's Kotlin package. Framework support types (DecimalString, …) are
 * imported from `com.happyvertical.smrt.mobile.contract`.
 */
export function generateKotlinDtoFiles(
  contract: MobileContract,
): Map<string, string> {
  const files = new Map<string, string>();

  files.set('MobileContractManifest.kt', manifestFile(contract));
  for (const object of contract.objects) {
    files.set(`${object.dtoName}.kt`, dtoFile(contract, object));
  }

  return files;
}

function manifestFile(contract: MobileContract): string {
  return [
    GENERATED_HEADER,
    `package ${contract.kotlin.packageName}`,
    '',
    `const val MOBILE_CONTRACT_SCHEMA_VERSION: Int = ${contract.schemaVersion}`,
    `const val MOBILE_CONTRACT_VERSION: String = "${contract.contractVersion}"`,
    `const val MOBILE_CONTRACT_SOURCE_HASH: String = "${contract.sourceHash}"`,
    '',
    'val MOBILE_CONTRACT_OBJECTS: List<String> = listOf(',
    ...contract.objects.map((object) => `    "${object.name}",`),
    ')',
    '',
  ].join('\n');
}

function dtoFile(
  contract: MobileContract,
  object: MobileContractObject,
): string {
  const imports = new Set(['kotlinx.serialization.Serializable']);
  for (const field of object.fields) {
    if (field.kotlinType.includes('Instant')) {
      imports.add('kotlinx.datetime.Instant');
    }
    if (field.kotlinType.includes('JsonObject')) {
      imports.add('kotlinx.serialization.json.JsonObject');
    }
    if (field.kotlinType.includes('DecimalString')) {
      imports.add(`${FRAMEWORK_CONTRACT_PACKAGE}.DecimalString`);
    }
  }

  return [
    GENERATED_HEADER,
    `package ${contract.kotlin.packageName}`,
    '',
    ...[...imports].sort().map((importPath) => `import ${importPath}`),
    '',
    '@Serializable',
    `data class ${object.dtoName}(`,
    ...object.fields.map((field) => kotlinProperty(field)),
    ')',
    '',
  ].join('\n');
}

function kotlinProperty(field: MobileContractField): string {
  const defaultValue =
    field.kotlinDefault === null ? '' : ` = ${field.kotlinDefault}`;
  return `    val ${field.name}: ${field.kotlinType}${defaultValue},`;
}
