/**
 * Unit test for issue #131: External package manifest loading
 *
 * Tests the manifest loading mechanism that fixes the bug where only 8/17
 * columns were being created in the schema for external package classes.
 *
 * NOTE: Full integration tests with actual external packages are in:
 * - packages/places/src/__tests__/integration.test.ts
 * - packages/events/src/__tests__/integration.test.ts
 */

import { beforeEach, describe, expect, it } from 'vitest';
import {
  clearManifestCache,
  discoverManifestEntry,
  discoverManifestSync,
  getPackageName,
} from '../manifest/manifest-loader';
import { ObjectRegistry } from '../registry';

describe('Issue #131: External package manifest loading', () => {
  beforeEach(() => {
    // Clear registry and manifest cache before each test
    ObjectRegistry.clear();
    clearManifestCache();
  });

  describe('Manifest discovery mechanism', () => {
    it('should find manifests from testManifest synchronously', () => {
      // Test classes are in testManifest (generated by pretest script)
      const entry = discoverManifestSync('CollectionCreateTestProduct');

      // Should find test classes
      expect(entry).toBeDefined();
      if (entry) {
        expect(entry.className).toBe('CollectionCreateTestProduct');
        expect(entry.fields).toBeDefined();
      }
    });

    it('should return undefined for non-existent classes', () => {
      const entry = discoverManifestSync('NonExistentClass');
      expect(entry).toBeUndefined();
    });

    it('should handle case-insensitive lookups', () => {
      // Both lowercase and exact case should work
      const entry1 = discoverManifestSync('collectioncreatetestproduct');
      const entry2 = discoverManifestSync('CollectionCreateTestProduct');

      expect(entry1).toBeDefined();
      expect(entry2).toBeDefined();
      expect(entry1?.className).toBe(entry2?.className);
    });
  });

  describe('Package name extraction', () => {
    it('should extract package name from constructor metadata', () => {
      // Mock constructor with package metadata
      class MockClass {
        static __package__ = '@happyvertical/smrt-places';
      }

      const packageName = getPackageName(MockClass as any);
      expect(packageName).toBe('@happyvertical/smrt-places');
    });

    it('should return package name when available', () => {
      // Package name extraction uses multiple strategies:
      // 1. __package__ metadata (most reliable)
      // 2. Error stack trace parsing (for node_modules imports)
      // 3. Class name heuristics (fallback for known patterns)

      class Place {
        static __package__ = '@happyvertical/smrt-places';
      }

      const packageName = getPackageName(Place as any);
      // Should return the package name (from any strategy)
      expect(typeof packageName).toBe('string');
    });
  });

  describe('ObjectRegistry.ensureManifestLoaded()', () => {
    it('should throw error for unregistered class', async () => {
      await expect(
        ObjectRegistry.ensureManifestLoaded('NonExistentClass'),
      ).rejects.toThrow(/is not registered/);
    });

    it('should handle manifest loading flow', () => {
      // The manifest loading happens automatically during schema generation
      // This test documents the expected flow:

      // 1. Class is registered (via @smrt decorator)
      // 2. Initial registration may have empty fields (for external packages)
      // 3. When schema is generated, ensureManifestLoaded() is called
      // 4. Manifest is loaded dynamically from external package
      // 5. Fields are populated in the registry

      // This flow is tested end-to-end in the places/events packages
      expect(true).toBe(true); // Documentation test
    });
  });

  describe('Runtime introspection removal', () => {
    it('should no longer support primitive-only field detection', () => {
      // Before PR #129 and #131, this would work via runtime introspection
      // Now it should require a manifest

      class PrimitiveOnlyClass {
        name = '';
        age = 0;
      }

      // Register the class - should NOT detect fields from primitives
      ObjectRegistry.register(PrimitiveOnlyClass as any, {});

      const fields = ObjectRegistry.getFields('PrimitiveOnlyClass');

      // Should have 0 fields (no manifest, no Field helpers)
      expect(fields.size).toBe(0);
    });
  });

  describe('Documentation for integration testing', () => {
    it('documents where full integration tests live', () => {
      // This test serves as documentation
      const integrationTestLocations = [
        'packages/places/src/__tests__/integration.test.ts',
        'packages/events/src/__tests__/integration.test.ts',
      ];

      // These files test the full flow:
      // 1. External package builds manifest
      // 2. Core package loads manifest dynamically
      // 3. Schema generation includes all fields
      // 4. Database table has all columns

      expect(integrationTestLocations.length).toBeGreaterThan(0);
    });
  });
});
