import { randomUUID } from 'node:crypto';
import type { DatabaseInterface } from '@happyvertical/sql';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  appendChange,
  drainChangeFeed,
  ensureChangeFeedTable,
} from '../change-feed.js';
import { resolveDatabase } from '../database.js';
import { MigrationTracker } from '../migrations/tracker.js';
import {
  applyPostgresPermissions,
  type PostgresPermissionContract,
  planPostgresPermissions,
} from '../postgres-permissions.js';

const pgUrl = process.env.SMRT_TEST_POSTGRES_URL;
const pgDescribe = pgUrl ? describe.sequential : describe.skip;
const rolePassword = 'smrt-test-password';

pgDescribe('PostgreSQL permission contract (#2701)', () => {
  let admin: DatabaseInterface;
  let db: DatabaseInterface;
  let database: string;
  let owner: string;
  let runtime: string;
  let monitor: string;
  let contract: PostgresPermissionContract;
  const q = (value: string) => `"${value.replaceAll('"', '""')}"`;
  async function as(role: string, sql: string) {
    return db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(role)}`);
      return tx.query(sql);
    });
  }
  async function apply() {
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
    return applyPostgresPermissions(db, contract, {
      expectedFingerprint: plan.fingerprint,
    });
  }
  beforeEach(async () => {
    const suffix = randomUUID().replaceAll('-', '').slice(0, 12);
    database = `perm2701_${suffix}`;
    owner = `own_${suffix}`;
    runtime = `run_${suffix}`;
    monitor = `mon_${suffix}`;
    admin = await resolveDatabase(
      { type: 'postgres', url: pgUrl! },
      { dbid: `admin-${suffix}` },
    );
    for (const role of [owner, runtime, monitor])
      await admin.query(
        `CREATE ROLE ${q(role)} LOGIN PASSWORD '${rolePassword}'`,
      );
    await admin.query(`CREATE DATABASE ${q(database)} OWNER ${q(owner)}`);
    const url = new URL(pgUrl!);
    url.pathname = `/${database}`;
    db = await resolveDatabase(
      { type: 'postgres', url: url.toString() },
      { dbid: database },
    );
    await db.query(`REVOKE TEMPORARY ON DATABASE ${q(database)} FROM PUBLIC`);
    // PostgreSQL 14 grants PUBLIC CREATE here by default. Infrastructure must
    // remove that unrelated schema authority before the app contract can pass.
    await db.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
    await db.query(`CREATE SCHEMA app AUTHORIZATION ${q(owner)}`);
    await as(
      owner,
      'CREATE TABLE app.items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, visible text, secret text)',
    );
    for (const table of [
      '_smrt_migrations',
      '_smrt_schema_migrations',
      '_smrt_backfills',
    ]) {
      await as(owner, `CREATE TABLE app.${q(table)} (id text)`);
    }
    contract = {
      schema: 'app',
      schemaExclusive: true,
      migrationOwner: owner,
      runtimeRole: runtime,
      managedTables: ['items'],
      managedTriggerFunctions: [],
      monitor: { role: monitor, tables: { items: ['id', 'visible'] } },
    };
  });
  afterEach(async () => {
    await db?.close();
    if (database)
      await admin.query(`DROP DATABASE IF EXISTS ${q(database)} WITH (FORCE)`);
    for (const role of [owner, runtime, monitor])
      if (role) await admin.query(`DROP ROLE IF EXISTS ${q(role)}`);
    await admin?.close();
  });
  it('establishes actual runtime operations and column-only monitoring, excluding DDL and bookkeeping writes', async () => {
    const result = await apply();
    expect(result.diagnostics).toEqual([]);
    expect(result.statements).toEqual([]);
    await as(
      runtime,
      "INSERT INTO app.items(visible,secret) VALUES ('hello','private')",
    );
    await as(runtime, "UPDATE app.items SET visible='world' WHERE id=1");
    expect(
      (await as(monitor, 'SELECT id,visible FROM app.items')).rows,
    ).toHaveLength(1);
    await expect(as(monitor, 'SELECT secret FROM app.items')).rejects.toThrow();
    await expect(
      as(monitor, "UPDATE app.items SET visible='no' WHERE id=1"),
    ).rejects.toThrow();
    await expect(
      as(runtime, 'CREATE TABLE app.forbidden(id int)'),
    ).rejects.toThrow();
    await expect(
      as(runtime, 'CREATE TEMP TABLE forbidden(id int)'),
    ).rejects.toThrow();
    await expect(as(runtime, 'TRUNCATE app.items')).rejects.toThrow();
    await expect(
      as(runtime, "INSERT INTO app._smrt_schema_migrations VALUES ('fake')"),
    ).rejects.toThrow();
    await as(runtime, 'DELETE FROM app.items WHERE id=1');
  });
  it('reconciles canonical change-feed routines and executes them as runtime', async () => {
    await db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(owner)}`);
      await tx.query('SET LOCAL search_path TO app');
      await ensureChangeFeedTable(tx);
    });
    const before = await planPostgresPermissions(db, contract);
    expect(before.canApply, JSON.stringify(before.diagnostics)).toBe(true);
    expect(
      before.diagnostics.some(
        (entry) =>
          entry.code === 'missing-routine-privilege' &&
          entry.role === runtime &&
          entry.resource.includes('_smrt_append_change'),
      ),
    ).toBe(true);
    await applyPostgresPermissions(db, contract, {
      expectedFingerprint: before.fingerprint,
    });
    const runtimeUrl = new URL(pgUrl!);
    runtimeUrl.pathname = `/${database}`;
    runtimeUrl.username = runtime;
    runtimeUrl.password = rolePassword;
    const runtimeDb = await resolveDatabase(
      { type: 'postgres', url: runtimeUrl.toString() },
      { dbid: `${database}-${runtime}-change-feed` },
    );
    try {
      await runtimeDb.query('SET search_path TO app');
      const seq = await appendChange(runtimeDb, {
        table: 'items',
        rowId: 'runtime-change',
        operation: 'update',
      });
      expect(seq).not.toBeNull();
      await drainChangeFeed(runtimeDb);
      await expect(
        runtimeDb.query(
          'CREATE TABLE app.runtime_changefeed_forbidden(id int)',
        ),
      ).rejects.toThrow();
    } finally {
      await runtimeDb.close();
    }
    await expect(
      as(monitor, 'SELECT * FROM app._smrt_drain_changes()'),
    ).rejects.toThrow();
    expect(
      (
        await as(
          monitor,
          "SELECT has_function_privilege(current_user, 'app._smrt_append_change(text,text,text,text,timestamp with time zone)', 'EXECUTE') AS allowed",
        )
      ).rows[0]?.allowed,
    ).toBe(false);
  });
  it('supports declared invoker trigger routines without direct EXECUTE', async () => {
    contract.managedTriggerFunctions = ['integrity_guard'];
    await as(
      owner,
      `CREATE FUNCTION app.integrity_guard() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER AS $$
        BEGIN
          IF NEW.visible = 'forbidden' THEN RAISE EXCEPTION 'integrity guard'; END IF;
          RETURN NEW;
        END;
      $$`,
    );
    await as(
      owner,
      'CREATE TRIGGER integrity_guard BEFORE INSERT ON app.items FOR EACH ROW EXECUTE FUNCTION app.integrity_guard()',
    );
    await apply();
    await as(
      owner,
      'ALTER TABLE app.items ENABLE ALWAYS TRIGGER integrity_guard',
    );
    await apply();
    expect(
      (
        await as(
          runtime,
          "SELECT has_function_privilege(current_user, 'app.integrity_guard()', 'EXECUTE') AS allowed",
        )
      ).rows[0]?.allowed,
    ).toBe(false);
    await as(
      runtime,
      "INSERT INTO app.items(visible,secret) VALUES ('allowed','private')",
    );
    await expect(
      as(
        runtime,
        "INSERT INTO app.items(visible,secret) VALUES ('forbidden','private')",
      ),
    ).rejects.toThrow('integrity guard');
    expect(
      (
        await as(
          monitor,
          "SELECT has_function_privilege(current_user, 'app.integrity_guard()', 'EXECUTE') AS allowed",
        )
      ).rows[0]?.allowed,
    ).toBe(false);
  });
  it('rejects a stale plan after a canonical framework routine definition changes', async () => {
    await db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(owner)}`);
      await tx.query('SET LOCAL search_path TO app');
      await ensureChangeFeedTable(tx);
    });
    const before = await planPostgresPermissions(db, contract);
    expect(before.canApply, JSON.stringify(before.diagnostics)).toBe(true);
    await as(
      owner,
      `CREATE OR REPLACE FUNCTION app._smrt_append_change(
        p_table_name TEXT, p_row_id TEXT, p_operation TEXT, p_tenant_id TEXT, p_created_at TIMESTAMPTZ
      ) RETURNS TABLE(allocated_seq BIGINT, error_code TEXT, error_message TEXT)
      LANGUAGE plpgsql SECURITY INVOKER AS $$ BEGIN RETURN; END $$`,
    );
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: before.fingerprint,
      }),
    ).rejects.toThrow('stale');
    expect((await planPostgresPermissions(db, contract)).canApply).toBe(false);
  });
  it('rejects canonical framework routines with changed execution properties', async () => {
    await db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(owner)}`);
      await tx.query('SET LOCAL search_path TO app');
      await ensureChangeFeedTable(tx);
    });
    await as(
      owner,
      'ALTER FUNCTION app._smrt_append_change(text,text,text,text,timestamp with time zone) COST 101',
    );
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'framework-routine-definition' }),
    );
  });
  it('rejects SECURITY DEFINER canonical framework routines', async () => {
    await db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(owner)}`);
      await tx.query('SET LOCAL search_path TO app');
      await ensureChangeFeedTable(tx);
    });
    await as(
      owner,
      'ALTER FUNCTION app._smrt_append_change(text,text,text,text,timestamp with time zone) SECURITY DEFINER',
    );
    await as(
      owner,
      'ALTER FUNCTION app._smrt_drain_changes(integer) SECURITY DEFINER',
    );
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(
      plan.diagnostics.filter(
        (entry) => entry.code === 'framework-routine-definition',
      ),
    ).toHaveLength(2);
  });
  it('rejects overloads beside canonical framework routines', async () => {
    await db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(owner)}`);
      await tx.query('SET LOCAL search_path TO app');
      await ensureChangeFeedTable(tx);
    });
    await as(
      owner,
      'CREATE FUNCTION app._smrt_append_change(p_extra text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END $$',
    );
    await as(
      owner,
      'CREATE FUNCTION app._smrt_drain_changes(p_extra text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN END $$',
    );
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    for (const name of ['_smrt_append_change', '_smrt_drain_changes'])
      expect(plan.diagnostics).toContainEqual(
        expect.objectContaining({
          code: 'unsupported-routines',
          resource: `"app"."${name}"`,
        }),
      );
  });
  it('rejects configured trigger routines when their security or binding contract changes', async () => {
    contract.managedTriggerFunctions = ['integrity_guard'];
    await as(
      owner,
      'CREATE FUNCTION app.integrity_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$ BEGIN RETURN NEW; END $$',
    );
    await as(
      owner,
      'CREATE TRIGGER integrity_guard BEFORE INSERT ON app.items FOR EACH ROW EXECUTE FUNCTION app.integrity_guard()',
    );
    const result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some(
        (entry) =>
          entry.code === 'unsupported-routines' &&
          entry.resource === '"app"."integrity_guard"',
      ),
    ).toBe(true);
  });
  it('rejects declared trigger functions without an enabled managed-table-only binding', async () => {
    contract.managedTriggerFunctions = ['integrity_guard'];
    await as(
      owner,
      'CREATE FUNCTION app.integrity_guard() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER AS $$ BEGIN RETURN NEW; END $$',
    );
    let result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some(
        (entry) => entry.code === 'missing-managed-trigger-function',
      ),
    ).toBe(true);
    await as(owner, 'CREATE SCHEMA other');
    await as(owner, 'CREATE TABLE other.unmanaged(id integer)');
    await as(
      owner,
      'CREATE TRIGGER integrity_guard BEFORE INSERT ON other.unmanaged FOR EACH ROW EXECUTE FUNCTION app.integrity_guard()',
    );
    result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some(
        (entry) =>
          entry.code === 'unsupported-routines' &&
          entry.resource === '"app"."integrity_guard"',
      ),
    ).toBe(true);
  });
  it('rejects an overload alongside an otherwise declared trigger function', async () => {
    contract.managedTriggerFunctions = ['integrity_guard'];
    await as(
      owner,
      'CREATE FUNCTION app.integrity_guard() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER AS $$ BEGIN RETURN NEW; END $$',
    );
    await as(
      owner,
      'CREATE TRIGGER integrity_guard BEFORE INSERT ON app.items FOR EACH ROW EXECUTE FUNCTION app.integrity_guard()',
    );
    await as(
      owner,
      "CREATE FUNCTION app.integrity_guard(value text) RETURNS integer LANGUAGE sql AS 'SELECT 1'",
    );
    const result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.filter(
        (entry) =>
          entry.code === 'unsupported-routines' &&
          entry.resource === '"app"."integrity_guard"',
      ),
    ).not.toHaveLength(0);
  });
  it('repairs restored direct table/column grants and preserves unrelated role ACLs', async () => {
    await db.query(`GRANT ALL ON app.items TO ${q(monitor)} WITH GRANT OPTION`);
    await db.query(`GRANT UPDATE(secret) ON app.items TO ${q(monitor)}`);
    await db.query(`GRANT SELECT(secret) ON app.items TO ${q(runtime)}`);
    await as(
      owner,
      "INSERT INTO app.items(visible,secret) VALUES ('preserved','secret')",
    );
    await db.query('CREATE SCHEMA unrelated');
    await db.query('CREATE TABLE unrelated.saved(id int)');
    await db.query(`GRANT SELECT ON unrelated.saved TO ${q(owner)}`);
    const before = (
      await db.query(
        "SELECT relacl::text FROM pg_class WHERE oid='unrelated.saved'::regclass",
      )
    ).rows;
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.severity === 'excessive',
      ),
    ).toBe(true);
    await apply();
    await expect(as(monitor, 'SELECT secret FROM app.items')).rejects.toThrow();
    await expect(
      as(monitor, "UPDATE app.items SET secret='no'"),
    ).rejects.toThrow();
    expect(
      (
        await db.query(
          "SELECT relacl::text FROM pg_class WHERE oid='unrelated.saved'::regclass",
        )
      ).rows,
    ).toEqual(before);
    expect((await as(runtime, 'SELECT visible FROM app.items')).rows).toEqual([
      { visible: 'preserved' },
    ]);
  });
  it('is idempotent and creator defaults cover future framework/application tables and sequences', async () => {
    await apply();
    expect((await apply()).statements).toEqual([]);
    await as(owner, 'CREATE TABLE app.future(id bigserial, value text)');
    await as(owner, 'CREATE TABLE app._smrt_feature(id text)');
    await as(runtime, "INSERT INTO app.future(value) VALUES ('yes')");
    await as(runtime, "INSERT INTO app._smrt_feature VALUES ('yes')");
    await expect(as(monitor, 'SELECT * FROM app.future')).rejects.toThrow();
    contract.managedTables.push('future');
    expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
      [],
    );
  });
  it('revokes creator defaults from declared retained tables and their sequences without changing retained data', async () => {
    await apply();
    await as(
      owner,
      'CREATE TABLE app.operator_audit (id bigserial PRIMARY KEY, evidence text NOT NULL)',
    );
    await as(
      owner,
      "INSERT INTO app.operator_audit(evidence) VALUES ('preserve this')",
    );
    expect(
      (await as(runtime, 'SELECT evidence FROM app.operator_audit')).rows,
    ).toEqual([{ evidence: 'preserve this' }]);
    contract.retainedTables = ['operator_audit'];
    const stale = await planPostgresPermissions(db, contract);
    await db.query(
      `GRANT SELECT(evidence) ON app.operator_audit TO ${q(monitor)}`,
    );
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: stale.fingerprint,
      }),
    ).rejects.toThrow('stale');
    const before = await planPostgresPermissions(db, contract);
    expect(before.canApply, JSON.stringify(before.diagnostics)).toBe(true);
    expect(before.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'excessive-privilege',
        role: runtime,
        resource: '"app"."operator_audit"',
      }),
    );
    expect(before.statements).toContain(
      `REVOKE ALL PRIVILEGES ON TABLE "app"."operator_audit" FROM ${q(runtime)}`,
    );
    expect(before.statements).toContain(
      `REVOKE ALL PRIVILEGES ON SEQUENCE "app"."operator_audit_id_seq" FROM ${q(runtime)}`,
    );
    const result = await applyPostgresPermissions(db, contract, {
      expectedFingerprint: before.fingerprint,
    });
    expect(result.diagnostics).toEqual([]);
    await expect(
      as(runtime, 'SELECT evidence FROM app.operator_audit'),
    ).rejects.toThrow();
    await expect(
      as(runtime, "SELECT nextval('app.operator_audit_id_seq')"),
    ).rejects.toThrow();
    await expect(
      as(monitor, 'SELECT evidence FROM app.operator_audit'),
    ).rejects.toThrow();
    expect(
      (await as(owner, 'SELECT evidence FROM app.operator_audit')).rows,
    ).toEqual([{ evidence: 'preserve this' }]);
    expect((await apply()).statements).toEqual([]);
  });
  it('fails closed for undeclared tables and retained monitoring declarations', async () => {
    await as(owner, 'CREATE TABLE app.unknown_table (id integer)');
    let plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'undeclared-table' }),
    );
    await as(owner, 'DROP TABLE app.unknown_table');
    await as(owner, 'CREATE TABLE app.operator_audit (id integer)');
    contract.retainedTables = ['operator_audit'];
    if (!contract.monitor) throw new Error('Expected test monitor role.');
    contract.monitor.tables.operator_audit = ['id'];
    plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'monitor-table',
        resource: 'operator_audit',
      }),
    );
  });
  it('refuses retained inheritance from a managed table', async () => {
    await as(owner, 'CREATE TABLE app.operator_audit () INHERITS (app.items)');
    contract.retainedTables = ['operator_audit'];
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'retained-inheritance',
        resource: '"app"."operator_audit"',
      }),
    );
  });
  it('refuses a managed partition of a retained table', async () => {
    await as(
      owner,
      'CREATE TABLE app.operator_audit (id bigint) PARTITION BY RANGE (id)',
    );
    await as(
      owner,
      'CREATE TABLE app.operator_audit_partition PARTITION OF app.operator_audit FOR VALUES FROM (0) TO (100)',
    );
    contract.retainedTables = ['operator_audit'];
    contract.managedTables = ['operator_audit_partition'];
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'retained-inheritance',
        resource: '"app"."operator_audit_partition"',
      }),
    );
  });
  it('refuses retained foreign keys to a managed table', async () => {
    await as(
      owner,
      'CREATE TABLE app.operator_audit (item_id bigint REFERENCES app.items(id) ON DELETE CASCADE)',
    );
    contract.retainedTables = ['operator_audit'];
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'retained-foreign-key',
        resource: '"app"."operator_audit" -> "app"."items"',
      }),
    );
  });
  it('refuses managed rewrite rules that could write a retained table', async () => {
    await as(owner, 'CREATE TABLE app.operator_audit (evidence text)');
    await as(
      owner,
      'CREATE RULE items_to_audit AS ON INSERT TO app.items DO ALSO INSERT INTO app.operator_audit(evidence) VALUES (NEW.visible)',
    );
    contract.retainedTables = ['operator_audit'];
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({
        code: 'user-rewrite-rule',
        resource: '"app"."items" (items_to_audit)',
      }),
    );
  });
  it('allows rewrite rules that do not reference a retained table', async () => {
    await as(owner, 'CREATE TABLE app.operator_audit (evidence text)');
    await as(
      owner,
      'CREATE RULE items_notify AS ON UPDATE TO app.items DO ALSO NOTIFY items_updated',
    );
    contract.retainedTables = ['operator_audit'];
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
  });
  it('retains permissions for tables and sequences created by supported owner migrations', async () => {
    await as(owner, 'DROP TABLE app._smrt_schema_migrations');
    await db.query(
      `ALTER ROLE ${q(owner)} IN DATABASE ${q(database)} SET search_path = app`,
    );
    const url = new URL(pgUrl!);
    url.pathname = `/${database}`;
    url.username = owner;
    url.password = rolePassword;
    const migrationDb = await resolveDatabase(
      { type: 'postgres', url: url.toString() },
      { dbid: `${database}-supported-migration` },
    );
    try {
      const tracker = new MigrationTracker({
        db: migrationDb,
        engineHint: 'postgres',
      });
      await tracker.initialize();
      await apply();
      const results = await tracker.applyAll(
        [
          {
            id: 'permissions_2701_future_table',
            description: 'Create an application table after permission setup',
            version: '1.0.0',
            up: [
              'CREATE TABLE app.migrated_items (id bigserial PRIMARY KEY, value text)',
            ],
            down: ['DROP TABLE app.migrated_items'],
          },
        ],
        { atomic: true },
      );
      expect(results).toHaveLength(1);
      expect(results[0].success).toBe(true);
      await as(
        runtime,
        "INSERT INTO app.migrated_items(value) VALUES ('supported')",
      );
      expect(
        (await as(runtime, 'SELECT value FROM app.migrated_items')).rows,
      ).toEqual([{ value: 'supported' }]);
      await expect(
        as(monitor, 'SELECT * FROM app.migrated_items'),
      ).rejects.toThrow();
      await expect(
        as(runtime, 'DELETE FROM app._smrt_schema_migrations'),
      ).rejects.toThrow();
      contract.managedTables.push('migrated_items');
      expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
        [],
      );
    } finally {
      await migrationDb.close();
    }
  });
  it('fails closed for memberships, PUBLIC access, ownership, and global defaults', async () => {
    await db.query(`GRANT ${q(owner)} TO ${q(runtime)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'role-membership',
      ),
    ).toBe(true);
    await db.query(`REVOKE ${q(owner)} FROM ${q(runtime)}`);
    await db.query('GRANT SELECT ON app.items TO PUBLIC');
    let plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: plan.fingerprint,
      }),
    ).rejects.toThrow('unsupported');
    await db.query('REVOKE SELECT ON app.items FROM PUBLIC');
    await db.query(`ALTER TABLE app.items OWNER TO ${q(runtime)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'resource-owner',
      ),
    ).toBe(true);
    await db.query(`ALTER TABLE app.items OWNER TO ${q(owner)}`);
    await db.query(
      `ALTER DEFAULT PRIVILEGES FOR ROLE ${q(owner)} GRANT SELECT ON TABLES TO ${q(monitor)}`,
    );
    plan = await planPostgresPermissions(db, contract);
    expect(
      plan.diagnostics.some(
        (entry) => entry.code === 'global-default-privilege',
      ),
    ).toBe(true);
    expect(plan.canApply).toBe(false);
  });
  it('refuses inbound memberships of every configured role without changing permissions', async () => {
    const external = `inbound_${randomUUID().replaceAll('-', '').slice(0, 12)}`;
    await admin.query(`CREATE ROLE ${q(external)} LOGIN`);
    try {
      const baseline = await planPostgresPermissions(db, contract);
      for (const role of [runtime, monitor, owner]) {
        await admin.query(`GRANT ${q(role)} TO ${q(external)}`);
        try {
          const plan = await planPostgresPermissions(db, contract);
          expect(plan.canApply).toBe(false);
          expect(
            plan.diagnostics.some(
              (entry) =>
                entry.code === 'role-membership' &&
                entry.message.includes(external) &&
                entry.message.includes(role),
            ),
          ).toBe(true);
          await expect(
            applyPostgresPermissions(db, contract, {
              expectedFingerprint: plan.fingerprint,
            }),
          ).rejects.toThrow('unsupported');
          expect(
            (await planPostgresPermissions(db, contract)).fingerprint,
          ).toBe(plan.fingerprint);
        } finally {
          await admin.query(`REVOKE ${q(role)} FROM ${q(external)}`);
        }
        expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
          baseline.fingerprint,
        );
      }
    } finally {
      await admin.query(`DROP ROLE ${q(external)}`);
    }
  });
  it('reports missing prerequisites, unknown columns, and unrelated effective access without mutation', async () => {
    const absent = {
      ...contract,
      migrationOwner: 'missing_owner_2701',
      managedTables: ['missing_table'],
    };
    const result = await planPostgresPermissions(db, absent);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some((entry) => entry.code === 'missing-role'),
    ).toBe(true);
    expect(
      result.diagnostics.some((entry) => entry.code === 'missing-table'),
    ).toBe(true);
    contract.monitor?.tables.items.push('missing_column');
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'monitor-column',
      ),
    ).toBe(true);
    await db.query('CREATE TABLE public.unrelated(id int)');
    await db.query(`GRANT SELECT ON public.unrelated TO ${q(monitor)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'outside-resource-access',
      ),
    ).toBe(true);
  });
  it('rejects stale plans and rolls back every grant on mid-apply failure', async () => {
    const before = await planPostgresPermissions(db, contract);
    await db.query(`GRANT SELECT ON app.items TO ${q(runtime)}`);
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: before.fingerprint,
      }),
    ).rejects.toThrow('stale');
    const fresh = await planPostgresPermissions(db, contract);
    const failing = {
      transaction: (callback: (tx: DatabaseInterface) => Promise<unknown>) =>
        db.transaction?.(async (tx) =>
          callback({
            ...tx,
            query: async (sql: string, ...args: unknown[]) => {
              if (sql.startsWith('ALTER DEFAULT PRIVILEGES'))
                throw new Error('injected mutation failure');
              return tx.query(sql, ...args);
            },
          } as DatabaseInterface),
        ),
    } as DatabaseInterface;
    await expect(
      applyPostgresPermissions(failing, contract, {
        expectedFingerprint: fresh.fingerprint,
      }),
    ).rejects.toThrow('injected');
    expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
      fresh.fingerprint,
    );
  });
  it('supports migration-owner apply and real LOGIN runtime/monitor connections', async () => {
    const connections: DatabaseInterface[] = [];
    try {
      async function connect(role: string) {
        const url = new URL(pgUrl!);
        url.pathname = `/${database}`;
        url.username = role;
        url.password = rolePassword;
        const connection = await resolveDatabase(
          { type: 'postgres', url: url.toString() },
          { dbid: `${database}-${role}` },
        );
        connections.push(connection);
        return connection;
      }
      const ownerDb = await connect(owner);
      const plan = await planPostgresPermissions(ownerDb, contract);
      expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
      await applyPostgresPermissions(ownerDb, contract, {
        expectedFingerprint: plan.fingerprint,
      });
      const runtimeDb = await connect(runtime);
      await runtimeDb.query(
        "INSERT INTO app.items(visible,secret) VALUES ('login','private')",
      );
      const monitorDb = await connect(monitor);
      expect(
        (await monitorDb.query('SELECT visible FROM app.items')).rows,
      ).toEqual([{ visible: 'login' }]);
      await expect(
        monitorDb.query('SELECT secret FROM app.items'),
      ).rejects.toThrow();
      await expect(
        runtimeDb.query('CREATE TABLE app.denied(id int)'),
      ).rejects.toThrow();
    } finally {
      for (const connection of connections) await connection.close();
    }
  });
  it('refuses privileged roles and absent schema without changing ACLs', async () => {
    const original = await planPostgresPermissions(db, contract);
    const absent = { ...contract, schema: 'missing_schema' };
    const plan = await planPostgresPermissions(db, absent);
    expect(
      plan.diagnostics.some((entry) => entry.code === 'missing-schema'),
    ).toBe(true);
    await expect(
      applyPostgresPermissions(db, absent, {
        expectedFingerprint: plan.fingerprint,
      }),
    ).rejects.toThrow('unsupported');
    expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
      original.fingerprint,
    );
    await db.query(`ALTER ROLE ${q(runtime)} CREATEDB`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'privileged-role',
      ),
    ).toBe(true);
  });
  it('escapes punctuation safely with legacy string literal settings', async () => {
    const odd = "odd\\'; SELECT 1; --";
    await as(owner, `CREATE SCHEMA ${q(odd)} AUTHORIZATION ${q(owner)}`);
    await as(owner, `CREATE TABLE ${q(odd)}.items(id text)`);
    for (const table of [
      '_smrt_migrations',
      '_smrt_schema_migrations',
      '_smrt_backfills',
    ]) {
      await as(owner, `CREATE TABLE ${q(odd)}.${q(table)} (id text)`);
    }
    const weirdContract = { ...contract, schema: odd, monitor: undefined };
    await db.transaction?.(async (tx) => {
      await tx.query('SET LOCAL standard_conforming_strings = off');
      const plan = await planPostgresPermissions(tx, weirdContract);
      expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
      expect(
        plan.statements.some((statement) => statement.includes(q(odd))),
      ).toBe(true);
    });
    expect(
      (await db.query("SELECT 1 FROM pg_namespace WHERE nspname='app'")).rows,
    ).toHaveLength(1);
  });
  it('refuses parameter configuration authority from PostgreSQL 15+ ACLs', async () => {
    const version = Number(
      (
        await db.query(
          "SELECT current_setting('server_version_num') AS version",
        )
      ).rows[0].version,
    );
    if (version < 150000) return;
    try {
      await db.query(
        `GRANT ALTER SYSTEM ON PARAMETER log_statement TO ${q(runtime)}`,
      );
      const plan = await planPostgresPermissions(db, contract);
      expect(plan.canApply).toBe(false);
      expect(
        plan.diagnostics.some(
          (entry) =>
            entry.code === 'parameter-privilege' && entry.role === runtime,
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: plan.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
    } finally {
      // Parameter ACLs are cluster scoped, so remove this test role's grant.
      await db.query(
        `REVOKE ALTER SYSTEM ON PARAMETER log_statement FROM ${q(runtime)}`,
      );
    }
  });
  it('requires every bookkeeping table before setup and repairs recreated bookkeeping ACLs', async () => {
    for (const table of [
      '_smrt_migrations',
      '_smrt_schema_migrations',
      '_smrt_backfills',
    ]) {
      await as(owner, `DROP TABLE app.${q(table)}`);
      const missing = await planPostgresPermissions(db, contract);
      expect(missing.canApply).toBe(false);
      expect(
        missing.diagnostics.some(
          (entry) =>
            entry.code === 'missing-bookkeeping-table' &&
            entry.resource.includes(table),
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: missing.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
      expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
        missing.fingerprint,
      );
      await as(owner, `CREATE TABLE app.${q(table)} (id text)`);
    }
    await apply();
    // A maintenance cycle keeps runtime and monitoring inactive until repair.
    await as(owner, 'DROP TABLE app._smrt_backfills');
    await as(owner, 'CREATE TABLE app._smrt_backfills (id text)');
    const restored = await planPostgresPermissions(db, contract);
    expect(
      restored.diagnostics.some(
        (entry) =>
          entry.severity === 'excessive' &&
          entry.resource.includes('_smrt_backfills'),
      ),
    ).toBe(true);
    expect(
      (
        await db.query(
          'SELECT has_table_privilege($1, $2, $3) AS allowed',
          runtime,
          'app._smrt_backfills',
          'INSERT',
        )
      ).rows[0].allowed,
    ).toBe(true);
    await applyPostgresPermissions(db, contract, {
      expectedFingerprint: restored.fingerprint,
    });
    await expect(
      as(runtime, "INSERT INTO app._smrt_backfills VALUES ('forbidden')"),
    ).rejects.toThrow();
    await expect(
      as(monitor, 'SELECT * FROM app._smrt_backfills'),
    ).rejects.toThrow();
  });
  it('refuses historical system table, column and privileged routine ACL deltas', async () => {
    const cases = [
      [
        'GRANT SELECT ON information_schema._pg_user_mappings TO PUBLIC',
        'REVOKE SELECT ON information_schema._pg_user_mappings FROM PUBLIC',
      ],
      [
        `GRANT SELECT ON pg_catalog.pg_authid TO ${q(monitor)}`,
        `REVOKE SELECT ON pg_catalog.pg_authid FROM ${q(monitor)}`,
      ],
      [
        `GRANT SELECT(rolpassword) ON pg_catalog.pg_authid TO ${q(monitor)}`,
        `REVOKE SELECT(rolpassword) ON pg_catalog.pg_authid FROM ${q(monitor)}`,
      ],
      [
        'GRANT SELECT ON pg_catalog.pg_authid TO PUBLIC',
        'REVOKE SELECT ON pg_catalog.pg_authid FROM PUBLIC',
      ],
      [
        `GRANT EXECUTE ON FUNCTION pg_catalog.pg_read_file(text) TO ${q(runtime)}`,
        `REVOKE EXECUTE ON FUNCTION pg_catalog.pg_read_file(text) FROM ${q(runtime)}`,
      ],
      [
        'GRANT EXECUTE ON FUNCTION pg_catalog.pg_read_file(text) TO PUBLIC',
        'REVOKE EXECUTE ON FUNCTION pg_catalog.pg_read_file(text) FROM PUBLIC',
      ],
    ];
    for (const [grant, revoke] of cases) {
      await db.query(grant);
      try {
        // Inspect ACL metadata only; never query credential/catalog record values.
        const plan = await planPostgresPermissions(db, contract);
        expect(plan.canApply).toBe(false);
        expect(
          plan.diagnostics.some(
            (entry) => entry.code === 'system-privilege-delta',
          ),
        ).toBe(true);
        await expect(
          applyPostgresPermissions(db, contract, {
            expectedFingerprint: plan.fingerprint,
          }),
        ).rejects.toThrow('unsupported');
        expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
          plan.fingerprint,
        );
      } finally {
        await db.query(revoke);
      }
    }
  });
  it('refuses PUBLIC managed access without a monitor and grants explicit database CONNECT', async () => {
    contract = { ...contract, monitor: undefined };
    const cases = [
      [
        'GRANT SELECT,INSERT,UPDATE,DELETE ON app.items TO PUBLIC',
        'REVOKE SELECT,INSERT,UPDATE,DELETE ON app.items FROM PUBLIC',
      ],
      [
        'GRANT SELECT(visible) ON app.items TO PUBLIC',
        'REVOKE SELECT(visible) ON app.items FROM PUBLIC',
      ],
      [
        'GRANT USAGE ON SCHEMA app TO PUBLIC',
        'REVOKE USAGE ON SCHEMA app FROM PUBLIC',
      ],
      [
        'GRANT USAGE ON SEQUENCE app.items_id_seq TO PUBLIC',
        'REVOKE USAGE ON SEQUENCE app.items_id_seq FROM PUBLIC',
      ],
      [
        `GRANT TEMPORARY,CREATE ON DATABASE ${q(database)} TO PUBLIC`,
        `REVOKE TEMPORARY,CREATE ON DATABASE ${q(database)} FROM PUBLIC`,
      ],
      [
        `ALTER DEFAULT PRIVILEGES FOR ROLE ${q(owner)} IN SCHEMA app GRANT SELECT ON TABLES TO PUBLIC`,
        `ALTER DEFAULT PRIVILEGES FOR ROLE ${q(owner)} IN SCHEMA app REVOKE SELECT ON TABLES FROM PUBLIC`,
      ],
    ];
    for (const [grant, revoke] of cases) {
      await db.query(grant);
      try {
        const plan = await planPostgresPermissions(db, contract);
        expect(plan.canApply, grant).toBe(false);
        await expect(
          applyPostgresPermissions(db, contract, {
            expectedFingerprint: plan.fingerprint,
          }),
        ).rejects.toThrow('unsupported');
        expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
          plan.fingerprint,
        );
      } finally {
        await db.query(revoke);
      }
    }
    const clean = await planPostgresPermissions(db, contract);
    expect(clean.statements).toContain(
      `GRANT CONNECT ON DATABASE ${q(database)} TO ${q(runtime)}`,
    );
    await applyPostgresPermissions(db, contract, {
      expectedFingerprint: clean.fingerprint,
    });
    const grants = (
      await db.query(
        "SELECT a.grantee::text, a.privilege_type FROM pg_database d CROSS JOIN LATERAL aclexplode(d.datacl) a WHERE d.datname=current_database() AND a.privilege_type='CONNECT' AND (a.grantee=0 OR a.grantee=(SELECT oid FROM pg_roles WHERE rolname=$1))",
        runtime,
      )
    ).rows;
    expect(grants).toHaveLength(2);
  });
  it('refuses system schema CREATE authority and ownership without modifying ACLs', async () => {
    await apply();
    const baseline = await planPostgresPermissions(db, contract);
    for (const schema of ['pg_catalog', 'information_schema']) {
      for (const grantee of [q(runtime), q(monitor), 'PUBLIC']) {
        await db.query(`GRANT CREATE ON SCHEMA ${q(schema)} TO ${grantee}`);
        try {
          const exposed = await planPostgresPermissions(db, contract);
          expect(exposed.canApply).toBe(false);
          expect(exposed.fingerprint).not.toBe(baseline.fingerprint);
          expect(
            exposed.diagnostics.some(
              (entry) =>
                entry.code === 'system-schema-authority' &&
                entry.resource === schema,
            ),
          ).toBe(true);
          await expect(
            applyPostgresPermissions(db, contract, {
              expectedFingerprint: exposed.fingerprint,
            }),
          ).rejects.toThrow('unsupported');
          expect(
            (await planPostgresPermissions(db, contract)).fingerprint,
          ).toBe(exposed.fingerprint);
        } finally {
          await db.query(
            `REVOKE CREATE ON SCHEMA ${q(schema)} FROM ${grantee}`,
          );
        }
        expect(
          (await planPostgresPermissions(db, contract)).diagnostics,
        ).toEqual([]);
      }
    }
    const originalOwner = String(
      (
        await db.query(
          "SELECT pg_get_userbyid(nspowner) AS owner FROM pg_namespace WHERE nspname='information_schema'",
        )
      ).rows[0].owner,
    );
    for (const role of [runtime, monitor]) {
      await db.query(`ALTER SCHEMA information_schema OWNER TO ${q(role)}`);
      try {
        const exposed = await planPostgresPermissions(db, contract);
        expect(exposed.canApply).toBe(false);
        expect(
          exposed.diagnostics.some(
            (entry) =>
              entry.code === 'system-schema-owner' && entry.role === role,
          ),
        ).toBe(true);
        await expect(
          applyPostgresPermissions(db, contract, {
            expectedFingerprint: exposed.fingerprint,
          }),
        ).rejects.toThrow('unsupported');
        expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
          exposed.fingerprint,
        );
      } finally {
        await db.query(
          `ALTER SCHEMA information_schema OWNER TO ${q(originalOwner)}`,
        );
      }
    }
    expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
      [],
    );
  });
  it('refuses system object ownership after ordinary owner ACLs are revoked', async () => {
    await apply();
    for (const role of [runtime, monitor]) {
      for (const kind of ['TABLE', 'SEQUENCE', 'FUNCTION', 'TYPE']) {
        const resource = `information_schema.${q(`synthetic_${kind.toLowerCase()}`)}`;
        const target = kind === 'FUNCTION' ? `${resource}()` : resource;
        const create =
          kind === 'TABLE'
            ? `CREATE TABLE ${resource}(id int)`
            : kind === 'SEQUENCE'
              ? `CREATE SEQUENCE ${resource}`
              : kind === 'FUNCTION'
                ? `CREATE FUNCTION ${target} RETURNS integer LANGUAGE sql AS 'SELECT 1'`
                : `CREATE TYPE ${resource} AS ENUM ('initial')`;
        await db.query(create);
        try {
          await db.query(`ALTER ${kind} ${target} OWNER TO ${q(role)}`);
          await db.query(
            `REVOKE ALL PRIVILEGES ON ${kind} ${target} FROM PUBLIC, ${q(role)}`,
          );
          const alter =
            kind === 'TABLE'
              ? `ALTER TABLE ${resource} ADD COLUMN synthetic int`
              : kind === 'SEQUENCE'
                ? `ALTER SEQUENCE ${resource} INCREMENT BY 2`
                : kind === 'FUNCTION'
                  ? `ALTER FUNCTION ${target} COST 2`
                  : `ALTER TYPE ${resource} ADD VALUE 'changed'`;
          // Synthetic owner-only DDL remains possible despite revoked ACLs.
          await as(role, alter);
          const plan = await planPostgresPermissions(db, contract);
          expect(plan.canApply, `${kind} owner ${role}`).toBe(false);
          expect(
            plan.diagnostics.some(
              (entry) =>
                entry.code === 'system-object-owner' && entry.role === role,
            ),
          ).toBe(true);
          await expect(
            applyPostgresPermissions(db, contract, {
              expectedFingerprint: plan.fingerprint,
            }),
          ).rejects.toThrow('unsupported');
          expect(
            (await planPostgresPermissions(db, contract)).fingerprint,
          ).toBe(plan.fingerprint);
        } finally {
          await db.query(`DROP ${kind} ${target}`);
        }
      }
    }
  });
  it('refuses unrecorded custom system routines', async () => {
    await apply();
    await as(
      owner,
      "INSERT INTO app.items(visible,secret) VALUES ('test','synthetic-private')",
    );
    for (const schema of ['pg_catalog', 'information_schema']) {
      const routine = `${q(schema)}.synthetic_private_2701()`;
      await db.query(
        `CREATE FUNCTION ${routine} RETURNS text LANGUAGE sql SECURITY DEFINER AS 'SELECT secret FROM app.items LIMIT 1'`,
      );
      try {
        expect((await as(monitor, `SELECT ${routine} AS value`)).rows).toEqual([
          { value: 'synthetic-private' },
        ]);
        const exposed = await planPostgresPermissions(db, contract);
        expect(exposed.canApply).toBe(false);
        expect(
          exposed.diagnostics.some(
            (entry) => entry.code === 'system-privilege-delta',
          ),
        ).toBe(true);
      } finally {
        await db.query(`DROP FUNCTION ${routine}`);
      }
    }
  });
  it('refuses exceptional system type grants', async () => {
    await apply();
    await db.query(
      `GRANT USAGE ON TYPE pg_catalog.int4 TO ${q(runtime)} WITH GRANT OPTION`,
    );
    try {
      const exposed = await planPostgresPermissions(db, contract);
      expect(exposed.canApply).toBe(false);
      expect(
        exposed.diagnostics.some(
          (entry) =>
            entry.code === 'system-privilege-delta' && entry.role === runtime,
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: exposed.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
      expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
        exposed.fingerprint,
      );
    } finally {
      await db.query(`REVOKE USAGE ON TYPE pg_catalog.int4 FROM ${q(runtime)}`);
    }
  });
  it('refuses large-object owners and direct or PUBLIC access without reading payloads in diagnostics', async () => {
    await apply();
    const oid = Number(
      (
        await db.query(
          "SELECT lo_from_bytea(0, convert_to('synthetic-only', 'UTF8')) AS oid",
        )
      ).rows[0].oid,
    );
    try {
      for (const role of [runtime, monitor]) {
        await expect(
          as(role, `SELECT octet_length(lo_get(${oid}))`),
        ).rejects.toThrow();
        await expect(
          as(role, `SELECT lo_put(${oid}, 0, decode('01', 'hex'))`),
        ).rejects.toThrow();
      }
      for (const grantee of [q(runtime), q(monitor), 'PUBLIC']) {
        for (const privilege of ['SELECT', 'UPDATE']) {
          await db.query(
            `GRANT ${privilege} ON LARGE OBJECT ${oid} TO ${grantee}`,
          );
          try {
            const actor = grantee === q(monitor) ? monitor : runtime;
            if (privilege === 'SELECT') {
              await as(actor, `SELECT octet_length(lo_get(${oid}))`);
            } else {
              // PostgreSQL's write descriptor also needs SELECT. Prove the
              // actual write with both grants, then diagnose UPDATE alone.
              await db.query(
                `GRANT SELECT ON LARGE OBJECT ${oid} TO ${grantee}`,
              );
              try {
                await as(
                  actor,
                  `SELECT lo_put(${oid}, 0, decode('01', 'hex'))`,
                );
              } finally {
                await db.query(
                  `REVOKE SELECT ON LARGE OBJECT ${oid} FROM ${grantee}`,
                );
              }
            }
            const exposed = await planPostgresPermissions(db, contract);
            expect(exposed.canApply, `${grantee} ${privilege}`).toBe(false);
            expect(
              exposed.diagnostics.some(
                (entry) => entry.code === 'large-object-privilege',
              ),
            ).toBe(true);
            await expect(
              applyPostgresPermissions(db, contract, {
                expectedFingerprint: exposed.fingerprint,
              }),
            ).rejects.toThrow('unsupported');
            expect(
              (await planPostgresPermissions(db, contract)).fingerprint,
            ).toBe(exposed.fingerprint);
          } finally {
            await db.query(
              `REVOKE ${privilege} ON LARGE OBJECT ${oid} FROM ${grantee}`,
            );
          }
        }
      }
      for (const role of [runtime, monitor]) {
        await db.query(`ALTER LARGE OBJECT ${oid} OWNER TO ${q(role)}`);
        await db.query(`REVOKE ALL ON LARGE OBJECT ${oid} FROM ${q(role)}`);
        const exposed = await planPostgresPermissions(db, contract);
        expect(exposed.canApply).toBe(false);
        expect(
          exposed.diagnostics.some(
            (entry) =>
              entry.code === 'large-object-owner' && entry.role === role,
          ),
        ).toBe(true);
        await expect(
          applyPostgresPermissions(db, contract, {
            expectedFingerprint: exposed.fingerprint,
          }),
        ).rejects.toThrow('unsupported');
        expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
          exposed.fingerprint,
        );
      }
    } finally {
      await db.query(`SELECT lo_unlink(${oid})`);
    }
  });
  it('refuses large-object compatibility mode and configured role/database overrides', async () => {
    await apply();
    const oid = Number(
      (
        await db.query(
          "SELECT lo_from_bytea(0, convert_to('synthetic-only', 'UTF8')) AS oid",
        )
      ).rows[0].oid,
    );
    try {
      await db.transaction?.(async (tx) => {
        await tx.query('SET LOCAL lo_compat_privileges = on');
        await tx.query(`SET LOCAL ROLE ${q(runtime)}`);
        await tx.query(`SELECT octet_length(lo_get(${oid}))`);
        await tx.query('RESET ROLE');
        const exposed = await planPostgresPermissions(tx, contract);
        expect(exposed.canApply).toBe(false);
        expect(
          exposed.diagnostics.some(
            (entry) => entry.code === 'large-object-compatibility',
          ),
        ).toBe(true);
      });
      await db.transaction?.(async (tx) => {
        await tx.query('SET LOCAL lo_compat_privileges = off');
        const obscured = await planPostgresPermissions(tx, contract);
        expect(obscured.canApply).toBe(false);
        expect(
          obscured.diagnostics.some(
            (entry) => entry.code === 'large-object-compatibility',
          ),
        ).toBe(true);
      });
      for (const target of [
        `ROLE ${q(runtime)}`,
        `ROLE ${q(monitor)} IN DATABASE ${q(database)}`,
        `DATABASE ${q(database)}`,
      ]) {
        await db.query(`ALTER ${target} SET lo_compat_privileges = on`);
        try {
          const exposed = await planPostgresPermissions(db, contract);
          expect(exposed.canApply, target).toBe(false);
          expect(
            exposed.diagnostics.some(
              (entry) => entry.code === 'large-object-compatibility',
            ),
          ).toBe(true);
          await expect(
            applyPostgresPermissions(db, contract, {
              expectedFingerprint: exposed.fingerprint,
            }),
          ).rejects.toThrow('unsupported');
          expect(
            (await planPostgresPermissions(db, contract)).fingerprint,
          ).toBe(exposed.fingerprint);
        } finally {
          await db.query(`ALTER ${target} RESET lo_compat_privileges`);
        }
      }
      await expect(
        as(runtime, `SELECT octet_length(lo_get(${oid}))`),
      ).rejects.toThrow();
    } finally {
      await db.query(`SELECT lo_unlink(${oid})`);
    }
  });
  it('reports legacy PUBLIC CREATE on public as an infrastructure prerequisite', async () => {
    await db.query('GRANT CREATE ON SCHEMA public TO PUBLIC');
    try {
      const exposed = await planPostgresPermissions(db, contract);
      expect(exposed.canApply).toBe(false);
      expect(
        exposed.diagnostics.some(
          (entry) =>
            entry.code === 'outside-schema-create' &&
            entry.resource === 'public',
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: exposed.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
      expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
        exposed.fingerprint,
      );
    } finally {
      await db.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
    }
  });
  it('inspects non-array element types and domains over arrays without treating generated arrays as independent types', async () => {
    await apply();
    const before = await planPostgresPermissions(db, contract);
    const point = (
      await db.query(
        "SELECT typelem::text,typtype,typcategory FROM pg_type WHERE oid='pg_catalog.point'::regtype",
      )
    ).rows[0];
    expect(point.typelem).not.toBe('0');
    expect(point.typcategory).toBe('G');
    await db.query(
      `GRANT USAGE ON TYPE pg_catalog.point TO ${q(runtime)} WITH GRANT OPTION`,
    );
    try {
      const exposed = await planPostgresPermissions(db, contract);
      expect(exposed.canApply).toBe(false);
      expect(exposed.fingerprint).not.toBe(before.fingerprint);
      expect(
        exposed.diagnostics.some(
          (entry) =>
            entry.code === 'system-privilege-delta' &&
            entry.resource.includes('point') &&
            entry.role === runtime,
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: exposed.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
      expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
        exposed.fingerprint,
      );
    } finally {
      await db.query(
        `REVOKE USAGE ON TYPE pg_catalog.point FROM ${q(runtime)}`,
      );
    }
    for (const schema of ['app', 'information_schema']) {
      const domain = `${q(schema)}.synthetic_array_domain`;
      await db.query(`CREATE DOMAIN ${domain} AS integer[]`);
      try {
        const exposed = await planPostgresPermissions(db, contract);
        expect(exposed.canApply).toBe(false);
        const typeDiagnostics = exposed.diagnostics.filter(
          (entry) =>
            entry.code === 'unsupported-types' ||
            entry.code === 'system-privilege-delta',
        );
        expect(
          typeDiagnostics.some((entry) =>
            entry.resource.includes('synthetic_array_domain'),
          ),
        ).toBe(true);
        expect(
          typeDiagnostics.some((entry) =>
            entry.resource.includes('_synthetic_array_domain'),
          ),
        ).toBe(false);
      } finally {
        await db.query(`DROP DOMAIN ${domain}`);
      }
    }
    expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
      [],
    );
  });
  it('refuses user routines and standalone composite types after schema evolution', async () => {
    await apply();
    await as(owner, 'CREATE TYPE app.custom AS (value text)');
    await as(
      owner,
      "CREATE FUNCTION app.custom_fn() RETURNS integer LANGUAGE sql AS 'SELECT 1'",
    );
    const result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some((entry) => entry.code === 'unsupported-types'),
    ).toBe(true);
    expect(
      result.diagnostics.some((entry) => entry.code === 'unsupported-routines'),
    ).toBe(true);
  });
  it('reports user aggregates as unsupported instead of aborting catalog inspection', async () => {
    await as(
      owner,
      "CREATE FUNCTION app.aggregate_state(state integer, value integer) RETURNS integer LANGUAGE sql AS 'SELECT state + value'",
    );
    await as(
      owner,
      'CREATE AGGREGATE app.aggregate_sum(integer) (SFUNC = app.aggregate_state, STYPE = integer)',
    );
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    expect(plan.diagnostics).toContainEqual(
      expect.objectContaining({ code: 'unsupported-routines' }),
    );
  });
});
