import { randomUUID } from 'node:crypto';
import type { DatabaseInterface } from '@happyvertical/sql';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { resolveDatabase } from '../database.js';
import { MigrationTracker } from '../migrations/tracker.js';
import {
  applyPostgresPermissions,
  type PostgresPermissionContract,
  planPostgresPermissions,
} from '../postgres-permissions.js';

const pgUrl = process.env.SMRT_TEST_POSTGRES_URL;
const pgDescribe = pgUrl ? describe.sequential : describe.skip;

pgDescribe('PostgreSQL permission contract (#2701)', () => {
  let admin: DatabaseInterface;
  let db: DatabaseInterface;
  let database: string;
  let owner: string;
  let runtime: string;
  let monitor: string;
  let contract: PostgresPermissionContract;
  const q = (value: string) => `"${value.replaceAll('"', '""')}"`;
  async function as(role: string, sql: string) {
    return db.transaction?.(async (tx) => {
      await tx.query(`SET LOCAL ROLE ${q(role)}`);
      return tx.query(sql);
    });
  }
  async function apply() {
    const plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
    return applyPostgresPermissions(db, contract, {
      expectedFingerprint: plan.fingerprint,
    });
  }
  beforeEach(async () => {
    const suffix = randomUUID().replaceAll('-', '').slice(0, 12);
    database = `perm2701_${suffix}`;
    owner = `own_${suffix}`;
    runtime = `run_${suffix}`;
    monitor = `mon_${suffix}`;
    admin = await resolveDatabase(
      { type: 'postgres', url: pgUrl! },
      { dbid: `admin-${suffix}` },
    );
    for (const role of [owner, runtime, monitor])
      await admin.query(`CREATE ROLE ${q(role)} LOGIN`);
    await admin.query(`CREATE DATABASE ${q(database)} OWNER ${q(owner)}`);
    const url = new URL(pgUrl!);
    url.pathname = `/${database}`;
    db = await resolveDatabase(
      { type: 'postgres', url: url.toString() },
      { dbid: database },
    );
    await db.query(`REVOKE TEMPORARY ON DATABASE ${q(database)} FROM PUBLIC`);
    await db.query(`CREATE SCHEMA app AUTHORIZATION ${q(owner)}`);
    await as(
      owner,
      'CREATE TABLE app.items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, visible text, secret text)',
    );
    await as(owner, 'CREATE TABLE app._smrt_schema_migrations (id text)');
    contract = {
      schema: 'app',
      schemaExclusive: true,
      migrationOwner: owner,
      runtimeRole: runtime,
      managedTables: ['items'],
      monitor: { role: monitor, tables: { items: ['id', 'visible'] } },
    };
  });
  afterEach(async () => {
    await db?.close();
    if (database)
      await admin.query(`DROP DATABASE IF EXISTS ${q(database)} WITH (FORCE)`);
    for (const role of [owner, runtime, monitor])
      if (role) await admin.query(`DROP ROLE IF EXISTS ${q(role)}`);
    await admin?.close();
  });
  it('establishes actual runtime operations and column-only monitoring, excluding DDL and bookkeeping writes', async () => {
    const result = await apply();
    expect(result.diagnostics).toEqual([]);
    expect(result.statements).toEqual([]);
    await as(
      runtime,
      "INSERT INTO app.items(visible,secret) VALUES ('hello','private')",
    );
    await as(runtime, "UPDATE app.items SET visible='world' WHERE id=1");
    expect(
      (await as(monitor, 'SELECT id,visible FROM app.items')).rows,
    ).toHaveLength(1);
    await expect(as(monitor, 'SELECT secret FROM app.items')).rejects.toThrow();
    await expect(
      as(monitor, "UPDATE app.items SET visible='no' WHERE id=1"),
    ).rejects.toThrow();
    await expect(
      as(runtime, 'CREATE TABLE app.forbidden(id int)'),
    ).rejects.toThrow();
    await expect(
      as(runtime, 'CREATE TEMP TABLE forbidden(id int)'),
    ).rejects.toThrow();
    await expect(as(runtime, 'TRUNCATE app.items')).rejects.toThrow();
    await expect(
      as(runtime, "INSERT INTO app._smrt_schema_migrations VALUES ('fake')"),
    ).rejects.toThrow();
    await as(runtime, 'DELETE FROM app.items WHERE id=1');
  });
  it('repairs restored direct table/column grants and preserves unrelated role ACLs', async () => {
    await db.query(`GRANT ALL ON app.items TO ${q(monitor)} WITH GRANT OPTION`);
    await db.query(`GRANT UPDATE(secret) ON app.items TO ${q(monitor)}`);
    await db.query(`GRANT SELECT(secret) ON app.items TO ${q(runtime)}`);
    await as(
      owner,
      "INSERT INTO app.items(visible,secret) VALUES ('preserved','secret')",
    );
    await db.query('CREATE SCHEMA unrelated');
    await db.query('CREATE TABLE unrelated.saved(id int)');
    await db.query(`GRANT SELECT ON unrelated.saved TO ${q(owner)}`);
    const before = (
      await db.query(
        "SELECT relacl::text FROM pg_class WHERE oid='unrelated.saved'::regclass",
      )
    ).rows;
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.severity === 'excessive',
      ),
    ).toBe(true);
    await apply();
    await expect(as(monitor, 'SELECT secret FROM app.items')).rejects.toThrow();
    await expect(
      as(monitor, "UPDATE app.items SET secret='no'"),
    ).rejects.toThrow();
    expect(
      (
        await db.query(
          "SELECT relacl::text FROM pg_class WHERE oid='unrelated.saved'::regclass",
        )
      ).rows,
    ).toEqual(before);
    expect((await as(runtime, 'SELECT visible FROM app.items')).rows).toEqual([
      { visible: 'preserved' },
    ]);
  });
  it('is idempotent and creator defaults cover future framework/application tables and sequences', async () => {
    await apply();
    expect((await apply()).statements).toEqual([]);
    await as(owner, 'CREATE TABLE app.future(id bigserial, value text)');
    await as(owner, 'CREATE TABLE app._smrt_feature(id text)');
    await as(runtime, "INSERT INTO app.future(value) VALUES ('yes')");
    await as(runtime, "INSERT INTO app._smrt_feature VALUES ('yes')");
    await expect(as(monitor, 'SELECT * FROM app.future')).rejects.toThrow();
    contract.managedTables.push('future');
    expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
      [],
    );
  });
  it('retains permissions for tables and sequences created by supported owner migrations', async () => {
    await as(owner, 'DROP TABLE app._smrt_schema_migrations');
    await db.query(
      `ALTER ROLE ${q(owner)} IN DATABASE ${q(database)} SET search_path = app`,
    );
    const url = new URL(pgUrl!);
    url.pathname = `/${database}`;
    url.username = owner;
    url.password = '';
    const migrationDb = await resolveDatabase(
      { type: 'postgres', url: url.toString() },
      { dbid: `${database}-supported-migration` },
    );
    try {
      const tracker = new MigrationTracker({
        db: migrationDb,
        engineHint: 'postgres',
      });
      await tracker.initialize();
      await apply();
      const results = await tracker.applyAll(
        [
          {
            id: 'permissions_2701_future_table',
            description: 'Create an application table after permission setup',
            version: '1.0.0',
            up: [
              'CREATE TABLE app.migrated_items (id bigserial PRIMARY KEY, value text)',
            ],
            down: ['DROP TABLE app.migrated_items'],
          },
        ],
        { atomic: true },
      );
      expect(results).toHaveLength(1);
      expect(results[0].success).toBe(true);
      await as(
        runtime,
        "INSERT INTO app.migrated_items(value) VALUES ('supported')",
      );
      expect(
        (await as(runtime, 'SELECT value FROM app.migrated_items')).rows,
      ).toEqual([{ value: 'supported' }]);
      await expect(
        as(monitor, 'SELECT * FROM app.migrated_items'),
      ).rejects.toThrow();
      await expect(
        as(runtime, 'DELETE FROM app._smrt_schema_migrations'),
      ).rejects.toThrow();
      contract.managedTables.push('migrated_items');
      expect((await planPostgresPermissions(db, contract)).diagnostics).toEqual(
        [],
      );
    } finally {
      await migrationDb.close();
    }
  });
  it('fails closed for memberships, PUBLIC access, ownership, and global defaults', async () => {
    await db.query(`GRANT ${q(owner)} TO ${q(runtime)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'role-membership',
      ),
    ).toBe(true);
    await db.query(`REVOKE ${q(owner)} FROM ${q(runtime)}`);
    await db.query('GRANT SELECT ON app.items TO PUBLIC');
    let plan = await planPostgresPermissions(db, contract);
    expect(plan.canApply).toBe(false);
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: plan.fingerprint,
      }),
    ).rejects.toThrow('unsupported');
    await db.query('REVOKE SELECT ON app.items FROM PUBLIC');
    await db.query(`ALTER TABLE app.items OWNER TO ${q(runtime)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'resource-owner',
      ),
    ).toBe(true);
    await db.query(`ALTER TABLE app.items OWNER TO ${q(owner)}`);
    await db.query(
      `ALTER DEFAULT PRIVILEGES FOR ROLE ${q(owner)} GRANT SELECT ON TABLES TO ${q(monitor)}`,
    );
    plan = await planPostgresPermissions(db, contract);
    expect(
      plan.diagnostics.some(
        (entry) => entry.code === 'global-default-privilege',
      ),
    ).toBe(true);
    expect(plan.canApply).toBe(false);
  });
  it('reports missing prerequisites, unknown columns, and unrelated effective access without mutation', async () => {
    const absent = {
      ...contract,
      migrationOwner: 'missing_owner_2701',
      managedTables: ['missing_table'],
    };
    const result = await planPostgresPermissions(db, absent);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some((entry) => entry.code === 'missing-role'),
    ).toBe(true);
    expect(
      result.diagnostics.some((entry) => entry.code === 'missing-table'),
    ).toBe(true);
    contract.monitor?.tables.items.push('missing_column');
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'monitor-column',
      ),
    ).toBe(true);
    await db.query('CREATE TABLE public.unrelated(id int)');
    await db.query(`GRANT SELECT ON public.unrelated TO ${q(monitor)}`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'outside-resource-access',
      ),
    ).toBe(true);
  });
  it('rejects stale plans and rolls back every grant on mid-apply failure', async () => {
    const before = await planPostgresPermissions(db, contract);
    await db.query(`GRANT SELECT ON app.items TO ${q(runtime)}`);
    await expect(
      applyPostgresPermissions(db, contract, {
        expectedFingerprint: before.fingerprint,
      }),
    ).rejects.toThrow('stale');
    const fresh = await planPostgresPermissions(db, contract);
    const failing = {
      transaction: (callback: (tx: DatabaseInterface) => Promise<unknown>) =>
        db.transaction?.(async (tx) =>
          callback({
            ...tx,
            query: async (sql: string, ...args: unknown[]) => {
              if (sql.startsWith('ALTER DEFAULT PRIVILEGES'))
                throw new Error('injected mutation failure');
              return tx.query(sql, ...args);
            },
          } as DatabaseInterface),
        ),
    } as DatabaseInterface;
    await expect(
      applyPostgresPermissions(failing, contract, {
        expectedFingerprint: fresh.fingerprint,
      }),
    ).rejects.toThrow('injected');
    expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
      fresh.fingerprint,
    );
  });
  it('supports migration-owner apply and real LOGIN runtime/monitor connections', async () => {
    const connections: DatabaseInterface[] = [];
    try {
      async function connect(role: string) {
        const url = new URL(pgUrl!);
        url.pathname = `/${database}`;
        url.username = role;
        url.password = '';
        const connection = await resolveDatabase(
          { type: 'postgres', url: url.toString() },
          { dbid: `${database}-${role}` },
        );
        connections.push(connection);
        return connection;
      }
      const ownerDb = await connect(owner);
      const plan = await planPostgresPermissions(ownerDb, contract);
      expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
      await applyPostgresPermissions(ownerDb, contract, {
        expectedFingerprint: plan.fingerprint,
      });
      const runtimeDb = await connect(runtime);
      await runtimeDb.query(
        "INSERT INTO app.items(visible,secret) VALUES ('login','private')",
      );
      const monitorDb = await connect(monitor);
      expect(
        (await monitorDb.query('SELECT visible FROM app.items')).rows,
      ).toEqual([{ visible: 'login' }]);
      await expect(
        monitorDb.query('SELECT secret FROM app.items'),
      ).rejects.toThrow();
      await expect(
        runtimeDb.query('CREATE TABLE app.denied(id int)'),
      ).rejects.toThrow();
    } finally {
      for (const connection of connections) await connection.close();
    }
  });
  it('refuses privileged roles and absent schema without changing ACLs', async () => {
    const original = await planPostgresPermissions(db, contract);
    const absent = { ...contract, schema: 'missing_schema' };
    const plan = await planPostgresPermissions(db, absent);
    expect(
      plan.diagnostics.some((entry) => entry.code === 'missing-schema'),
    ).toBe(true);
    await expect(
      applyPostgresPermissions(db, absent, {
        expectedFingerprint: plan.fingerprint,
      }),
    ).rejects.toThrow('unsupported');
    expect((await planPostgresPermissions(db, contract)).fingerprint).toBe(
      original.fingerprint,
    );
    await db.query(`ALTER ROLE ${q(runtime)} CREATEDB`);
    expect(
      (await planPostgresPermissions(db, contract)).diagnostics.some(
        (entry) => entry.code === 'privileged-role',
      ),
    ).toBe(true);
  });
  it('escapes punctuation safely with legacy string literal settings', async () => {
    const odd = "odd\\'; SELECT 1; --";
    await as(owner, `CREATE SCHEMA ${q(odd)} AUTHORIZATION ${q(owner)}`);
    await as(owner, `CREATE TABLE ${q(odd)}.items(id text)`);
    const weirdContract = { ...contract, schema: odd, monitor: undefined };
    await db.transaction?.(async (tx) => {
      await tx.query('SET LOCAL standard_conforming_strings = off');
      const plan = await planPostgresPermissions(tx, weirdContract);
      expect(plan.canApply, JSON.stringify(plan.diagnostics)).toBe(true);
      expect(
        plan.statements.some((statement) => statement.includes(q(odd))),
      ).toBe(true);
    });
    expect(
      (await db.query("SELECT 1 FROM pg_namespace WHERE nspname='app'")).rows,
    ).toHaveLength(1);
  });
  it('refuses parameter configuration authority from PostgreSQL 15+ ACLs', async () => {
    const version = Number(
      (
        await db.query(
          "SELECT current_setting('server_version_num') AS version",
        )
      ).rows[0].version,
    );
    if (version < 150000) return;
    try {
      await db.query(
        `GRANT ALTER SYSTEM ON PARAMETER log_statement TO ${q(runtime)}`,
      );
      const plan = await planPostgresPermissions(db, contract);
      expect(plan.canApply).toBe(false);
      expect(
        plan.diagnostics.some(
          (entry) =>
            entry.code === 'parameter-privilege' && entry.role === runtime,
        ),
      ).toBe(true);
      await expect(
        applyPostgresPermissions(db, contract, {
          expectedFingerprint: plan.fingerprint,
        }),
      ).rejects.toThrow('unsupported');
    } finally {
      // Parameter ACLs are cluster scoped, so remove this test role's grant.
      await db.query(
        `REVOKE ALTER SYSTEM ON PARAMETER log_statement FROM ${q(runtime)}`,
      );
    }
  });
  it('refuses user routines and standalone composite types after schema evolution', async () => {
    await apply();
    await as(owner, 'CREATE TYPE app.custom AS (value text)');
    await as(
      owner,
      "CREATE FUNCTION app.custom_fn() RETURNS integer LANGUAGE sql AS 'SELECT 1'",
    );
    const result = await planPostgresPermissions(db, contract);
    expect(result.canApply).toBe(false);
    expect(
      result.diagnostics.some((entry) => entry.code === 'unsupported-types'),
    ).toBe(true);
    expect(
      result.diagnostics.some((entry) => entry.code === 'unsupported-routines'),
    ).toBe(true);
  });
});
