// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom collection method: link
export const POST: RequestHandler = async ({ request }) => {
  const collection = (await getCollection<any>(
    '@happyvertical/smrt-content:ContentReference',
  )) as any;
  if (!collection)
    throw error(
      500,
      '@happyvertical/smrt-content:ContentReference collection is not registered',
    );

  const options = await request.json();
  const result = await collection.link(
    options['sourceId'],
    options['targetId'],
    options['tenantId'],
  );

  return json({ action: 'link', result });
};
