/**
 * Test manifest stub
 * This file is generated by `smrt test`
 *
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import type { SmartObjectManifest } from '@happyvertical/smrt-core/scanner';

export const testManifest: SmartObjectManifest = {
  "version": "1.0.0",
  "timestamp": 1762774024562,
  "objects": {
    "profilerelationshipterm": {
      "name": "profilerelationshipterm",
      "className": "ProfileRelationshipTerm",
      "collection": "profilerelationshipterms",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileRelationshipTerm.ts",
      "fields": {
        "relationshipId": {
          "type": "foreignKey",
          "required": true
        },
        "startedAt": {
          "type": "datetime",
          "required": true,
          "options": {
            "required": true
          }
        },
        "endedAt": {
          "type": "datetime",
          "required": true
        }
      },
      "methods": {
        "isActive": {
          "name": "isActive",
          "async": false,
          "parameters": [],
          "returnType": "boolean",
          "isStatic": false,
          "isPublic": true
        },
        "end": {
          "name": "end",
          "async": true,
          "parameters": [
            {
              "name": "endedAt",
              "type": "Date",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "getDurationDays": {
          "name": "getDurationDays",
          "async": false,
          "parameters": [],
          "returnType": "number",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update",
            "delete"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationshipTerm",
      "collectionExportName": "ProfileRelationshipTermCollection"
    },
    "profilerelationshiptermcollection": {
      "name": "profilerelationshiptermcollection",
      "className": "ProfileRelationshipTermCollection",
      "collection": "profilerelationshiptermcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileRelationshipTermCollection.ts",
      "fields": {},
      "methods": {
        "getByRelationship": {
          "name": "getByRelationship",
          "async": true,
          "parameters": [
            {
              "name": "relationshipId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipTerm[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getActiveTerm": {
          "name": "getActiveTerm",
          "async": true,
          "parameters": [
            {
              "name": "relationshipId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipTerm | null>",
          "isStatic": false,
          "isPublic": true
        },
        "getHistoricalTerms": {
          "name": "getHistoricalTerms",
          "async": true,
          "parameters": [
            {
              "name": "relationshipId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipTerm[]>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationshipTermCollection",
      "collectionExportName": "ProfileRelationshipTermCollectionCollection"
    },
    "profilerelationship": {
      "name": "profilerelationship",
      "className": "ProfileRelationship",
      "collection": "profilerelationships",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileRelationship.ts",
      "fields": {
        "fromProfileId": {
          "type": "foreignKey",
          "required": true
        },
        "toProfileId": {
          "type": "foreignKey",
          "required": true
        },
        "typeId": {
          "type": "foreignKey",
          "required": true
        },
        "contextProfileId": {
          "type": "foreignKey",
          "required": true
        },
        "terms": {
          "type": "oneToMany",
          "required": true
        }
      },
      "methods": {
        "getTypeSlug": {
          "name": "getTypeSlug",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        },
        "addTerm": {
          "name": "addTerm",
          "async": true,
          "parameters": [
            {
              "name": "startedAt",
              "type": "Date",
              "optional": false
            },
            {
              "name": "endedAt",
              "type": "Date",
              "optional": true
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "endCurrentTerm": {
          "name": "endCurrentTerm",
          "async": true,
          "parameters": [
            {
              "name": "endedAt",
              "type": "Date",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "getTerms": {
          "name": "getTerms",
          "async": true,
          "parameters": [],
          "returnType": "Promise<ProfileRelationshipTerm[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getActiveTerm": {
          "name": "getActiveTerm",
          "async": true,
          "parameters": [],
          "returnType": "Promise<ProfileRelationshipTerm | null>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "delete"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationship",
      "collectionExportName": "ProfileRelationshipCollection"
    },
    "profiletype": {
      "name": "profiletype",
      "className": "ProfileType",
      "collection": "profiletypes",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileType.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "description": {
          "type": "text",
          "required": false
        }
      },
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "_slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileType | null>",
          "isStatic": true,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileType",
      "collectionExportName": "ProfileTypeCollection"
    },
    "profilemetafield": {
      "name": "profilemetafield",
      "className": "ProfileMetafield",
      "collection": "profilemetafields",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileMetafield.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "description": {
          "type": "text",
          "required": false
        },
        "validation": {
          "type": "json",
          "required": false
        }
      },
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "_slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileMetafield | null>",
          "isStatic": true,
          "isPublic": true
        },
        "registerValidator": {
          "name": "registerValidator",
          "async": false,
          "parameters": [
            {
              "name": "name",
              "type": "string",
              "optional": false
            },
            {
              "name": "validator",
              "type": "ValidatorFunction",
              "optional": false
            }
          ],
          "returnType": "void",
          "isStatic": true,
          "isPublic": true
        },
        "getValidator": {
          "name": "getValidator",
          "async": false,
          "parameters": [
            {
              "name": "name",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "ValidatorFunction | undefined",
          "isStatic": true,
          "isPublic": true
        },
        "validateValue": {
          "name": "validateValue",
          "async": true,
          "parameters": [
            {
              "name": "value",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<boolean>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileMetafield",
      "collectionExportName": "ProfileMetafieldCollection"
    },
    "profilemetafieldcollection": {
      "name": "profilemetafieldcollection",
      "className": "ProfileMetafieldCollection",
      "collection": "profilemetafieldcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileMetafieldCollection.ts",
      "fields": {},
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileMetafield | null>",
          "isStatic": false,
          "isPublic": true
        },
        "getOrCreateBySlug": {
          "name": "getOrCreateBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            },
            {
              "name": "defaults",
              "type": "{\n      name: string;\n      description?: string;\n      validation?: ValidationSchema;\n    }",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileMetafield>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileMetafieldCollection",
      "collectionExportName": "ProfileMetafieldCollectionCollection"
    },
    "profilemetadata": {
      "name": "profilemetadata",
      "className": "ProfileMetadata",
      "collection": "profilemetadatas",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileMetadata.ts",
      "fields": {
        "profileId": {
          "type": "foreignKey",
          "required": true
        },
        "metafieldId": {
          "type": "foreignKey",
          "required": true
        },
        "value": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        }
      },
      "methods": {
        "validate": {
          "name": "validate",
          "async": true,
          "parameters": [],
          "returnType": "Promise<boolean>",
          "isStatic": false,
          "isPublic": true
        },
        "getMetafieldSlug": {
          "name": "getMetafieldSlug",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update",
            "delete"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileMetadata",
      "collectionExportName": "ProfileMetadataCollection"
    },
    "profilemetadatacollection": {
      "name": "profilemetadatacollection",
      "className": "ProfileMetadataCollection",
      "collection": "profilemetadatacollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileMetadataCollection.ts",
      "fields": {},
      "methods": {
        "getByProfile": {
          "name": "getByProfile",
          "async": true,
          "parameters": [
            {
              "name": "profileId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileMetadata[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getMetadataObject": {
          "name": "getMetadataObject",
          "async": true,
          "parameters": [
            {
              "name": "profileId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<Record<string, any>>",
          "isStatic": false,
          "isPublic": true
        },
        "findProfilesByMetadata": {
          "name": "findProfilesByMetadata",
          "async": true,
          "parameters": [
            {
              "name": "metafieldId",
              "type": "string",
              "optional": false
            },
            {
              "name": "value",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<string[]>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileMetadataCollection",
      "collectionExportName": "ProfileMetadataCollectionCollection"
    },
    "profilerelationshiptype": {
      "name": "profilerelationshiptype",
      "className": "ProfileRelationshipType",
      "collection": "profilerelationshiptypes",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/ProfileRelationshipType.ts",
      "fields": {
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "reciprocal": {
          "type": "boolean",
          "required": true,
          "options": {
            "default": true
          }
        }
      },
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "_slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipType | null>",
          "isStatic": true,
          "isPublic": true
        },
        "registerReciprocalHandler": {
          "name": "registerReciprocalHandler",
          "async": false,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            },
            {
              "name": "handler",
              "type": "ReciprocalHandler",
              "optional": false
            }
          ],
          "returnType": "void",
          "isStatic": true,
          "isPublic": true
        },
        "getReciprocalHandler": {
          "name": "getReciprocalHandler",
          "async": false,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "ReciprocalHandler | undefined",
          "isStatic": true,
          "isPublic": true
        },
        "isReciprocal": {
          "name": "isReciprocal",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<boolean>",
          "isStatic": true,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationshipType",
      "collectionExportName": "ProfileRelationshipTypeCollection"
    },
    "profilerelationshiptypecollection": {
      "name": "profilerelationshiptypecollection",
      "className": "ProfileRelationshipTypeCollection",
      "collection": "profilerelationshiptypecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileRelationshipTypeCollection.ts",
      "fields": {},
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipType | null>",
          "isStatic": false,
          "isPublic": true
        },
        "getOrCreateBySlug": {
          "name": "getOrCreateBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            },
            {
              "name": "defaults",
              "type": "{ name: string; reciprocal?: boolean }",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileRelationshipType>",
          "isStatic": false,
          "isPublic": true
        },
        "getReciprocal": {
          "name": "getReciprocal",
          "async": true,
          "parameters": [],
          "returnType": "Promise<ProfileRelationshipType[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getDirectional": {
          "name": "getDirectional",
          "async": true,
          "parameters": [],
          "returnType": "Promise<ProfileRelationshipType[]>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationshipTypeCollection",
      "collectionExportName": "ProfileRelationshipTypeCollectionCollection"
    },
    "profilerelationshipcollection": {
      "name": "profilerelationshipcollection",
      "className": "ProfileRelationshipCollection",
      "collection": "profilerelationshipcollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileRelationshipCollection.ts",
      "fields": {},
      "methods": {
        "getFromProfile": {
          "name": "getFromProfile",
          "async": true,
          "parameters": [
            {
              "name": "fromProfileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "typeId",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<ProfileRelationship[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getToProfile": {
          "name": "getToProfile",
          "async": true,
          "parameters": [
            {
              "name": "toProfileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "typeId",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<ProfileRelationship[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getForProfile": {
          "name": "getForProfile",
          "async": true,
          "parameters": [
            {
              "name": "profileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "typeId",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<ProfileRelationship[]>",
          "isStatic": false,
          "isPublic": true
        },
        "exists": {
          "name": "exists",
          "async": true,
          "parameters": [
            {
              "name": "fromProfileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "toProfileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "typeId",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<boolean>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileRelationshipCollection",
      "collectionExportName": "ProfileRelationshipCollectionCollection"
    },
    "profile": {
      "name": "profile",
      "className": "Profile",
      "collection": "profiles",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/models/Profile.ts",
      "fields": {
        "typeId": {
          "type": "foreignKey",
          "required": true
        },
        "email": {
          "type": "text",
          "required": false,
          "options": {
            "unique": true
          }
        },
        "name": {
          "type": "text",
          "required": true,
          "options": {
            "required": true
          }
        },
        "description": {
          "type": "text",
          "required": false
        },
        "metadata": {
          "type": "oneToMany",
          "required": true
        },
        "relationshipsFrom": {
          "type": "oneToMany",
          "required": true
        },
        "relationshipsTo": {
          "type": "oneToMany",
          "required": true
        }
      },
      "methods": {
        "getTypeSlug": {
          "name": "getTypeSlug",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        },
        "setTypeBySlug": {
          "name": "setTypeBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "addMetadata": {
          "name": "addMetadata",
          "async": true,
          "parameters": [
            {
              "name": "metafieldSlug",
              "type": "string",
              "optional": false
            },
            {
              "name": "value",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "getMetadata": {
          "name": "getMetadata",
          "async": true,
          "parameters": [],
          "returnType": "Promise<Record<string, any>>",
          "isStatic": false,
          "isPublic": true
        },
        "updateMetadata": {
          "name": "updateMetadata",
          "async": true,
          "parameters": [
            {
              "name": "metadata",
              "type": "Record<string, any>",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "removeMetadata": {
          "name": "removeMetadata",
          "async": true,
          "parameters": [
            {
              "name": "metafieldSlug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "addRelationship": {
          "name": "addRelationship",
          "async": true,
          "parameters": [
            {
              "name": "toProfile",
              "type": "Profile",
              "optional": false
            },
            {
              "name": "relationshipSlug",
              "type": "string",
              "optional": false
            },
            {
              "name": "contextProfile",
              "type": "Profile",
              "optional": true
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "getRelationships": {
          "name": "getRelationships",
          "async": true,
          "parameters": [
            {
              "name": "options",
              "type": "{\n    typeSlug?: string;\n    direction?: 'from' | 'to' | 'all';\n  }",
              "optional": true
            }
          ],
          "returnType": "Promise<ProfileRelationship[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getRelatedProfiles": {
          "name": "getRelatedProfiles",
          "async": true,
          "parameters": [
            {
              "name": "relationshipSlug",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": false,
          "isPublic": true
        },
        "removeRelationship": {
          "name": "removeRelationship",
          "async": true,
          "parameters": [
            {
              "name": "toProfile",
              "type": "Profile",
              "optional": false
            },
            {
              "name": "relationshipSlug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "generateBio": {
          "name": "generateBio",
          "async": true,
          "parameters": [],
          "returnType": "Promise<string>",
          "isStatic": false,
          "isPublic": true
        },
        "matches": {
          "name": "matches",
          "async": true,
          "parameters": [
            {
              "name": "criteria",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<boolean>",
          "isStatic": false,
          "isPublic": true
        },
        "findByMetadata": {
          "name": "findByMetadata",
          "async": true,
          "parameters": [
            {
              "name": "_metafieldSlug",
              "type": "string",
              "optional": false
            },
            {
              "name": "_value",
              "type": "any",
              "optional": false
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": true,
          "isPublic": true
        },
        "findByType": {
          "name": "findByType",
          "async": true,
          "parameters": [
            {
              "name": "_typeSlug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": true,
          "isPublic": true
        },
        "findRelated": {
          "name": "findRelated",
          "async": true,
          "parameters": [
            {
              "name": "_profileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "_relationshipSlug",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": true,
          "isPublic": true
        },
        "searchByEmail": {
          "name": "searchByEmail",
          "async": true,
          "parameters": [
            {
              "name": "_email",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<Profile | null>",
          "isStatic": true,
          "isPublic": true
        }
      },
      "decoratorConfig": {
        "api": {
          "include": [
            "list",
            "get",
            "create",
            "update",
            "delete"
          ]
        },
        "mcp": {
          "include": [
            "list",
            "get",
            "create",
            "update"
          ]
        },
        "cli": true
      },
      "extends": "SmrtObject",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "Profile",
      "collectionExportName": "ProfileCollection"
    },
    "profilecollection": {
      "name": "profilecollection",
      "className": "ProfileCollection",
      "collection": "profilecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileCollection.ts",
      "fields": {},
      "methods": {
        "findByType": {
          "name": "findByType",
          "async": true,
          "parameters": [
            {
              "name": "typeSlug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": false,
          "isPublic": true
        },
        "batchGetMetadata": {
          "name": "batchGetMetadata",
          "async": true,
          "parameters": [
            {
              "name": "profileIds",
              "type": "string[]",
              "optional": false
            }
          ],
          "returnType": "Promise<Map<string, Record<string, any>>>",
          "isStatic": false,
          "isPublic": true
        },
        "batchUpdateMetadata": {
          "name": "batchUpdateMetadata",
          "async": true,
          "parameters": [
            {
              "name": "updates",
              "type": "Array<{ profileId: string; data: Record<string, any> }>",
              "optional": false
            }
          ],
          "returnType": "Promise<void>",
          "isStatic": false,
          "isPublic": true
        },
        "findRelated": {
          "name": "findRelated",
          "async": true,
          "parameters": [
            {
              "name": "profileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "relationshipSlug",
              "type": "string",
              "optional": true
            }
          ],
          "returnType": "Promise<Profile[]>",
          "isStatic": false,
          "isPublic": true
        },
        "getRelationshipNetwork": {
          "name": "getRelationshipNetwork",
          "async": true,
          "parameters": [
            {
              "name": "profileId",
              "type": "string",
              "optional": false
            },
            {
              "name": "options",
              "type": "{ maxDepth?: number }",
              "optional": false,
              "default": {}
            }
          ],
          "returnType": "Promise<Map<string, number>>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileCollection",
      "collectionExportName": "ProfileCollectionCollection"
    },
    "profiletypecollection": {
      "name": "profiletypecollection",
      "className": "ProfileTypeCollection",
      "collection": "profiletypecollections",
      "filePath": "/Users/will/Work/happyvertical/repos/smrt/packages/profiles/src/collections/ProfileTypeCollection.ts",
      "fields": {},
      "methods": {
        "getBySlug": {
          "name": "getBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileType | null>",
          "isStatic": false,
          "isPublic": true
        },
        "getOrCreateBySlug": {
          "name": "getOrCreateBySlug",
          "async": true,
          "parameters": [
            {
              "name": "slug",
              "type": "string",
              "optional": false
            },
            {
              "name": "defaults",
              "type": "{ name: string; description?: string }",
              "optional": false
            }
          ],
          "returnType": "Promise<ProfileType>",
          "isStatic": false,
          "isPublic": true
        }
      },
      "decoratorConfig": {},
      "extends": "SmrtCollection",
      "packageName": "@happyvertical/smrt-profiles",
      "exportName": "ProfileTypeCollection",
      "collectionExportName": "ProfileTypeCollectionCollection"
    }
  },
  "packageName": "@happyvertical/smrt-profiles"
} as const;

export default testManifest;
