// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom collection method: getBySlug
export const GET: RequestHandler = async ({ request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:Content',
  );
  const typedCollection = collection as any;
  if (!collection)
    throw error(
      500,
      '@happyvertical/smrt-content:Content collection is not registered',
    );

  const options = Object.fromEntries(
    new URL(request.url).searchParams.entries(),
  );
  const result = await typedCollection.getBySlug(options);

  return json({ action: 'getBySlug', result });
};
