// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom action: evaluateReviewProfileAction
export const GET: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:Content',
  );
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const pathParams = {
    profileKey: params.profileKey,
  };
  const options = {
    ...Object.fromEntries(new URL(request.url).searchParams.entries()),
    ...pathParams,
  };
  const result = await item.evaluateReviewProfileAction(options);

  return json({ action: 'evaluateReviewProfileAction', result });
};
