// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';

// Custom action: listReviews
export const GET: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:Content');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const options = Object.fromEntries(new URL(request.url).searchParams.entries());
  const result = await item.listReviews(options);

  return json({ action: 'listReviews', result });
};

// Custom action: runReviewAction
export const POST: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:Content');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const options = await request.json();
  const result = await item.runReviewAction(options);

  return json({ action: 'runReviewAction', result });
};
