
import { ASTScanner, ManifestGenerator } from '@happyvertical/smrt-core/scanner';
import fg from 'fast-glob';
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

async function runScanner() {
  // Scan all source files (models, collections, tests)
  const sourceFiles = fg.sync(['src/**/*.ts'], {
    absolute: true,
    ignore: ['src/**/*.d.ts'],
  });

  if (sourceFiles.length === 0) {
    console.log('[smrt] No source files found');
    return { version: '1.0.0', timestamp: Date.now(), objects: {} };
  }

  console.log(`[smrt] Scanning ${sourceFiles.length} source files...`);

  const scanner = new ASTScanner(sourceFiles, {
    baseClasses: ['SmrtObject', 'SmrtClass', 'SmrtCollection'],
    includePrivateMethods: false,
    includeStaticMethods: true,
    followImports: true,
  });

  const scanResults = scanner.scanFiles();
  const generator = new ManifestGenerator();
  return generator.generateManifest(scanResults);
}

runScanner().then(manifest => {
  // Inject package name from package.json
  try {
    const packageJsonPath = resolve(process.cwd(), 'package.json');
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    manifest.packageName = packageJson.name;
    console.log(`[smrt] Injected package name: ${packageJson.name}`);
  } catch (error) {
    console.warn('[smrt] Warning: Could not read package.json, packageName will be undefined');
  }

  mkdirSync('src/manifest', { recursive: true });
  writeFileSync('src/manifest/test-manifest.json', JSON.stringify(manifest, null, 2));

  const tsContent = `/**
 * Test manifest stub
 * This file is replaced by generate-test-manifest.js during pretest
 * If tests run without pretest, this empty manifest is used
 *
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

import type { SmartObjectManifest } from '@happyvertical/smrt-core/scanner';

export const testManifest: SmartObjectManifest = ${JSON.stringify(manifest, null, 2)} as const;

export default testManifest;
`;
  writeFileSync('src/manifest/test-manifest-stub.ts', tsContent);

  const objectCount = Object.keys(manifest.objects).length;
  console.log(`[smrt] Generated test manifest with ${objectCount} objects`);
}).catch(console.error);
