// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom action: previewTransparencyAction
export const GET: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:Content',
  );
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:Content not found');

  const result = await item.previewTransparencyAction();

  return json({ action: 'previewTransparencyAction', result });
};
