import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: '@smrt/types',
      link: { type: 'doc', id: 'types' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/types#overview' },
        { type: 'link', label: 'Features', href: '/types#features' },
        { type: 'link', label: 'Installation', href: '/types#installation' },
        { type: 'link', label: 'Usage', href: '/types#usage' },
        { type: 'link', label: 'Signal Interface', href: '/types#signal-interface' },
        { type: 'link', label: 'Signal Lifecycle', href: '/types#signal-lifecycle' },
        { type: 'link', label: '📚 API Reference', href: '/api/types/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/core',
      link: { type: 'doc', id: 'core' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/core#overview' },
        { type: 'link', label: 'Key Features', href: '/core#key-features' },
        { type: 'link', label: 'Installation', href: '/core#installation' },
        { type: 'link', label: 'Usage', href: '/core#usage' },
        { type: 'link', label: 'Code Generation', href: '/core#code-generation' },
        { type: 'link', label: 'SMRT Advisor for Claude Code', href: '/core#smrt-advisor-for-claude-code' },
        { type: 'link', label: '📚 API Reference', href: '/api/core/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/accounts',
      link: { type: 'doc', id: 'accounts' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/accounts#overview' },
        { type: 'link', label: 'Features', href: '/accounts#features' },
        { type: 'link', label: 'Installation', href: '/accounts#installation' },
        { type: 'link', label: 'Usage', href: '/accounts#usage' },
        { type: 'link', label: 'API Reference', href: '/accounts#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/accounts/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/agents',
      link: { type: 'doc', id: 'agents' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/agents#overview' },
        { type: 'link', label: 'Features', href: '/agents#features' },
        { type: 'link', label: 'Installation', href: '/agents#installation' },
        { type: 'link', label: 'Usage', href: '/agents#usage' },
        { type: 'link', label: 'API Reference', href: '/agents#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/agents/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/assets',
      link: { type: 'doc', id: 'assets' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/assets#overview' },
        { type: 'link', label: 'Features', href: '/assets#features' },
        { type: 'link', label: 'Installation', href: '/assets#installation' },
        { type: 'link', label: 'Quick Start', href: '/assets#quick-start' },
        { type: 'link', label: 'Usage', href: '/assets#usage' },
        { type: 'link', label: 'Advanced Usage', href: '/assets#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/assets/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/content',
      link: { type: 'doc', id: 'content' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/content#overview' },
        { type: 'link', label: 'Features', href: '/content#features' },
        { type: 'link', label: 'Installation', href: '/content#installation' },
        { type: 'link', label: 'Quick Start', href: '/content#quick-start' },
        { type: 'link', label: 'Usage', href: '/content#usage' },
        { type: 'link', label: 'REST API Server', href: '/content#rest-api-server' },
        { type: 'link', label: '📚 API Reference', href: '/api/content/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/events',
      link: { type: 'doc', id: 'events' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/events#overview' },
        { type: 'link', label: 'Features', href: '/events#features' },
        { type: 'link', label: 'Installation', href: '/events#installation' },
        { type: 'link', label: 'Quick Start', href: '/events#quick-start' },
        { type: 'link', label: 'API Reference', href: '/events#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/events/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/gnode',
      link: { type: 'doc', id: 'gnode' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/gnode#overview' },
        { type: 'link', label: 'Installation', href: '/gnode#installation' },
        { type: 'link', label: 'Usage', href: '/gnode#usage' },
        { type: 'link', label: 'Features', href: '/gnode#features' },
        { type: 'link', label: 'Documentation', href: '/gnode#documentation' },
        { type: 'link', label: 'Related Packages', href: '/gnode#related-packages' },
        { type: 'link', label: '📚 API Reference', href: '/api/gnode/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/places',
      link: { type: 'doc', id: 'places' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/places#overview' },
        { type: 'link', label: 'Features', href: '/places#features' },
        { type: 'link', label: 'Installation', href: '/places#installation' },
        { type: 'link', label: 'Quick Start', href: '/places#quick-start' },
        { type: 'link', label: 'Advanced Usage', href: '/places#advanced-usage' },
        { type: 'link', label: 'TypeScript Support', href: '/places#typescript-support' },
        { type: 'link', label: '📚 API Reference', href: '/api/places/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/products',
      link: { type: 'doc', id: 'products' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Quick Start', href: '/products#quick-start' },
        { type: 'link', label: 'Three Ways to Use This Service', href: '/products#three-ways-to-use-this-service' },
        { type: 'link', label: 'What\'s Auto-Generated', href: '/products#whats-auto-generated' },
        { type: 'link', label: 'Project Structure', href: '/products#project-structure' },
        { type: 'link', label: 'Development Commands', href: '/products#development-commands' },
        { type: 'link', label: 'How It Works', href: '/products#how-it-works' },
        { type: 'link', label: '📚 API Reference', href: '/api/products/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/profiles',
      link: { type: 'doc', id: 'profiles' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/profiles#overview' },
        { type: 'link', label: 'Features', href: '/profiles#features' },
        { type: 'link', label: 'Installation', href: '/profiles#installation' },
        { type: 'link', label: 'Quick Start', href: '/profiles#quick-start' },
        { type: 'link', label: 'Data Model', href: '/profiles#data-model' },
        { type: 'link', label: 'Advanced Usage', href: '/profiles#advanced-usage' },
        { type: 'link', label: '📚 API Reference', href: '/api/profiles/globals' },
      ],
    },
    {
      type: 'category',
      label: '@smrt/tags',
      link: { type: 'doc', id: 'tags' },
      collapsed: true,
      items: [
        { type: 'link', label: 'Overview', href: '/tags#overview' },
        { type: 'link', label: 'Features', href: '/tags#features' },
        { type: 'link', label: 'Installation', href: '/tags#installation' },
        { type: 'link', label: 'Usage', href: '/tags#usage' },
        { type: 'link', label: 'API Reference', href: '/tags#api-reference' },
        { type: 'link', label: '📚 API Reference', href: '/api/tags/globals' },
      ],
    },
  ],
};

export default sidebars;
