import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    { type: 'doc', id: 'index', label: 'Introduction' },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        { type: 'doc', id: 'app-cli' },
        { type: 'doc', id: 'data-compartmentalization' },
        { type: 'doc', id: 'dispatch' },
        { type: 'doc', id: 'field-policies' },
        { type: 'doc', id: 'm5-reference-fixture' },
        { type: 'doc', id: 'runtime-profiles' },
        { type: 'doc', id: 'webmcp-integration' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Standards and decisions',
      collapsed: true,
      items: [
        { type: 'doc', id: 'standards' },
        { type: 'doc', id: 'PROJECT_REQUIREMENTS' },
        { type: 'doc', id: 'STYLE_GUIDE' },
        { type: 'autogenerated', dirName: 'adr' },
        { type: 'autogenerated', dirName: 'rfcs' },
      ],
    },
    {
      type: 'category',
      label: 'Packages',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'packages' }],
    },
  ],
};

export default sidebars;
