// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';

// Get single contentcorrection
export const GET: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:ContentCorrection');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:ContentCorrection not found');

  return json(item);
};

// Update contentcorrection
export const PUT: RequestHandler = async ({ params, request }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:ContentCorrection');
  const item = await collection.get(params.id);
  if (!item) throw error(404, '@happyvertical/smrt-content:ContentCorrection not found');

  const data = await request.json();
  Object.assign(item, data);
  await item.save();

  return json(item);
};
