// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { getCollection } from '$lib/server/smrt';

// Custom collection method: getLatestForContent
export const POST: RequestHandler = async ({ request }) => {
  const collection = await getCollection<any>('@happyvertical/smrt-content:ContentReview') as any;
  if (!collection) throw error(500, '@happyvertical/smrt-content:ContentReview collection is not registered');

  const options = await request.json();
  const result = await collection.getLatestForContent(options["contentId"], options["kind"])

  return json({ action: 'getLatestForContent', result });
};
