/**
 * Header marking a route file as generated by the SMRT vite plugin.
 *
 * Shared by every route emitter (`sveltekit-generator.ts`,
 * `changes-route.ts`): the cleanup pass deletes exactly the `+server.ts`
 * files that start with this header, so all emitters MUST use the same
 * constant — a divergent copy would orphan generated files.
 */
export const AUTO_GENERATED_ROUTE_HEADER =
  '// Auto-generated by @smrt/core vite plugin';
