/**
 * SvelteKit route auto-generation from SMRT objects
 * Generates real TypeScript files in src/routes/api/ based on discovered SMRT objects
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';
import type {
  ApiConfig,
  ApiCustomRouteConfig,
  ApiHttpMethod,
  ApiSerializerReference,
} from '../registry/types.js';
import type {
  SmartObjectDefinition,
  SmartObjectManifest,
} from '../scanner/types';

export interface SvelteKitOptions {
  enabled: boolean;
  routesDir: string;
  objectsDir: string;
  configPath?: string; // default: 'src/lib/server'
  configFileName?: string; // default: 'smrt.ts'
}

// Keep this aligned with biome.json formatter.lineWidth.
const BIOME_LINE_WIDTH = 80;
const AUTO_GENERATED_ROUTE_HEADER =
  '// Auto-generated by @smrt/core vite plugin';
const STANDARD_API_ACTIONS = ['list', 'get', 'create', 'update', 'delete'];

interface ResolvedApiActionRouteConfig {
  scope: 'item' | 'collection';
  method: ApiHttpMethod;
  pathSegments: string[];
  pathParamNames: string[];
}

interface GeneratedActionRouteSpec {
  lookupClassName: string;
  actionName: string;
  actionDef: any;
  routeConfig: ResolvedApiActionRouteConfig;
  hostType: 'item' | 'collection';
}

interface ResolvedStandardRouteSerializers {
  importStatements: string[];
  itemSerializerName?: string;
  listItemSerializerName?: string;
}

/**
 * Extract simple class name from potentially qualified name.
 * Qualified names follow the pattern: @scope/package:ClassName
 *
 * Issue #870: Manifests may contain qualified names which generate invalid
 * import statements like: import { @pkg:Class } from '@pkg'
 *
 * @param qualifiedName - Class name that may be qualified (e.g., "@pkg:Class" or "Class")
 * @returns Simple class name (e.g., "Class")
 */
function extractSimpleClassName(qualifiedName: string): string {
  const colonIndex = qualifiedName.indexOf(':');
  if (colonIndex !== -1) {
    return qualifiedName.substring(colonIndex + 1);
  }
  return qualifiedName;
}

/**
 * Check if an object definition represents a SmrtCollection class.
 * Collection classes share route paths with their item class (via inherited `collection` field),
 * so generating routes for both would cause file collisions.
 */
function isCollectionClass(objectDef: SmartObjectDefinition): boolean {
  return objectDef.extends === 'SmrtCollection' || !!objectDef.extendsTypeArg;
}

function getRegistrationPackageName(
  manifest: SmartObjectManifest,
  objectDef: SmartObjectDefinition,
  isLocal: boolean,
): string | undefined {
  if (isLocal) {
    return manifest.packageName ?? objectDef.packageName;
  }

  return objectDef.packageName;
}

function toSingleQuotedStringLiteral(value: string): string {
  const jsonLiteral = JSON.stringify(value);
  const jsonContent = jsonLiteral.slice(1, -1).replaceAll("'", "\\'");
  return `'${jsonContent}'`;
}

function getApiConfigObject(apiConfig: unknown): ApiConfig | null {
  if (!apiConfig || typeof apiConfig !== 'object') {
    return null;
  }

  return apiConfig as ApiConfig;
}

function isSameSerializerReference(
  left?: ApiSerializerReference,
  right?: ApiSerializerReference,
): boolean {
  return (
    !!left &&
    !!right &&
    left.importPath === right.importPath &&
    left.exportName === right.exportName
  );
}

function resolveStandardRouteSerializers(
  apiConfig: unknown,
): ResolvedStandardRouteSerializers {
  const config = getApiConfigObject(apiConfig);
  const itemSerializer = config?.serializers?.item;
  const listItemSerializer =
    config?.serializers?.listItem || config?.serializers?.item;

  const importStatements: string[] = [];
  let itemSerializerName: string | undefined;
  let listItemSerializerName: string | undefined;

  if (itemSerializer) {
    itemSerializerName = 'serializeItemResponse';
    importStatements.push(
      `import { ${itemSerializer.exportName} as ${itemSerializerName} } from '${itemSerializer.importPath}';`,
    );
  }

  if (listItemSerializer) {
    if (isSameSerializerReference(listItemSerializer, itemSerializer)) {
      listItemSerializerName = itemSerializerName;
    } else {
      listItemSerializerName = 'serializeListItemResponse';
      importStatements.push(
        `import { ${listItemSerializer.exportName} as ${listItemSerializerName} } from '${listItemSerializer.importPath}';`,
      );
    }
  }

  return {
    importStatements,
    itemSerializerName,
    listItemSerializerName,
  };
}

function normalizeApiHttpMethod(method?: string): ApiHttpMethod {
  switch (method?.toUpperCase()) {
    case 'GET':
    case 'POST':
    case 'PUT':
    case 'PATCH':
    case 'DELETE':
      return method.toUpperCase() as ApiHttpMethod;
    default:
      return 'POST';
  }
}

function normalizeCustomRoutePath(actionName: string, path?: string): string[] {
  const normalizedPath = (path || actionName)
    .split('/')
    .map((segment) => segment.trim())
    .filter(Boolean);

  return normalizedPath.length > 0 ? normalizedPath : [actionName];
}

function extractRoutePathParamNames(pathSegments: string[]): string[] {
  return pathSegments
    .filter((segment) => /^\[[^\]]+\]$/.test(segment))
    .map((segment) => segment.slice(1, -1))
    .filter(Boolean);
}

function resolveApiActionRouteConfig(
  actionName: string,
  actionDef: { isStatic?: boolean },
  apiConfig: unknown,
  defaultScope: 'item' | 'collection' = actionDef.isStatic
    ? 'collection'
    : 'item',
): ResolvedApiActionRouteConfig {
  const config = getApiConfigObject(apiConfig);
  const routeConfig: ApiCustomRouteConfig | undefined =
    config?.routes?.[actionName];

  return {
    scope: routeConfig?.scope || defaultScope,
    method: normalizeApiHttpMethod(routeConfig?.method),
    pathSegments: normalizeCustomRoutePath(actionName, routeConfig?.path),
    pathParamNames: extractRoutePathParamNames(
      normalizeCustomRoutePath(actionName, routeConfig?.path),
    ),
  };
}

function buildRouteHandlerArgs(
  includeParams: boolean,
  includeRequest: boolean,
): string {
  const args: string[] = [];

  if (includeParams) {
    args.push('params');
  }

  if (includeRequest) {
    args.push('request');
  }

  return args.length > 0 ? `{ ${args.join(', ')} }` : '';
}

function buildPathParamsObjectLiteral(pathParamNames: string[]): string {
  if (pathParamNames.length === 0) {
    return '{}';
  }

  return `{
${pathParamNames
  .map(
    (paramName) =>
      `    ${JSON.stringify(paramName)}: params[${JSON.stringify(paramName)}],`,
  )
  .join('\n')}
  }`;
}

function buildActionInvocationArgs(actionDef: any): string[] {
  const parameters = Array.isArray(actionDef.parameters)
    ? actionDef.parameters
    : [];

  if (parameters.length === 0) {
    return [];
  }

  if (parameters.length === 1 && parameters[0]?.name === 'options') {
    return ['options'];
  }

  return parameters.map((parameter: any) =>
    buildOptionsPropertyAccess(parameter.name),
  );
}

function buildOptionsPropertyAccess(propertyName: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(propertyName)) {
    return `options.${propertyName}`;
  }

  const escapedPropertyName = propertyName
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'");

  return `options['${escapedPropertyName}']`;
}

function buildActionInvocationExpression(
  receiverExpression: string,
  actionName: string,
  invocationArgs: string[],
): string {
  const singleLineInvocation = `await ${receiverExpression}.${actionName}(${invocationArgs.join(', ')})`;
  const singleLineResultAssignment = `  const result = ${singleLineInvocation};`;

  if (singleLineResultAssignment.length <= 100) {
    return singleLineInvocation;
  }

  return [
    `await ${receiverExpression}.${actionName}(`,
    ...invocationArgs.map((argument) => `    ${argument},`),
    '  )',
  ].join('\n');
}

function findItemClassRegistryKey(
  className: string,
  objectDef: SmartObjectDefinition,
  manifest: SmartObjectManifest,
): string {
  const itemClassName =
    objectDef.extendsTypeArg ||
    (className.endsWith('Collection')
      ? className.slice(0, -'Collection'.length)
      : undefined);

  if (!itemClassName) {
    return className;
  }

  const manifestMatch = Object.entries(manifest.objects).find(
    ([manifestKey, candidate]) =>
      manifestKey === itemClassName || candidate.className === itemClassName,
  );

  return manifestMatch?.[0] || itemClassName;
}

function groupCustomActionRoutes(
  actionSpecs: Array<{
    routeDir: string;
    spec: GeneratedActionRouteSpec;
  }>,
): Map<string, GeneratedActionRouteSpec[]> {
  const groupedRoutes = new Map<string, GeneratedActionRouteSpec[]>();

  for (const { routeDir, spec } of actionSpecs) {
    const existing = groupedRoutes.get(routeDir) || [];
    const duplicateMethod = existing.find(
      (candidate) => candidate.routeConfig.method === spec.routeConfig.method,
    );

    if (duplicateMethod) {
      throw new Error(
        `Duplicate custom API route handler for ${routeDir} (${spec.routeConfig.method}). ` +
          `Methods ${duplicateMethod.actionName} and ${spec.actionName} resolve to the same generated route.`,
      );
    }

    existing.push(spec);
    groupedRoutes.set(routeDir, existing);
  }

  return groupedRoutes;
}

/**
 * Generates SvelteKit API routes from manifest
 */
export async function generateSvelteKitRoutes(
  projectRoot: string,
  manifest: SmartObjectManifest,
  options: SvelteKitOptions,
): Promise<void> {
  if (!options.enabled) return;

  console.log('[smrt] Generating SvelteKit routes...');

  clearGeneratedRouteFiles(join(projectRoot, options.routesDir));

  // Generate centralized configuration file first (if it doesn't exist)
  await generateSmrtConfigFile(projectRoot, manifest, options);

  let generatedCount = 0;
  let skippedCollections = 0;
  for (const [className, objectDef] of Object.entries(manifest.objects)) {
    if (isCollectionClass(objectDef)) {
      const generatedCollectionRoutes = await generateCollectionRoutesForObject(
        projectRoot,
        className,
        objectDef,
        manifest,
        options,
      );
      if (generatedCollectionRoutes) {
        generatedCount++;
      } else {
        console.log(
          `[smrt] Skipping ${className} - no collection API routes to generate`,
        );
        skippedCollections++;
      }
      continue;
    }
    await generateRoutesForObject(projectRoot, className, objectDef, options);
    generatedCount++;
  }

  // Update .gitignore to exclude generated routes
  updateGitignore(projectRoot, options);

  const skippedMsg =
    skippedCollections > 0
      ? ` (skipped ${skippedCollections} collection classes)`
      : '';
  console.log(
    `[smrt] Generated routes for ${generatedCount} SMRT objects${skippedMsg}`,
  );
}

function clearGeneratedRouteFiles(routesRoot: string): void {
  if (!existsSync(routesRoot)) {
    return;
  }

  for (const entry of readdirSync(routesRoot, { withFileTypes: true })) {
    const entryPath = join(routesRoot, entry.name);

    if (entry.isDirectory()) {
      clearGeneratedRouteFiles(entryPath);
      continue;
    }

    if (!entry.isFile() || entry.name !== '+server.ts') {
      continue;
    }

    const fileContent = readFileSync(entryPath, 'utf-8');
    if (fileContent.startsWith(AUTO_GENERATED_ROUTE_HEADER)) {
      unlinkSync(entryPath);
    }
  }
}

/**
 * Generates SMRT object registration file
 * This file imports all SMRT objects to trigger their @smrt() decorators
 */
async function generateRegistrationFile(
  projectRoot: string,
  manifest: SmartObjectManifest,
  options: SvelteKitOptions,
): Promise<void> {
  const configPath = options.configPath || 'src/lib/server';
  const configDir = join(projectRoot, configPath);
  const registrationFilePath = join(configDir, 'smrt-register.ts');

  // Group objects by package for efficient imports
  const localObjects: Array<[string, (typeof manifest.objects)[string]]> = [];
  const packageObjects = new Map<
    string,
    { classNames: string[]; hasCollectionImport: boolean }
  >();

  for (const [className, objectDef] of Object.entries(manifest.objects)) {
    if (isLocalObject(projectRoot, objectDef)) {
      // Local object (source in project, not node_modules) - use $lib path
      localObjects.push([className, objectDef]);
    } else if (objectDef.packageName) {
      // External package - group by package name
      const packageEntry = packageObjects.get(objectDef.packageName) || {
        classNames: [],
        hasCollectionImport: false,
      };

      if (isCollectionClass(objectDef)) {
        packageEntry.hasCollectionImport = true;
      } else {
        packageEntry.classNames.push(className);
      }

      packageObjects.set(objectDef.packageName, packageEntry);
    } else {
      // No package name and not local - treat as local fallback
      localObjects.push([className, objectDef]);
    }
  }

  // Generate imports for local objects
  // Issue #870: Extract simple class names from qualified names
  const localNamedImports = new Map<string, string[]>();
  const localSideEffectImports = new Set<string>();

  for (const [className, objectDef] of localObjects) {
    const simpleClassName = extractSimpleClassName(className);

    // Calculate direct relative path from the configDir where smrt-register.ts lives
    // to the actual source file of the object.
    let importPath = '';
    if (objectDef.filePath) {
      const relativeToConfig = relative(configDir, objectDef.filePath);
      const normalized = relativeToConfig
        .replace(/\\/g, '/')
        .replace(/\.(ts|js|tsx|jsx)$/, '');
      importPath = normalized.startsWith('.') ? normalized : `./${normalized}`;
    } else {
      // Fallback for missing file paths
      importPath = getSvelteKitImportPath(
        projectRoot,
        undefined,
        options.objectsDir,
        simpleClassName,
      );
    }

    if (isCollectionClass(objectDef)) {
      localSideEffectImports.add(importPath);
      continue;
    }

    const existing = localNamedImports.get(importPath) ?? [];
    existing.push(simpleClassName);
    localNamedImports.set(importPath, existing);
  }

  const localImports = [
    ...Array.from(localNamedImports.entries())
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([importPath, simpleNames]) => {
        const sortedNames = simpleNames.sort((a, b) => a.localeCompare(b));
        return `import { ${sortedNames.join(', ')} } from '${importPath}';`;
      }),
    ...Array.from(localSideEffectImports.values())
      .sort((a, b) => a.localeCompare(b))
      .map((importPath) => `import '${importPath}';`),
  ].join('\n');

  // Generate imports for external packages
  // Issue #870: Extract simple class names from qualified names
  const packageImports = Array.from(packageObjects.entries())
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([packageName, packageEntry]) => {
      const imports: string[] = [];

      if (packageEntry.hasCollectionImport) {
        imports.push(`import '${packageName}';`);
      }

      if (packageEntry.classNames.length > 0) {
        // Extract simple class names for valid import syntax
        const simpleNames = packageEntry.classNames
          .map(extractSimpleClassName)
          .sort((a, b) => a.localeCompare(b));
        imports.push(
          `import { ${simpleNames.join(', ')} } from '${packageName}';`,
        );
      }

      return imports;
    })
    .join('\n');

  const imports = [packageImports, localImports].filter(Boolean).join('\n');
  const registrations = Object.entries(manifest.objects)
    .map(([className, objectDef]) => {
      if (isCollectionClass(objectDef)) {
        // Importing the collection class is enough to trigger its decorator.
        // Explicit package-qualified re-registration only applies to object
        // classes, because ObjectRegistry.register() is object-only.
        return null;
      }

      const simpleClassName = extractSimpleClassName(className);
      const localObject = isLocalObject(projectRoot, objectDef);
      const packageName = getRegistrationPackageName(
        manifest,
        objectDef,
        localObject,
      );

      if (!packageName) {
        return null;
      }

      const packageNameLiteral = toSingleQuotedStringLiteral(packageName);
      const singleLineRegistration = `ObjectRegistry.register(${simpleClassName}, { name: '${simpleClassName}', packageName: ${packageNameLiteral} });`;

      if (singleLineRegistration.length <= BIOME_LINE_WIDTH) {
        return singleLineRegistration;
      }

      return [
        `ObjectRegistry.register(${simpleClassName}, {`,
        `  name: '${simpleClassName}',`,
        `  packageName: ${packageNameLiteral},`,
        `});`,
      ].join('\n');
    })
    .filter((registration): registration is string => registration !== null)
    .join('\n');

  const registrationContent = `/**
 * Auto-generated SMRT object registration
 * DO NOT EDIT - changes will be overwritten
 *
 * Importing these modules triggers their @smrt() decorators, which perform
 * the initial registration. The explicit re-registration below is intentional:
 * it upgrades bundled runtimes to deterministic qualified registrations.
 */

import { ObjectRegistry } from '@happyvertical/smrt-core';

${imports}

// Re-register imported objects with explicit package names for bundled runtimes
${registrations}
`;

  // Create directory if it doesn't exist
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  writeFileSync(registrationFilePath, registrationContent, 'utf-8');
  console.log(`[smrt] Generated registration file: ${registrationFilePath}`);
}

/**
 * Generates centralized SMRT configuration file
 * Only creates if file doesn't exist (preserves user customizations)
 */
async function generateSmrtConfigFile(
  projectRoot: string,
  manifest: SmartObjectManifest,
  options: SvelteKitOptions,
): Promise<void> {
  const configPath = options.configPath || 'src/lib/server';
  const configFileName = options.configFileName || 'smrt.ts';
  const configDir = join(projectRoot, configPath);
  const configFilePath = join(configDir, configFileName);

  // Always generate registration file (it gets overwritten)
  await generateRegistrationFile(projectRoot, manifest, options);

  // Don't overwrite existing config file
  if (existsSync(configFilePath)) {
    console.log('[smrt] Config file already exists, skipping generation');
    return;
  }

  const configContent = `/**
 * Centralized SMRT configuration with per-object overrides
 * Generated by @smrt/core vite plugin
 *
 * Most objects will use the default configuration.
 * Add entries to \`objectOverrides\` for objects that need different backends.
 */

// Import SMRT objects to register them via @smrt() decorators
import './smrt-register.js';

import { ObjectRegistry } from '@happyvertical/smrt-core';
import type { SmrtClassOptions } from '@happyvertical/smrt-core';

declare global {
  // eslint-disable-next-line no-var
  var __smrtGetRequestScopedDatabase:
    | (() => SmrtClassOptions['db'] | undefined)
    | undefined;
}

/**
 * Per-object configuration overrides
 * Define specific backends for objects that differ from project defaults
 *
 * @example
 * const objectOverrides: Record<string, Partial<SmrtClassOptions>> = {
 *   // Analytics uses a separate PostgreSQL database
 *   Analytics: {
 *     db: {
 *       url: process.env.ANALYTICS_DATABASE_URL!,
 *       type: 'postgres'
 *     }
 *   },
 *
 *   // AuditLog uses dedicated database with no AI
 *   AuditLog: {
 *     db: {
 *       url: process.env.AUDIT_DATABASE_URL!,
 *       type: 'postgres'
 *     },
 *     ai: undefined
 *   },
 *
 *   // Cache uses REST adapter (e.g., Redis)
 *   Cache: {
 *     persistence: {
 *       type: 'rest',
 *       baseUrl: process.env.REDIS_URL!
 *     }
 *   }
 * };
 */
const objectOverrides: Record<string, Partial<SmrtClassOptions>> = {
  // Add your per-object configuration overrides here
};

/**
 * Default configuration for most SMRT objects
 * Customize this to change project-wide defaults
 */
function getDefaultConfig(): SmrtClassOptions {
  return {
    db: {
      url: process.env.DATABASE_URL || ':memory:',
      type: (process.env.DATABASE_TYPE as 'sqlite' | 'postgres') || 'sqlite'
    },
    ai: process.env.OPENAI_API_KEY ? {
      type: 'openai',
      apiKey: process.env.OPENAI_API_KEY
    } : process.env.ANTHROPIC_API_KEY ? {
      type: 'anthropic',
      apiKey: process.env.ANTHROPIC_API_KEY
    } : undefined
  };
}

function getRequestScopedDatabase(): SmrtClassOptions['db'] | undefined {
  const getter = globalThis.__smrtGetRequestScopedDatabase;
  return typeof getter === 'function' ? getter() : undefined;
}

/**
 * Get configuration for a specific SMRT object
 * Merges project defaults with per-object overrides if defined
 */
export function getSmrtConfig(className: string): SmrtClassOptions {
  const defaults = getDefaultConfig();
  const override = objectOverrides[className];

  if (override) {
    // Deep merge: override specific properties while keeping defaults
    return {
      ...defaults,
      ...override,
      // Ensure nested objects are merged properly
      db: override.db
        ? { ...(defaults.db as any), ...(override.db as any) }
        : defaults.db,
      ai: override.ai !== undefined ? override.ai : defaults.ai
    };
  }

  return defaults;
}

/**
 * Helper to get a collection with centralized configuration
 * Automatically applies project defaults or object-specific overrides
 */
export async function getCollection<
  T extends import('@happyvertical/smrt-core').SmrtObject,
>(className: string, overrides: Partial<SmrtClassOptions> = {}) {
  const config = getSmrtConfig(className);
  const objectOverride = objectOverrides[className];
  const requestScopedDb =
    !overrides.db && !objectOverride?.db
      ? getRequestScopedDatabase()
      : undefined;

  return await ObjectRegistry.getCollection<T>(
    className,
    {
      ...config,
      ...overrides,
      db: overrides.db
        ? { ...(config.db as any), ...(overrides.db as any) }
        : requestScopedDb ?? config.db,
      ai: overrides.ai !== undefined ? overrides.ai : config.ai
    }
  );
}
`;

  // Create directory if it doesn't exist
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  writeFileSync(configFilePath, configContent, 'utf-8');
  console.log(`[smrt] Generated configuration file: ${configFilePath}`);
}

/**
 * Generates route files for a single SMRT object
 */
async function generateRoutesForObject(
  projectRoot: string,
  className: string,
  objectDef: SmartObjectDefinition,
  options: SvelteKitOptions,
): Promise<void> {
  const collectionName = objectDef.collection;
  const routeDir = join(projectRoot, options.routesDir, collectionName);

  // Check if API is enabled for this object
  const apiConfig = objectDef.decoratorConfig?.api;
  if (apiConfig === false) {
    console.log(`[smrt] Skipping ${className} - API disabled`);
    return;
  }

  // Determine which actions to include
  let includedActions: string[] = [];

  if (apiConfig === true || apiConfig === undefined) {
    // Include all standard actions by default
    includedActions = [...STANDARD_API_ACTIONS];
  } else if (typeof apiConfig === 'object') {
    if (apiConfig.include) {
      includedActions = apiConfig.include.filter((action) =>
        STANDARD_API_ACTIONS.includes(action),
      );
    } else {
      includedActions = [...STANDARD_API_ACTIONS];
    }

    if (apiConfig.exclude && Array.isArray(apiConfig.exclude)) {
      includedActions = includedActions.filter(
        (action) => !apiConfig.exclude?.includes(action),
      );
    }
  }

  // Generate collection route (list, create)
  if (includedActions.includes('list') || includedActions.includes('create')) {
    const collectionRoute = generateCollectionRouteTemplate(
      projectRoot,
      className,
      objectDef,
      includedActions,
      options,
    );
    writeRoute(routeDir, '+server.ts', collectionRoute);
  }

  // Generate item route (get, update, delete)
  if (
    includedActions.includes('get') ||
    includedActions.includes('update') ||
    includedActions.includes('delete')
  ) {
    const itemRoute = generateItemRouteTemplate(
      projectRoot,
      className,
      objectDef,
      includedActions,
      options,
    );
    writeRoute(join(routeDir, '[id]'), '+server.ts', itemRoute);
  }

  // Generate custom action routes
  const customActions = Object.entries(objectDef.methods).filter(
    ([name, method]) =>
      !STANDARD_API_ACTIONS.includes(name) &&
      method.isPublic &&
      shouldIncludeInApi(name, apiConfig),
  );

  const actionSpecs: Array<{
    routeDir: string;
    spec: GeneratedActionRouteSpec;
  }> = [];

  for (const [actionName, actionDef] of customActions) {
    const routeConfig = resolveApiActionRouteConfig(
      actionName,
      actionDef,
      apiConfig,
    );

    if (routeConfig.scope === 'collection' && !actionDef.isStatic) {
      console.warn(
        `[smrt] Skipping ${className}.${actionName} - collection API routes require a static method`,
      );
      continue;
    }

    const actionBaseDir =
      routeConfig.scope === 'collection' ? routeDir : join(routeDir, '[id]');
    actionSpecs.push({
      routeDir: join(actionBaseDir, ...routeConfig.pathSegments),
      spec: {
        lookupClassName: className,
        actionName,
        actionDef,
        routeConfig,
        hostType: 'item',
      },
    });
  }

  for (const [actionRouteDir, routeSpecs] of groupCustomActionRoutes(
    actionSpecs,
  )) {
    const actionRoute = generateActionRouteTemplate(
      projectRoot,
      routeSpecs,
      objectDef,
      options,
    );
    writeRoute(actionRouteDir, '+server.ts', actionRoute);
  }
}

async function generateCollectionRoutesForObject(
  projectRoot: string,
  className: string,
  objectDef: SmartObjectDefinition,
  manifest: SmartObjectManifest,
  options: SvelteKitOptions,
): Promise<boolean> {
  const apiConfig = objectDef.decoratorConfig?.api;
  if (apiConfig === false) {
    console.log(`[smrt] Skipping ${className} - API disabled`);
    return false;
  }

  const routeDir = join(projectRoot, options.routesDir, objectDef.collection);
  const lookupClassName = findItemClassRegistryKey(
    className,
    objectDef,
    manifest,
  );

  const customActions = Object.entries(objectDef.methods).filter(
    ([name, method]) =>
      !STANDARD_API_ACTIONS.includes(name) &&
      method.isPublic &&
      shouldIncludeInApi(name, apiConfig),
  );

  if (customActions.length === 0) {
    return false;
  }

  let generatedAnyRoutes = false;
  const actionSpecs: Array<{
    routeDir: string;
    spec: GeneratedActionRouteSpec;
  }> = [];

  for (const [actionName, actionDef] of customActions) {
    const routeConfig = resolveApiActionRouteConfig(
      actionName,
      actionDef,
      apiConfig,
      'collection',
    );

    if (routeConfig.scope !== 'collection') {
      console.warn(
        `[smrt] Skipping ${className}.${actionName} - collection class methods only support collection-scoped API routes`,
      );
      continue;
    }

    actionSpecs.push({
      routeDir: join(routeDir, ...routeConfig.pathSegments),
      spec: {
        lookupClassName,
        actionName,
        actionDef,
        routeConfig,
        hostType: 'collection',
      },
    });
  }

  for (const [actionRouteDir, routeSpecs] of groupCustomActionRoutes(
    actionSpecs,
  )) {
    const actionRoute = generateActionRouteTemplate(
      projectRoot,
      routeSpecs,
      objectDef,
      options,
    );
    writeRoute(actionRouteDir, '+server.ts', actionRoute);
    generatedAnyRoutes = true;
  }

  return generatedAnyRoutes;
}

/**
 * Check if a custom action should be included in API
 */
function shouldIncludeInApi(actionName: string, apiConfig: any): boolean {
  if (apiConfig === false) return false;
  if (apiConfig === true || apiConfig === undefined) return true;

  if (typeof apiConfig === 'object') {
    if (apiConfig.include) {
      return apiConfig.include.includes(actionName);
    }
    if (apiConfig.exclude) {
      return !apiConfig.exclude.includes(actionName);
    }
  }

  return true;
}

/**
 * Writes a route file, creating directories as needed
 */
function writeRoute(dir: string, filename: string, content: string): void {
  try {
    // Create directory if needed
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    // Write the file (writeFileSync is synchronous and will throw on failure)
    const filePath = join(dir, filename);
    writeFileSync(filePath, content, 'utf-8');
    console.log(`[smrt] Generated: ${filePath}`);
  } catch (error) {
    console.error(`[smrt] [ERROR] Failed to write route file:`);
    console.error(`[smrt] [ERROR]   Directory: ${dir}`);
    console.error(`[smrt] [ERROR]   Filename: ${filename}`);
    console.error(`[smrt] [ERROR]   Error:`, error);
    throw error;
  }
}

/**
 * Converts absolute file path to SvelteKit $lib alias import
 * For SvelteKit projects, uses $lib alias for better module resolution
 */
function getSvelteKitImportPath(
  projectRoot: string,
  objectFilePath: string | undefined,
  objectsDir: string,
  className?: string,
): string {
  // Handle undefined filePath by generating a default path
  // This allows tests to work without providing explicit file paths
  const filePath =
    objectFilePath ||
    join(projectRoot, objectsDir, `${className || 'Object'}.ts`);

  // Convert objectsDir to absolute path if it's relative
  const absoluteObjectsDir = objectsDir.startsWith('/')
    ? objectsDir
    : join(projectRoot, objectsDir);

  // Get the relative path from objectsDir to the file
  const relativePath = relative(absoluteObjectsDir, filePath);

  // Convert to forward slashes and remove extension
  const normalizedPath = relativePath.replace(/\\/g, '/');
  const withoutExtension = normalizedPath.replace(/\.(ts|js|tsx|jsx)$/, '');

  // If objectsDir is under src/lib, use $lib alias
  if (objectsDir.includes('src/lib')) {
    const libSubpath = objectsDir.split('src/lib')[1] || '';
    const fullPath = libSubpath
      ? `${libSubpath}/${withoutExtension}`
      : withoutExtension;
    return `$lib${fullPath}`.replace(/\/+/g, '/'); // Clean up double slashes
  }

  // Otherwise use relative path (fallback for non-standard layouts)
  return withoutExtension.startsWith('.')
    ? withoutExtension
    : `./${withoutExtension}`;
}

/**
 * Check if an object's source file is local to the project (not in node_modules).
 * The scanner sets packageName for all objects (including local ones from the
 * project's own package.json), so we check the filePath to distinguish.
 */
function isLocalObject(
  projectRoot: string,
  objectDef: SmartObjectDefinition,
): boolean {
  if (!objectDef.filePath) return false;
  return (
    objectDef.filePath.startsWith(projectRoot) &&
    !objectDef.filePath.includes('/node_modules/')
  );
}

/**
 * Generates collection route template (GET list, POST create)
 */
function generateCollectionRouteTemplate(
  _projectRoot: string,
  className: string,
  objectDef: SmartObjectDefinition,
  includedActions: string[],
  _options: SvelteKitOptions,
): string {
  const hasGet = includedActions.includes('list');
  const hasPost = includedActions.includes('create');
  const serializers = resolveStandardRouteSerializers(
    objectDef.decoratorConfig?.api,
  );
  const serializerImports = serializers.importStatements.join('\n');

  const imports = `${AUTO_GENERATED_ROUTE_HEADER}
// DO NOT EDIT - changes will be overwritten

import { json } from '@sveltejs/kit';
${
  serializerImports ? `${serializerImports}\n` : ''
}import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';
// Note: ${className} is auto-registered by the Vite plugin scanner
`;

  const getHandler = hasGet
    ? `
// List all ${className.toLowerCase()}s
export const GET: RequestHandler = async ({ url }) => {
  const limit = Number(url.searchParams.get('limit')) || 50;
  const offset = Number(url.searchParams.get('offset')) || 0;

${generateCollectionLoad(className)}
  const items = await collection.list({ limit, offset });
  const count = await collection.count();
${
  serializers.listItemSerializerName
    ? `
  const serializedItems = await Promise.all(
    items.map((item) => ${serializers.listItemSerializerName}(item)),
  );

  return json({ items: serializedItems, count, limit, offset });`
    : `
  return json({ items, count, limit, offset });`
}
};
`
    : '';

  const postHandler = hasPost
    ? `
// Create new ${className.toLowerCase()}
export const POST: RequestHandler = async ({ request }) => {
  const data = await request.json();

${generateCollectionLoad(className)}
  const item = await collection.create(data);
  await item.save();
${
  serializers.itemSerializerName
    ? `
  const serializedItem = await ${serializers.itemSerializerName}(item);

  return json(serializedItem, { status: 201 });`
    : `
  return json(item, { status: 201 });`
}
};
`
    : '';

  return imports + getHandler + postHandler;
}

function generateCollectionLoad(
  className: string,
  options: { generic?: boolean } = {},
): string {
  const genericSuffix = options.generic ? '<any>' : '';

  return [
    `  const collection = await getCollection${genericSuffix}(`,
    `    '${className}',`,
    '  );',
  ].join('\n');
}

function generateNotFoundError(className: string): string {
  const singleLineNotFoundError = `  if (!item) throw error(404, '${className} not found');`;

  if (singleLineNotFoundError.length <= 100) {
    return singleLineNotFoundError;
  }

  return [
    '  if (!item)',
    '    throw error(',
    '      404,',
    `      '${className} not found',`,
    '    );',
  ].join('\n');
}

function generateCollectionNotRegisteredError(className: string): string {
  return [
    '  if (!collection)',
    '    throw error(',
    '      500,',
    `      '${className} collection is not registered',`,
    '    );',
  ].join('\n');
}

function generateClassNotRegisteredError(className: string): string {
  return [
    '  if (!registered)',
    '    throw error(',
    '      500,',
    `      '${className} is not registered',`,
    '    );',
  ].join('\n');
}

/**
 * Generates item route template (GET, PUT, DELETE)
 */
function generateItemRouteTemplate(
  _projectRoot: string,
  className: string,
  objectDef: SmartObjectDefinition,
  includedActions: string[],
  _options: SvelteKitOptions,
): string {
  const hasGet = includedActions.includes('get');
  const hasPut = includedActions.includes('update');
  const hasDelete = includedActions.includes('delete');
  const simpleClassName = extractSimpleClassName(className);
  const serializers = resolveStandardRouteSerializers(
    objectDef.decoratorConfig?.api,
  );
  const serializerImports = serializers.importStatements.join('\n');

  const imports = `${AUTO_GENERATED_ROUTE_HEADER}
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
${serializerImports ? `${serializerImports}\n` : ''}import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';`;

  const getHandler = hasGet
    ? `
// Get single ${simpleClassName.toLowerCase()}
export const GET: RequestHandler = async ({ params }) => {
${generateCollectionLoad(className, { generic: true })}
  const item = await collection.get(params.id);
${generateNotFoundError(className)}
${
  serializers.itemSerializerName
    ? `
  const serializedItem = await ${serializers.itemSerializerName}(item);

  return json(serializedItem);`
    : `
  return json(item);`
}
};
`
    : '';

  const putHandler = hasPut
    ? `
// Update ${simpleClassName.toLowerCase()}
export const PUT: RequestHandler = async ({ params, request }) => {
${generateCollectionLoad(className, { generic: true })}
  const item = await collection.get(params.id);
${generateNotFoundError(className)}

  const data = await request.json();
  Object.assign(item, data);
  await item.save();
${
  serializers.itemSerializerName
    ? `
  const serializedItem = await ${serializers.itemSerializerName}(item);

  return json(serializedItem);`
    : `
  return json(item);`
}
};
`
    : '';

  const deleteHandler = hasDelete
    ? `
// Delete ${simpleClassName.toLowerCase()}
export const DELETE: RequestHandler = async ({ params }) => {
${generateCollectionLoad(className, { generic: true })}
  const item = await collection.get(params.id);
${generateNotFoundError(className)}

  await item.delete();
  return json({ success: true });
};
`
    : '';

  return imports + getHandler + putHandler + deleteHandler;
}

/**
 * Generates custom action route template
 */
function generateActionRouteTemplate(
  _projectRoot: string,
  routeSpecs: GeneratedActionRouteSpec[],
  _objectDef: SmartObjectDefinition,
  _options: SvelteKitOptions,
): string {
  if (routeSpecs.length === 0) {
    throw new Error('Cannot generate a custom action route without handlers');
  }

  const [firstSpec] = routeSpecs;
  const { lookupClassName, routeConfig, hostType } = firstSpec;

  const hasMixedHosts = routeSpecs.some(
    (spec) =>
      spec.hostType !== hostType ||
      spec.lookupClassName !== lookupClassName ||
      spec.routeConfig.scope !== routeConfig.scope,
  );

  if (hasMixedHosts) {
    throw new Error(
      `Cannot generate mixed custom route handlers for ${lookupClassName}. ` +
        'All handlers sharing a route path must target the same host type and scope.',
    );
  }

  const importBlock =
    hostType === 'collection'
      ? `import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';`
      : routeConfig.scope === 'collection'
        ? `import { error, json } from '@sveltejs/kit';
import { ObjectRegistry } from '@happyvertical/smrt-core';
import type { RequestHandler } from './$types';`
        : `import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';`;

  const handlers = routeSpecs
    .map((spec) =>
      generateActionRouteHandler(
        spec.lookupClassName,
        spec.actionName,
        spec.actionDef,
        spec.routeConfig,
        spec.hostType,
      ),
    )
    .join('\n');

  return `${AUTO_GENERATED_ROUTE_HEADER}
// DO NOT EDIT - changes will be overwritten

${importBlock}

${handlers}`;
}

function generateActionRouteHandler(
  lookupClassName: string,
  actionName: string,
  actionDef: any,
  routeConfig: ResolvedApiActionRouteConfig,
  hostType: 'item' | 'collection',
): string {
  const handlerName = routeConfig.method;
  const hasInput = actionDef.parameters.length > 0;
  const needsRequest = hasInput;
  const invocationArgs = buildActionInvocationArgs(actionDef);
  const hasPathParams = routeConfig.pathParamNames.length > 0;
  const pathParamsObjectLiteral = buildPathParamsObjectLiteral(
    routeConfig.pathParamNames,
  );
  const optionsLoad =
    hasInput && routeConfig.method === 'GET'
      ? hasPathParams
        ? [
            `  const pathParams = ${pathParamsObjectLiteral};`,
            '  const options = {',
            '    ...Object.fromEntries(new URL(request.url).searchParams.entries()),',
            '    ...pathParams,',
            '  };',
            '',
          ].join('\n')
        : [
            '  const options = Object.fromEntries(',
            '    new URL(request.url).searchParams.entries(),',
            '  );',
            '',
          ].join('\n')
      : hasInput
        ? hasPathParams
          ? [
              `  const pathParams = ${pathParamsObjectLiteral};`,
              '  const options = {',
              '    ...(await request.json()),',
              '    ...pathParams,',
              '  };',
              '',
            ].join('\n')
          : '  const options = await request.json();\n'
        : '';
  const collectionHandlerArgs = buildRouteHandlerArgs(
    hasPathParams,
    needsRequest,
  );
  const itemHandlerArgs = buildRouteHandlerArgs(true, needsRequest);

  if (hostType === 'collection') {
    return `// Custom collection method: ${actionName}
export const ${handlerName}: RequestHandler = async (${collectionHandlerArgs}) => {
${generateCollectionLoad(lookupClassName, { generic: true })}
  const typedCollection = collection as any;
${generateCollectionNotRegisteredError(lookupClassName)}

${optionsLoad}  const result = ${buildActionInvocationExpression(
      actionDef.isStatic
        ? '(typedCollection.constructor as any)'
        : 'typedCollection',
      actionName,
      invocationArgs,
    )};

  return json({ action: '${actionName}', result });
};
`;
  }

  if (routeConfig.scope === 'collection') {
    return `// Custom collection action: ${actionName}
export const ${handlerName}: RequestHandler = async (${collectionHandlerArgs}) => {
  const registered = ObjectRegistry.getClass('${lookupClassName}');
${generateClassNotRegisteredError(lookupClassName)}

${optionsLoad}  const ClassRef = registered.constructor as any;
  const result = ${buildActionInvocationExpression(
    'ClassRef',
    actionName,
    invocationArgs,
  )};

  return json({ action: '${actionName}', result });
};
`;
  }

  return `// Custom action: ${actionName}
export const ${handlerName}: RequestHandler = async (${itemHandlerArgs}) => {
${generateCollectionLoad(lookupClassName, { generic: true })}
  const item = await collection.get(params.id);
${generateNotFoundError(lookupClassName)}

${optionsLoad}  const result = ${buildActionInvocationExpression(
    'item',
    actionName,
    invocationArgs,
  )};

  return json({ action: '${actionName}', result });
};
`;
}

/**
 * Updates .gitignore to exclude auto-generated routes
 */
function updateGitignore(projectRoot: string, options: SvelteKitOptions): void {
  const gitignorePath = join(projectRoot, '.gitignore');

  // Patterns to add
  const patternsToAdd = [
    '# SMRT auto-generated routes (from Vite plugin)',
    `${options.routesDir}/**/+server.ts`,
  ];

  // Read existing .gitignore or create empty string
  let gitignoreContent = '';
  if (existsSync(gitignorePath)) {
    gitignoreContent = readFileSync(gitignorePath, 'utf-8');
  }

  // Check if patterns already exist
  let needsUpdate = false;
  const linesToAdd: string[] = [];

  for (const pattern of patternsToAdd) {
    // Skip if pattern already exists (check for exact match or similar)
    if (!gitignoreContent.includes(pattern)) {
      linesToAdd.push(pattern);
      needsUpdate = true;
    }
  }

  if (needsUpdate) {
    // Ensure file ends with newline before adding
    if (gitignoreContent.length > 0 && !gitignoreContent.endsWith('\n')) {
      gitignoreContent += '\n';
    }

    // Add a blank line before our section if file has content
    if (gitignoreContent.length > 0 && !gitignoreContent.endsWith('\n\n')) {
      gitignoreContent += '\n';
    }

    // Add our patterns
    gitignoreContent += `${linesToAdd.join('\n')}\n`;

    writeFileSync(gitignorePath, gitignoreContent, 'utf-8');
    console.log('[smrt] Updated .gitignore with generated route patterns');
  }
}
