/**
 * Tests for the generated SvelteKit sync-apply batch route (#1759): target
 * collection from the manifest, template shape, and file emission — testing
 * the generator, not the generated output's runtime (which delegates to
 * `processSyncApplyBatch`, covered by the core sync tests).
 */

import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import type { SmartObjectManifest } from '../scanner/types';
import {
  collectSyncApplyTargets,
  generateSyncApplyRoute,
  generateSyncApplyRouteTemplate,
} from './sync-apply-route';

function manifestWith(
  objects: Record<string, Record<string, unknown>>,
): SmartObjectManifest {
  return {
    version: '1',
    timestamp: Date.now(),
    objects,
  } as unknown as SmartObjectManifest;
}

const productDef = {
  className: 'Product',
  collection: 'products',
  fields: {
    name: { type: 'text' },
    sku: { type: 'text', readonly: true },
  },
  methods: {},
  decoratorConfig: { api: true },
};

describe('collectSyncApplyTargets', () => {
  it('collects api-enabled objects with their mutating ops and policy data', () => {
    const targets = collectSyncApplyTargets(
      manifestWith({
        Product: productDef,
        Report: {
          className: 'Report',
          collection: 'reports',
          fields: {},
          methods: {},
          decoratorConfig: {
            api: {
              include: ['list', 'get', 'create'],
              public: true,
              writable: ['title'],
            },
            tenantScoped: { mode: 'optional' },
          },
        },
      }),
    );

    expect(targets).toHaveLength(2);
    const product = targets.find((t) => t.segment === 'products');
    expect(product).toMatchObject({
      registryKey: 'Product',
      ops: ['create', 'update', 'delete'],
      readonlyFields: ['sku'],
      writableAllowlist: null,
      publicAccess: false,
      tenantScoped: false,
    });
    const report = targets.find((t) => t.segment === 'reports');
    expect(report).toMatchObject({
      registryKey: 'Report',
      ops: ['create'],
      writableAllowlist: ['title'],
      publicAccess: true,
      tenantScoped: true,
    });
  });

  it('skips api-disabled objects, collection classes, and read-only APIs', () => {
    const targets = collectSyncApplyTargets(
      manifestWith({
        Hidden: {
          className: 'Hidden',
          collection: 'hiddens',
          fields: {},
          methods: {},
          decoratorConfig: { api: false },
        },
        ReadOnly: {
          className: 'ReadOnly',
          collection: 'readonlys',
          fields: {},
          methods: {},
          decoratorConfig: { api: { include: ['list', 'get'] } },
        },
        ProductCollection: {
          className: 'ProductCollection',
          collection: 'products',
          fields: {},
          methods: {},
          decoratorConfig: { api: true },
          extends: 'SmrtCollection',
          extendsTypeArg: 'Product',
        },
      }),
    );
    expect(targets).toHaveLength(0);
  });

  it('keeps qualified manifest keys verbatim so getCollection() resolves unambiguously', () => {
    // Two loaded packages may declare the same simple class name; the
    // generated route must pass the registry key exactly as the generated
    // CRUD routes do (qualified keys stay qualified).
    const targets = collectSyncApplyTargets(
      manifestWith({
        '@happyvertical/smrt-products:Product': productDef,
      }),
    );
    expect(targets[0].registryKey).toBe('@happyvertical/smrt-products:Product');

    const content = generateSyncApplyRouteTemplate(targets);
    expect(content).toContain(
      'registryKey: "@happyvertical/smrt-products:Product"',
    );
  });
});

describe('generateSyncApplyRouteTemplate', () => {
  const targets = collectSyncApplyTargets(
    manifestWith({
      Product: productDef,
      Report: {
        className: 'Report',
        collection: 'reports',
        fields: {},
        methods: {},
        decoratorConfig: {
          api: { include: ['list', 'create'], public: true },
          tenantScoped: { mode: 'optional' },
        },
      },
    }),
  );
  const content = generateSyncApplyRouteTemplate(targets);

  it('marks the file as generated and exports a POST handler', () => {
    expect(
      content.startsWith('// Auto-generated by @smrt/core vite plugin'),
    ).toBe(true);
    expect(content).toContain('export const POST: RequestHandler');
  });

  it('delegates to the shared core engine and policy helper', () => {
    expect(content).toContain('processSyncApplyBatch');
    expect(content).toContain('applySyncWritablePolicy');
    expect(content).toContain("from '@happyvertical/smrt-core'");
    expect(content).toContain("getCollection } from '$lib/server/smrt'");
  });

  it('embeds one target entry per syncable model with its policy data', () => {
    expect(content).toContain('"products": {');
    expect(content).toContain('registryKey: "Product"');
    expect(content).toContain('ops: ["create","update","delete"]');
    expect(content).toContain('readonlyFields: ["sku"]');
    expect(content).toContain('"reports": {');
    expect(content).toContain('ops: ["create"]');
    expect(content).toContain('publicAccess: true');
    expect(content).toContain('getCollection(target.registryKey)');
  });

  it('is fail-closed: requires an authenticated principal unless public', () => {
    expect(content).toContain('hasAuthenticatedPrincipal');
    expect(content).toContain('target.publicAccess === true');
    expect(content).toContain("'auth_required'");
  });

  it('establishes tenant context only when a target is tenant-scoped', () => {
    expect(content).toContain('establishTenantContext(locals);');
    expect(content).toContain("from '@happyvertical/smrt-tenancy'");

    const withoutTenants = generateSyncApplyRouteTemplate(
      collectSyncApplyTargets(manifestWith({ Product: productDef })),
    );
    expect(withoutTenants).not.toContain('establishTenantContext');
    expect(withoutTenants).not.toContain('@happyvertical/smrt-tenancy');
  });
});

describe('generateSyncApplyRoute (file emission)', () => {
  let projectRoot = '';
  const options = {
    enabled: true,
    routesDir: 'src/routes/api',
    objectsDir: 'src/lib/objects',
  };

  beforeEach(() => {
    projectRoot = mkdtempSync(join(tmpdir(), 'smrt-sync-apply-route-'));
  });

  afterEach(() => {
    rmSync(projectRoot, { force: true, recursive: true });
  });

  it('writes {routesDir}/sync/apply/+server.ts for syncable manifests', () => {
    const written = generateSyncApplyRoute(
      projectRoot,
      manifestWith({ Product: productDef }),
      options,
    );
    expect(written).toBe(true);
    const routePath = join(projectRoot, 'src/routes/api/sync/apply/+server.ts');
    expect(existsSync(routePath)).toBe(true);
    expect(readFileSync(routePath, 'utf-8')).toContain('processSyncApplyBatch');
  });

  it('writes nothing when no object is syncable', () => {
    const written = generateSyncApplyRoute(
      projectRoot,
      manifestWith({
        Hidden: {
          className: 'Hidden',
          collection: 'hiddens',
          fields: {},
          methods: {},
          decoratorConfig: { api: false },
        },
      }),
      options,
    );
    expect(written).toBe(false);
    expect(
      existsSync(join(projectRoot, 'src/routes/api/sync/apply/+server.ts')),
    ).toBe(false);
  });

  it('refuses to overwrite a user-authored file at the route path', () => {
    const routeDir = join(projectRoot, 'src/routes/api/sync/apply');
    mkdirSync(routeDir, { recursive: true });
    const routePath = join(routeDir, '+server.ts');
    writeFileSync(routePath, '// hand-written route\n', 'utf-8');

    const written = generateSyncApplyRoute(
      projectRoot,
      manifestWith({ Product: productDef }),
      options,
    );
    expect(written).toBe(false);
    expect(readFileSync(routePath, 'utf-8')).toBe('// hand-written route\n');
  });

  it('overwrites its own previously generated file', () => {
    generateSyncApplyRoute(
      projectRoot,
      manifestWith({ Product: productDef }),
      options,
    );
    const written = generateSyncApplyRoute(
      projectRoot,
      manifestWith({ Product: productDef }),
      options,
    );
    expect(written).toBe(true);
  });
});
