/**
 * SvelteKit generator for the sync-apply batch write route (#1759).
 *
 * Emits ONE route — `{routesDir}/sync/apply/+server.ts` — implementing the
 * shared web/mobile write contract for every syncable model in the manifest
 * (models whose API config exposes at least one of create/update/delete). The
 * generated file is deliberately thin: it maps `object` segments to
 * collections plus per-model policy data, and delegates all batch processing
 * to `processSyncApplyBatch` from `@happyvertical/smrt-core` — the same
 * engine the runtime REST generator uses, so the two transports cannot drift.
 *
 * This lives in its own module (rather than sveltekit-generator.ts) so the
 * shared generator file only needs a one-line registration hook; sibling
 * work (#1757, #1758) touches the same generator files in parallel.
 *
 * Contract documentation: docs/content/architecture/sync-apply-contract.md
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ApiConfig } from '../registry/types.js';
import type {
  SmartObjectDefinition,
  SmartObjectManifest,
} from '../scanner/types';
import type { SvelteKitOptions } from './sveltekit-generator.js';

const AUTO_GENERATED_ROUTE_HEADER =
  '// Auto-generated by @smrt/core vite plugin';

const MUTATING_ACTIONS = ['create', 'update', 'delete'] as const;

type MutatingAction = (typeof MUTATING_ACTIONS)[number];

/** Per-model data embedded into the generated route. */
interface SyncTargetSpec {
  segment: string;
  className: string;
  ops: MutatingAction[];
  readonlyFields: string[];
  writableAllowlist: string[] | null;
  publicAccess: boolean | 'read';
  tenantScoped: boolean;
}

function getApiConfigObject(apiConfig: unknown): ApiConfig | null {
  if (!apiConfig || typeof apiConfig !== 'object') {
    return null;
  }
  return apiConfig as ApiConfig;
}

/**
 * Mirror of sveltekit-generator.ts `resolveStandardCrudActions`, narrowed to
 * the mutating subset the sync contract can carry. Kept local so this module
 * needs no exports added to the (parallel-edited) shared generator file.
 */
function resolveMutatingActions(apiConfig: unknown): MutatingAction[] {
  if (apiConfig === false) return [];
  if (
    apiConfig === true ||
    apiConfig === undefined ||
    typeof apiConfig !== 'object'
  ) {
    return [...MUTATING_ACTIONS];
  }

  const config = apiConfig as { include?: string[]; exclude?: string[] };
  let actions: MutatingAction[] = Array.isArray(config.include)
    ? MUTATING_ACTIONS.filter((action) => config.include?.includes(action))
    : [...MUTATING_ACTIONS];
  if (Array.isArray(config.exclude)) {
    const excluded = config.exclude;
    actions = actions.filter((action) => !excluded.includes(action));
  }
  return actions;
}

/** Mirror of sveltekit-generator.ts `getApiPublicAccess` (fail-closed). */
function getApiPublicAccess(apiConfig: unknown): boolean | 'read' {
  const config = getApiConfigObject(apiConfig);
  const value = config?.public;
  if (value === true || value === 'read') {
    return value;
  }
  return false;
}

/** Mirror of sveltekit-generator.ts `collectReadonlyFieldNames` (#1540, 2b). */
function collectReadonlyFieldNames(objectDef: SmartObjectDefinition): string[] {
  const fields = objectDef.fields || {};
  const names: string[] = [];
  for (const [name, def] of Object.entries(fields)) {
    const meta = (def as { _meta?: Record<string, unknown> })._meta;
    if (
      (def as { readonly?: boolean }).readonly === true ||
      meta?.readonly === true
    ) {
      names.push(name);
    }
  }
  return names;
}

/** Mirror of sveltekit-generator.ts `getApiWritableAllowlist`. */
function getApiWritableAllowlist(apiConfig: unknown): string[] | null {
  const config = getApiConfigObject(apiConfig);
  return Array.isArray(config?.writable) ? config.writable : null;
}

/** Mirror of sveltekit-generator.ts `isCollectionClass`. */
function isCollectionClass(objectDef: SmartObjectDefinition): boolean {
  return objectDef.extends === 'SmrtCollection' || !!objectDef.extendsTypeArg;
}

function extractSimpleClassName(qualifiedName: string): string {
  const colonIndex = qualifiedName.indexOf(':');
  return colonIndex === -1
    ? qualifiedName
    : qualifiedName.substring(colonIndex + 1);
}

/**
 * Collect the syncable targets from a manifest: non-collection objects whose
 * API config is enabled and exposes at least one mutating action.
 */
export function collectSyncApplyTargets(
  manifest: SmartObjectManifest,
): SyncTargetSpec[] {
  const targets: SyncTargetSpec[] = [];

  for (const [className, objectDef] of Object.entries(manifest.objects)) {
    if (isCollectionClass(objectDef)) continue;

    const apiConfig = objectDef.decoratorConfig?.api;
    if (apiConfig === false) continue;

    const ops = resolveMutatingActions(apiConfig);
    if (ops.length === 0) continue;

    if (!objectDef.collection) continue;

    targets.push({
      segment: objectDef.collection,
      className: extractSimpleClassName(className),
      ops,
      readonlyFields: collectReadonlyFieldNames(objectDef),
      writableAllowlist: getApiWritableAllowlist(apiConfig),
      publicAccess: getApiPublicAccess(apiConfig),
      tenantScoped: !!objectDef.decoratorConfig?.tenantScoped,
    });
  }

  return targets.sort((a, b) => a.segment.localeCompare(b.segment));
}

function serializeTargets(targets: SyncTargetSpec[]): string {
  const entries = targets.map((target) => {
    const fields = [
      `className: ${JSON.stringify(target.className)}`,
      `ops: ${JSON.stringify(target.ops)}`,
      `readonlyFields: ${JSON.stringify(target.readonlyFields)}`,
      `writableAllowlist: ${JSON.stringify(target.writableAllowlist)}`,
      `publicAccess: ${JSON.stringify(target.publicAccess)}`,
    ];
    return `  ${JSON.stringify(target.segment)}: {\n    ${fields.join(',\n    ')},\n  },`;
  });
  return `{\n${entries.join('\n')}\n}`;
}

/**
 * Render the generated `+server.ts` content for the sync-apply route.
 * Exported for tests.
 */
export function generateSyncApplyRouteTemplate(
  targets: SyncTargetSpec[],
): string {
  const anyTenantScoped = targets.some((target) => target.tenantScoped);

  const tenantHelper = anyTenantScoped
    ? `
import { enterTenantContext, hasTenantContext } from '@happyvertical/smrt-tenancy';

function establishTenantContext(locals: unknown): void {
  if (hasTenantContext()) return;
  if (!locals || typeof locals !== 'object') return;
  const l = locals as Record<string, unknown>;
  const user = l.user as Record<string, unknown> | undefined;
  const session = l.session as Record<string, unknown> | undefined;
  const tenantId = l.tenantId ?? user?.tenantId ?? session?.tenantId;
  if (typeof tenantId === 'string' && tenantId) {
    enterTenantContext({ tenantId });
  }
}
`
    : '';

  return `${AUTO_GENERATED_ROUTE_HEADER}
// DO NOT EDIT - changes will be overwritten
//
// Idempotent sync-apply batch write contract (#1759) — the shared write path
// for the web offline outbox (#1762) and the KMP mobile write queue (#1739).
// Contract: docs/content/architecture/sync-apply-contract.md

import {
  applySyncWritablePolicy,
  processSyncApplyBatch,
  type SyncApplyOp,
  type SyncApplyTarget,
} from '@happyvertical/smrt-core';
import { json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';
${tenantHelper}
interface SyncTargetConfig {
  className: string;
  ops: SyncApplyOp[];
  readonlyFields: string[];
  writableAllowlist: string[] | null;
  publicAccess: boolean | 'read';
}

// One entry per syncable model, keyed by the collection route segment its
// generated CRUD routes use.
const SYNC_TARGETS: Record<string, SyncTargetConfig> = ${serializeTargets(targets)};

// Fail-closed authorization (#1540): sync mutations require an authenticated
// principal on \`locals\` unless the target model is \`api: { public: true }\`.
function hasAuthenticatedPrincipal(locals: unknown): boolean {
  if (!locals || typeof locals !== 'object') return false;
  const l = locals as Record<string, unknown>;
  const isResolvedPrincipal = (v: unknown) =>
    typeof v === 'object' && v !== null;
  return (
    isResolvedPrincipal(l.user) ||
    isResolvedPrincipal(l.session) ||
    l.smrtAuth === true
  );
}

export const POST: RequestHandler = async ({ locals, request }) => {
  const authenticated = hasAuthenticatedPrincipal(locals);
${anyTenantScoped ? '  establishTenantContext(locals);\n' : ''}
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return json(
      { error: { code: 'invalid_batch', message: 'Invalid JSON body' } },
      { status: 400 },
    );
  }

  const outcome = await processSyncApplyBatch(body, {
    resolveTarget: async (segment: string): Promise<SyncApplyTarget | null> => {
      const target = SYNC_TARGETS[segment];
      if (!target) return null;
      const collection = await getCollection(target.className);
      return {
        objectName: target.className,
        collection,
        isOpAllowed: (op: SyncApplyOp) => target.ops.includes(op),
        authorize: () =>
          authenticated || target.publicAccess === true
            ? ('ok' as const)
            : ('auth_required' as const),
        prepare: (payload: Record<string, unknown>) =>
          applySyncWritablePolicy(payload, {
            readonlyFields: target.readonlyFields,
            writableAllowlist: target.writableAllowlist,
          }),
      };
    },
  });

  return json(outcome.body, { status: outcome.status });
};
`;
}

/**
 * Generate `{routesDir}/sync/apply/+server.ts` for the manifest's syncable
 * models. Returns true when a route was written. Skips generation (with a
 * warning) if a non-generated file already occupies the path, and writes
 * nothing when the manifest has no syncable models.
 */
export function generateSyncApplyRoute(
  projectRoot: string,
  manifest: SmartObjectManifest,
  options: SvelteKitOptions,
): boolean {
  const targets = collectSyncApplyTargets(manifest);
  if (targets.length === 0) {
    return false;
  }

  const routeDir = join(projectRoot, options.routesDir, 'sync', 'apply');
  const routePath = join(routeDir, '+server.ts');

  if (existsSync(routePath)) {
    const existing = readFileSync(routePath, 'utf-8');
    if (!existing.startsWith(AUTO_GENERATED_ROUTE_HEADER)) {
      console.warn(
        `[smrt] Skipping sync-apply route - ${routePath} exists and is not generated`,
      );
      return false;
    }
  }

  if (!existsSync(routeDir)) {
    mkdirSync(routeDir, { recursive: true });
  }

  writeFileSync(routePath, generateSyncApplyRouteTemplate(targets), 'utf-8');
  console.log(`[smrt] Generated: ${routePath}`);
  return true;
}
