// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Custom action: getTransparencyAction
export const GET: RequestHandler = async ({ params }) => {
  const collection = await getCollection<any>(
    '@happyvertical/smrt-content:ContentVersion',
  );
  const item = await collection.get(params.id);
  if (!item)
    throw error(404, '@happyvertical/smrt-content:ContentVersion not found');

  const result = await item.getTransparencyAction();

  return json({ action: 'getTransparencyAction', result });
};
